// Code generated by `ubx sdk gen` from azure_sql_syncmembers_sync_member. DO NOT EDIT.
package sql

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type SyncmembersSyncMember_Value_Properties struct {
	DatabaseName any
	DatabaseType any
	Password any
	PrivateEndpointName any
	ServerName any
	SqlServerDatabaseId any
	SyncAgentId any
	SyncDirection any
	SyncMemberAzureDatabaseResourceId any
	SyncState any
	UsePrivateLinkConnection any
	UserName any
}

type SyncmembersSyncMember_Value struct {
	Properties any
}

type SyncmembersSyncMemberConfig struct {
	DatabaseName any
	ServerName any
	SyncGroupName any
}

type SyncmembersSyncMemberAttrs struct {
	DatabaseName any
	// The link to the next page of items
	NextLink any
	ServerName any
	SyncGroupName any
	// The SyncMember items on this page
	Value any
}

var SyncmembersSyncMember = ubx.DataSourceBinding{
	WireType: "azure_sql_syncmembers_sync_member",
	Fields: ubx.FieldMap{
		"DatabaseName": ubx.FieldSpec{WireName: "database_name"},
		"ServerName": ubx.FieldSpec{WireName: "server_name"},
		"SyncGroupName": ubx.FieldSpec{WireName: "sync_group_name"},
	},
}
