// Code generated by `ubx sdk gen` from azure_sql_syncgroups_sync_group. DO NOT EDIT.
package sql

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type SyncgroupsSyncGroup_Properties_Schema_Tables_Columns struct {
	DataSize   any
	DataType   any
	QuotedName any
}

type SyncgroupsSyncGroup_Properties_Schema_Tables struct {
	Columns    any
	QuotedName any
}

type SyncgroupsSyncGroup_Properties_Schema struct {
	// Name of master sync member where the schema is from.
	MasterSyncMemberName any
	// List of tables in sync group schema.
	Tables any
}

type SyncgroupsSyncGroup_Properties struct {
	// Conflict logging retention period.
	ConflictLoggingRetentionInDays any
	// Conflict resolution policy of the sync group.
	ConflictResolutionPolicy any
	// If conflict logging is enabled.
	EnableConflictLogging any
	// Password for the sync group hub database credential.
	HubDatabasePassword any
	// User name for the sync group hub database credential.
	HubDatabaseUserName any
	// Sync interval of the sync group.
	Interval any
	// Last sync time of the sync group.
	LastSyncTime any
	// Private endpoint name of the sync group if use private link connection is enabled.
	PrivateEndpointName any
	// Properties of sync group schema.
	Schema any
	// ARM resource id of the sync database in the sync group.
	SyncDatabaseId any
	// Sync state of the sync group.
	SyncState any
	// If use private link connection is enabled.
	UsePrivateLinkConnection any
}

type SyncgroupsSyncGroup_Sku struct {
	// Capacity of the particular SKU.
	Capacity any
	// If the service has different generations of hardware, for the same SKU, then that can be captured here.
	Family any
	// The name of the SKU, typically, a letter + Number code, e.g. P3.
	Name any
	// Size of the particular SKU
	Size any
	// The tier or edition of the particular SKU, e.g. Basic, Premium.
	Tier any
}

var SyncgroupsSyncGroup_Properties_Schema_Tables_ColumnsFields = ubx.FieldMap{
	"DataSize":   ubx.FieldSpec{WireName: "data_size"},
	"DataType":   ubx.FieldSpec{WireName: "data_type"},
	"QuotedName": ubx.FieldSpec{WireName: "quoted_name"},
}

var SyncgroupsSyncGroup_Properties_Schema_TablesFields = ubx.FieldMap{
	"Columns": ubx.FieldSpec{
		WireName: "columns",
		Kind:     "list",
		Fields:   SyncgroupsSyncGroup_Properties_Schema_Tables_ColumnsFields,
	},
	"QuotedName": ubx.FieldSpec{WireName: "quoted_name"},
}

var SyncgroupsSyncGroup_Properties_SchemaFields = ubx.FieldMap{
	"MasterSyncMemberName": ubx.FieldSpec{WireName: "master_sync_member_name"},
	"Tables": ubx.FieldSpec{
		WireName: "tables",
		Kind:     "list",
		Fields:   SyncgroupsSyncGroup_Properties_Schema_TablesFields,
	},
}

var SyncgroupsSyncGroup_PropertiesFields = ubx.FieldMap{
	"ConflictLoggingRetentionInDays": ubx.FieldSpec{WireName: "conflict_logging_retention_in_days"},
	"ConflictResolutionPolicy":       ubx.FieldSpec{WireName: "conflict_resolution_policy"},
	"EnableConflictLogging":          ubx.FieldSpec{WireName: "enable_conflict_logging"},
	"HubDatabasePassword":            ubx.FieldSpec{WireName: "hub_database_password"},
	"HubDatabaseUserName":            ubx.FieldSpec{WireName: "hub_database_user_name"},
	"Interval":                       ubx.FieldSpec{WireName: "interval"},
	"LastSyncTime":                   ubx.FieldSpec{WireName: "last_sync_time"},
	"PrivateEndpointName":            ubx.FieldSpec{WireName: "private_endpoint_name"},
	"Schema": ubx.FieldSpec{
		WireName: "schema",
		Kind:     "object",
		Fields:   SyncgroupsSyncGroup_Properties_SchemaFields,
	},
	"SyncDatabaseId":           ubx.FieldSpec{WireName: "sync_database_id"},
	"SyncState":                ubx.FieldSpec{WireName: "sync_state"},
	"UsePrivateLinkConnection": ubx.FieldSpec{WireName: "use_private_link_connection"},
}

var SyncgroupsSyncGroup_SkuFields = ubx.FieldMap{
	"Capacity": ubx.FieldSpec{WireName: "capacity"},
	"Family":   ubx.FieldSpec{WireName: "family"},
	"Name":     ubx.FieldSpec{WireName: "name"},
	"Size":     ubx.FieldSpec{WireName: "size"},
	"Tier":     ubx.FieldSpec{WireName: "tier"},
}

type SyncgroupsSyncGroupConfig struct {
	// Properties of a sync group with support to MI.
	Properties any
	// An ARM Resource SKU.
	Sku any
}

type SyncgroupsSyncGroupAttrs struct {
	// Properties of a sync group with support to MI.
	Properties any
	// An ARM Resource SKU.
	Sku any
}

var SyncgroupsSyncGroup = ubx.ResourceBinding{
	WireType: "azure_sql_syncgroups_sync_group",
	Fields: ubx.FieldMap{
		"Properties": ubx.FieldSpec{
			WireName: "properties",
			Kind:     "object",
			Fields:   SyncgroupsSyncGroup_PropertiesFields,
		},
		"Sku": ubx.FieldSpec{
			WireName: "sku",
			Kind:     "object",
			Fields:   SyncgroupsSyncGroup_SkuFields,
		},
	},
}
