// Code generated by `ubx sdk gen` from azure_netapp_netapp_volume_quota_rule. DO NOT EDIT.
package netapp

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type NetappVolumeQuotaRule_Properties struct {
	// Gets the status of the VolumeQuotaRule at the time the operation was called.
	ProvisioningState any
	// Size of quota
	QuotaSizeInKiBs any
	// UserID/GroupID/SID based on the quota target type. UserID and groupID can be found by running ‘id’ or ‘getent’ command for the user or group and SID can be found by running <wmic useraccount where name='user-name' get sid>
	QuotaTarget any
	// Type of quota
	QuotaType any
}

var NetappVolumeQuotaRule_PropertiesFields = ubx.FieldMap{
		"ProvisioningState": ubx.FieldSpec{WireName: "provisioning_state"},
		"QuotaSizeInKiBs": ubx.FieldSpec{WireName: "quota_size_in_ki_bs"},
		"QuotaTarget": ubx.FieldSpec{WireName: "quota_target"},
		"QuotaType": ubx.FieldSpec{WireName: "quota_type"},
	}

type NetappVolumeQuotaRuleConfig struct {
	// Volume Quota Rule properties
	Properties any
}

type NetappVolumeQuotaRuleAttrs struct {
	// Volume Quota Rule properties
	Properties any
}

var NetappVolumeQuotaRule = ubx.ResourceBinding{
	WireType: "azure_netapp_netapp_volume_quota_rule",
	Fields: ubx.FieldMap{
		"Properties": ubx.FieldSpec{
			WireName: "properties",
			Kind: "object",
			Fields: NetappVolumeQuotaRule_PropertiesFields,
		},
	},
}
