// Code generated by `ubx sdk gen` from azure_apimanagement_apimpolicies_policy_contract_2. DO NOT EDIT.
package apimanagement

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ApimpoliciesPolicyContract2_Properties struct {
	// Format of the policyContent.
	Format any
	// Contents of the Policy as defined by the format.
	Value any
}

var ApimpoliciesPolicyContract2_PropertiesFields = ubx.FieldMap{
		"Format": ubx.FieldSpec{WireName: "format"},
		"Value": ubx.FieldSpec{WireName: "value"},
	}

type ApimpoliciesPolicyContract2Config struct {
	// Policy contract Properties.
	Properties any
}

type ApimpoliciesPolicyContract2Attrs struct {
	// Policy contract Properties.
	Properties any
}

var ApimpoliciesPolicyContract2 = ubx.ResourceBinding{
	WireType: "azure_apimanagement_apimpolicies_policy_contract_2",
	Fields: ubx.FieldMap{
		"Properties": ubx.FieldSpec{
			WireName: "properties",
			Kind: "object",
			Fields: ApimpoliciesPolicyContract2_PropertiesFields,
		},
	},
}
