# Code generated by `ubx sdk gen` from azure_mysql_openapi_firewall_rule. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OpenapiFirewallRule_Value_Properties:
    end_ip_address: Any = None
    start_ip_address: Any = None

@dataclasses.dataclass
class OpenapiFirewallRule_Value:
    properties: Any = None

@dataclasses.dataclass
class OpenapiFirewallRuleConfig:
    server_name: Any = None

@dataclasses.dataclass
class OpenapiFirewallRuleAttrs:
    # The link to the next page of items
    next_link: Any = None
    server_name: Any = None
    # The FirewallRule items on this page
    value: Any = None

OpenapiFirewallRule = ubx.DataSourceBinding(
    wire_type="azure_mysql_openapi_firewall_rule",
    fields={
        "server_name": ubx.FieldSpec(wire_name="server_name"),
    },
)
