// Code generated by `ubx sdk gen` from azure_synapse_firewallrule_ip_firewall_rule_info. DO NOT EDIT.
package synapse

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type FirewallruleIpFirewallRuleInfo_Properties struct {
	// The end IP address of the firewall rule. Must be IPv4 format. Must be greater than or equal to startIpAddress
	EndIpAddress any
	// Resource provisioning state
	ProvisioningState any
	// The start IP address of the firewall rule. Must be IPv4 format
	StartIpAddress any
}

var FirewallruleIpFirewallRuleInfo_PropertiesFields = ubx.FieldMap{
	"EndIpAddress":      ubx.FieldSpec{WireName: "end_ip_address"},
	"ProvisioningState": ubx.FieldSpec{WireName: "provisioning_state"},
	"StartIpAddress":    ubx.FieldSpec{WireName: "start_ip_address"},
}

type FirewallruleIpFirewallRuleInfoConfig struct {
	// IP firewall rule properties
	Properties any
}

type FirewallruleIpFirewallRuleInfoAttrs struct {
	// IP firewall rule properties
	Properties any
}

var FirewallruleIpFirewallRuleInfo = ubx.ResourceBinding{
	WireType: "azure_synapse_firewallrule_ip_firewall_rule_info",
	Fields: ubx.FieldMap{
		"Properties": ubx.FieldSpec{
			WireName: "properties",
			Kind:     "object",
			Fields:   FirewallruleIpFirewallRuleInfo_PropertiesFields,
		},
	},
}
