// Code generated by `ubx sdk gen` from azure_logic_integration_account_schema_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface IntegrationAccountSchemaList_Value_Properties_ContentLink_ContentHash {
  algorithm?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface IntegrationAccountSchemaList_Value_Properties_ContentLink {
  contentHash?: IntegrationAccountSchemaList_Value_Properties_ContentLink_ContentHash | Computed<IntegrationAccountSchemaList_Value_Properties_ContentLink_ContentHash>;
  contentSize?: number | Computed<number>;
  contentVersion?: string | Computed<string>;
  metadata?: unknown | Computed<unknown>;
  uri?: string | Computed<string>;
}

export interface IntegrationAccountSchemaList_Value_Properties {
  changedTime?: string | Computed<string>;
  content?: string | Computed<string>;
  contentLink?: IntegrationAccountSchemaList_Value_Properties_ContentLink | Computed<IntegrationAccountSchemaList_Value_Properties_ContentLink>;
  contentType?: string | Computed<string>;
  createdTime?: string | Computed<string>;
  documentName?: string | Computed<string>;
  fileName?: string | Computed<string>;
  metadata?: unknown | Computed<unknown>;
  schemaType?: string | Computed<string>;
  targetNamespace?: string | Computed<string>;
}

export interface IntegrationAccountSchemaList_Value {
  properties?: IntegrationAccountSchemaList_Value_Properties | Computed<IntegrationAccountSchemaList_Value_Properties>;
}

export interface IntegrationAccountSchemaListConfig {
  apiVersion: string | Computed<string>;
  integrationAccountName: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  subscriptionId: string | Computed<string>;
}

export interface IntegrationAccountSchemaListAttrs {
  apiVersion: string;
  integrationAccountName: string;
  /** The URL to get the next set of results. */
  nextLink: string;
  resourceGroupName: string;
  subscriptionId: string;
  /** The list of integration account schemas. */
  value: IntegrationAccountSchemaList_Value[];
}

export const IntegrationAccountSchemaList: DataSourceBinding<IntegrationAccountSchemaListConfig, IntegrationAccountSchemaListAttrs> = {
  wireType: "azure_logic_integration_account_schema_list",
  fields: {
    apiVersion: "api_version",
    integrationAccountName: "integration_account_name",
    resourceGroupName: "resource_group_name",
    subscriptionId: "subscription_id",
  },
};
