// Code generated by `ubx sdk gen` from azure_logic_workflow_run_action_repetition_definition_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface WorkflowRunActionRepetitionDefinitionList_Value_Properties_RepetitionIndexes {
  itemIndex?: number | Computed<number>;
  scopeName?: string | Computed<string>;
}

export interface WorkflowRunActionRepetitionDefinitionList_Value_Properties {
  repetitionIndexes?: WorkflowRunActionRepetitionDefinitionList_Value_Properties_RepetitionIndexes[] | Computed<WorkflowRunActionRepetitionDefinitionList_Value_Properties_RepetitionIndexes[]>;
}

export interface WorkflowRunActionRepetitionDefinitionList_Value {
  properties?: WorkflowRunActionRepetitionDefinitionList_Value_Properties | Computed<WorkflowRunActionRepetitionDefinitionList_Value_Properties>;
}

export interface WorkflowRunActionRepetitionDefinitionListConfig {
  actionName: string | Computed<string>;
  apiVersion: string | Computed<string>;
  resourceGroupName: string | Computed<string>;
  runName: string | Computed<string>;
  subscriptionId: string | Computed<string>;
  workflowName: string | Computed<string>;
}

export interface WorkflowRunActionRepetitionDefinitionListAttrs {
  actionName: string;
  apiVersion: string;
  /** The link used to get the next page of recommendations. */
  nextLink: string;
  resourceGroupName: string;
  runName: string;
  subscriptionId: string;
  value: WorkflowRunActionRepetitionDefinitionList_Value[];
  workflowName: string;
}

export const WorkflowRunActionRepetitionDefinitionList: DataSourceBinding<WorkflowRunActionRepetitionDefinitionListConfig, WorkflowRunActionRepetitionDefinitionListAttrs> = {
  wireType: "azure_logic_workflow_run_action_repetition_definition_list",
  fields: {
    actionName: "action_name",
    apiVersion: "api_version",
    resourceGroupName: "resource_group_name",
    runName: "run_name",
    subscriptionId: "subscription_id",
    workflowName: "workflow_name",
  },
};
