// Code generated by `ubx sdk gen` from azure_netapp_backup_vault. DO NOT EDIT.
package netapp

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type BackupVault_Value_Properties struct {
	ProvisioningState any
}

type BackupVault_Value struct {
	Properties any
}

type BackupVaultConfig struct {
	AccountName any
}

type BackupVaultAttrs struct {
	AccountName any
	// The link to the next page of items
	NextLink any
	// The BackupVault items on this page
	Value any
}

var BackupVault = ubx.DataSourceBinding{
	WireType: "azure_netapp_backup_vault",
	Fields: ubx.FieldMap{
		"AccountName": ubx.FieldSpec{WireName: "account_name"},
	},
}
