// Code generated by `ubx sdk gen` from azure_hybridkubernetes_connectedclusters_connected_cluster. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ConnectedclustersConnectedCluster_Identity {
  /** The principal id of connected cluster identity. This property will only be provided for a system assigned identity. */
  principalId?: string | Computed<string>;
  /** The tenant id associated with the connected cluster. This property will only be provided for a system assigned identity. */
  tenantId?: string | Computed<string>;
  /** The type of identity used for the connected cluster. The type 'SystemAssigned, includes a system created identity. The type 'None' means no identity is assigned to the connected cluster. */
  type: string | Computed<string>;
}

export interface ConnectedclustersConnectedCluster_Properties_AadProfile {
  /** The list of AAD group object IDs that will have admin role of the cluster. */
  adminGroupObjectIds?: string[] | Computed<string[]>;
  /** Whether to enable Azure RBAC for Kubernetes authorization. */
  enableAzureRbac?: boolean | Computed<boolean>;
  /** The AAD tenant ID to use for authentication. If not specified, will use the tenant of the deployment subscription. */
  tenantId?: string | Computed<string>;
}

export interface ConnectedclustersConnectedCluster_Properties_ArcAgentProfile_AgentErrors {
  component?: string | Computed<string>;
  message?: string | Computed<string>;
  severity?: string | Computed<string>;
  time?: string | Computed<string>;
}

export interface ConnectedclustersConnectedCluster_Properties_ArcAgentProfile_SystemComponents {
  currentVersion?: string | Computed<string>;
  majorVersion?: number | Computed<number>;
  type?: string | Computed<string>;
  userSpecifiedVersion?: string | Computed<string>;
}

export interface ConnectedclustersConnectedCluster_Properties_ArcAgentProfile {
  /** Indicates whether the Arc agents on the be upgraded automatically to the latest version. Defaults to Enabled. */
  agentAutoUpgrade?: string | Computed<string>;
  /** List of arc agentry and system components errors on the cluster resource. */
  agentErrors?: ConnectedclustersConnectedCluster_Properties_ArcAgentProfile_AgentErrors[] | Computed<ConnectedclustersConnectedCluster_Properties_ArcAgentProfile_AgentErrors[]>;
  /** Represents the current state of the Arc agentry and its dependent components. */
  agentState?: string | Computed<string>;
  /** Version of the Arc agents to be installed on the cluster resource */
  desiredAgentVersion?: string | Computed<string>;
  /** List of system extensions that are installed on the cluster resource. */
  systemComponents?: ConnectedclustersConnectedCluster_Properties_ArcAgentProfile_SystemComponents[] | Computed<ConnectedclustersConnectedCluster_Properties_ArcAgentProfile_SystemComponents[]>;
}

export interface ConnectedclustersConnectedCluster_Properties_ArcAgentryConfigurations {
  feature?: string | Computed<string>;
  protectedSettings?: Record<string, string> | Computed<Record<string, string>>;
  settings?: Record<string, string> | Computed<Record<string, string>>;
}

export interface ConnectedclustersConnectedCluster_Properties_Gateway {
  /** Indicates whether the gateway for arc router connectivity is enabled. */
  enabled?: boolean | Computed<boolean>;
}

export interface ConnectedclustersConnectedCluster_Properties_OidcIssuerProfile {
  /** Whether to enable oidc issuer for workload identity integration. */
  enabled?: boolean | Computed<boolean>;
  /** The issuer url for hybrid clusters connected to Arc used for the workload identity feature. */
  issuerUrl?: string | Computed<string>;
  /** The issuer url for public cloud clusters - AKS, EKS, GKE - used for the workload identity feature. */
  selfHostedIssuerUrl?: string | Computed<string>;
}

export interface ConnectedclustersConnectedCluster_Properties_SecurityProfile {
  /** The workload identity feature webhook. */
  workloadIdentity?: ConnectedclustersConnectedCluster_Properties_Gateway | Computed<ConnectedclustersConnectedCluster_Properties_Gateway>;
}

export interface ConnectedclustersConnectedCluster_Properties {
  /** AAD Profile specifies attributes for Azure Active Directory integration. */
  aadProfile?: ConnectedclustersConnectedCluster_Properties_AadProfile | Computed<ConnectedclustersConnectedCluster_Properties_AadProfile>;
  /** Base64 encoded public certificate used by the agent to do the initial handshake to the backend services in Azure. */
  agentPublicKeyCertificate: string | Computed<string>;
  /** Version of the agent running on the connected cluster resource */
  agentVersion?: string | Computed<string>;
  /** Defines the Arc Agent properties for the clusters. */
  arcAgentProfile?: ConnectedclustersConnectedCluster_Properties_ArcAgentProfile | Computed<ConnectedclustersConnectedCluster_Properties_ArcAgentProfile>;
  /** Configuration settings for customizing the behavior of the connected cluster. */
  arcAgentryConfigurations?: ConnectedclustersConnectedCluster_Properties_ArcAgentryConfigurations[] | Computed<ConnectedclustersConnectedCluster_Properties_ArcAgentryConfigurations[]>;
  /** Indicates whether Azure Hybrid Benefit is opted in */
  azureHybridBenefit?: string | Computed<string>;
  /** Represents the connectivity status of the connected cluster. */
  connectivityStatus?: string | Computed<string>;
  /** The Kubernetes distribution running on this connected cluster. */
  distribution?: string | Computed<string>;
  /** The Kubernetes distribution version on this connected cluster. */
  distributionVersion?: string | Computed<string>;
  gateway?: ConnectedclustersConnectedCluster_Properties_Gateway | Computed<ConnectedclustersConnectedCluster_Properties_Gateway>;
  /** The infrastructure on which the Kubernetes cluster represented by this connected cluster is running on. */
  infrastructure?: string | Computed<string>;
  /** The Kubernetes version of the connected cluster resource */
  kubernetesVersion?: string | Computed<string>;
  /** Time representing the last instance when heart beat was received from the cluster */
  lastConnectivityTime?: string | Computed<string>;
  /** Expiration time of the managed identity certificate */
  managedIdentityCertificateExpirationTime?: string | Computed<string>;
  /** More properties related to the Connected Cluster */
  miscellaneousProperties?: Record<string, string> | Computed<Record<string, string>>;
  /** Connected cluster offering */
  offering?: string | Computed<string>;
  /** OIDC Issuer Profile specifies attributes for workload identity integration. */
  oidcIssuerProfile?: ConnectedclustersConnectedCluster_Properties_OidcIssuerProfile | Computed<ConnectedclustersConnectedCluster_Properties_OidcIssuerProfile>;
  /** This is populated only if privateLinkState is enabled. The resource id of the private link scope this connected cluster is assigned to, if any. */
  privateLinkScopeResourceId?: string | Computed<string>;
  /** Property which describes the state of private link on a connected cluster resource. */
  privateLinkState?: string | Computed<string>;
  /** The current deployment state of connectedClusters. */
  provisioningState?: string | Computed<string>;
  /** Security Profile specifies attributes for cluster security features. */
  securityProfile?: ConnectedclustersConnectedCluster_Properties_SecurityProfile | Computed<ConnectedclustersConnectedCluster_Properties_SecurityProfile>;
  /** Number of CPU cores present in the connected cluster resource */
  totalCoreCount?: number | Computed<number>;
  /** Number of nodes present in the connected cluster resource */
  totalNodeCount?: number | Computed<number>;
}

const ConnectedclustersConnectedCluster_IdentityFields: FieldMap = {
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
};

const ConnectedclustersConnectedCluster_Properties_AadProfileFields: FieldMap = {
  adminGroupObjectIds: "admin_group_object_ids",
  enableAzureRbac: "enable_azure_rbac",
  tenantId: "tenant_id",
};

const ConnectedclustersConnectedCluster_Properties_ArcAgentProfile_AgentErrorsFields: FieldMap = {
  component: "component",
  message: "message",
  severity: "severity",
  time: "time",
};

const ConnectedclustersConnectedCluster_Properties_ArcAgentProfile_SystemComponentsFields: FieldMap = {
  currentVersion: "current_version",
  majorVersion: "major_version",
  type: "type",
  userSpecifiedVersion: "user_specified_version",
};

const ConnectedclustersConnectedCluster_Properties_ArcAgentProfileFields: FieldMap = {
  agentAutoUpgrade: "agent_auto_upgrade",
  agentErrors: {
    wireName: "agent_errors",
    kind: "list",
    fields: ConnectedclustersConnectedCluster_Properties_ArcAgentProfile_AgentErrorsFields,
  },
  agentState: "agent_state",
  desiredAgentVersion: "desired_agent_version",
  systemComponents: {
    wireName: "system_components",
    kind: "list",
    fields: ConnectedclustersConnectedCluster_Properties_ArcAgentProfile_SystemComponentsFields,
  },
};

const ConnectedclustersConnectedCluster_Properties_ArcAgentryConfigurationsFields: FieldMap = {
  feature: "feature",
  protectedSettings: "protected_settings",
  settings: "settings",
};

const ConnectedclustersConnectedCluster_Properties_GatewayFields: FieldMap = {
  enabled: "enabled",
};

const ConnectedclustersConnectedCluster_Properties_OidcIssuerProfileFields: FieldMap = {
  enabled: "enabled",
  issuerUrl: "issuer_url",
  selfHostedIssuerUrl: "self_hosted_issuer_url",
};

const ConnectedclustersConnectedCluster_Properties_SecurityProfileFields: FieldMap = {
  workloadIdentity: {
    wireName: "workload_identity",
    kind: "object",
    fields: ConnectedclustersConnectedCluster_Properties_GatewayFields,
  },
};

const ConnectedclustersConnectedCluster_PropertiesFields: FieldMap = {
  aadProfile: {
    wireName: "aad_profile",
    kind: "object",
    fields: ConnectedclustersConnectedCluster_Properties_AadProfileFields,
  },
  agentPublicKeyCertificate: "agent_public_key_certificate",
  agentVersion: "agent_version",
  arcAgentProfile: {
    wireName: "arc_agent_profile",
    kind: "object",
    fields: ConnectedclustersConnectedCluster_Properties_ArcAgentProfileFields,
  },
  arcAgentryConfigurations: {
    wireName: "arc_agentry_configurations",
    kind: "list",
    fields: ConnectedclustersConnectedCluster_Properties_ArcAgentryConfigurationsFields,
  },
  azureHybridBenefit: "azure_hybrid_benefit",
  connectivityStatus: "connectivity_status",
  distribution: "distribution",
  distributionVersion: "distribution_version",
  gateway: {
    wireName: "gateway",
    kind: "object",
    fields: ConnectedclustersConnectedCluster_Properties_GatewayFields,
  },
  infrastructure: "infrastructure",
  kubernetesVersion: "kubernetes_version",
  lastConnectivityTime: "last_connectivity_time",
  managedIdentityCertificateExpirationTime: "managed_identity_certificate_expiration_time",
  miscellaneousProperties: "miscellaneous_properties",
  offering: "offering",
  oidcIssuerProfile: {
    wireName: "oidc_issuer_profile",
    kind: "object",
    fields: ConnectedclustersConnectedCluster_Properties_OidcIssuerProfileFields,
  },
  privateLinkScopeResourceId: "private_link_scope_resource_id",
  privateLinkState: "private_link_state",
  provisioningState: "provisioning_state",
  securityProfile: {
    wireName: "security_profile",
    kind: "object",
    fields: ConnectedclustersConnectedCluster_Properties_SecurityProfileFields,
  },
  totalCoreCount: "total_core_count",
  totalNodeCount: "total_node_count",
};

export interface ConnectedclustersConnectedClusterConfig {
  /** Identity for the connected cluster. */
  identity: ConnectedclustersConnectedCluster_Identity | Computed<ConnectedclustersConnectedCluster_Identity>;
  /** Indicates the kind of Arc connected cluster based on host infrastructure. */
  kind?: string | Computed<string>;
  /** Properties of the connected cluster. */
  properties: ConnectedclustersConnectedCluster_Properties | Computed<ConnectedclustersConnectedCluster_Properties>;
}

export interface ConnectedclustersConnectedClusterAttrs {
  /** Identity for the connected cluster. */
  identity: ConnectedclustersConnectedCluster_Identity;
  /** Indicates the kind of Arc connected cluster based on host infrastructure. */
  kind: string;
  /** Properties of the connected cluster. */
  properties: ConnectedclustersConnectedCluster_Properties;
}

export const ConnectedclustersConnectedCluster: ResourceBinding<ConnectedclustersConnectedClusterConfig, ConnectedclustersConnectedClusterAttrs> = {
  wireType: "azure_hybridkubernetes_connectedclusters_connected_cluster",
  fields: {
    identity: {
      wireName: "identity",
      kind: "object",
      fields: ConnectedclustersConnectedCluster_IdentityFields,
    },
    kind: "kind",
    properties: {
      wireName: "properties",
      kind: "object",
      fields: ConnectedclustersConnectedCluster_PropertiesFields,
    },
  },
};
