// Code generated by `ubx sdk gen` from azure_kusto_private_endpoint_connection_list. DO NOT EDIT.
package kusto

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type PrivateEndpointConnectionList_Value_Properties_PrivateEndpoint struct {
	Id any
}

type PrivateEndpointConnectionList_Value_Properties_PrivateLinkServiceConnectionState struct {
	ActionsRequired any
	Description any
	Status any
}

type PrivateEndpointConnectionList_Value_Properties struct {
	GroupId any
	PrivateEndpoint any
	PrivateLinkServiceConnectionState any
	ProvisioningState any
}

type PrivateEndpointConnectionList_Value struct {
	Properties any
}

type PrivateEndpointConnectionListConfig struct {
	ClusterName any
}

type PrivateEndpointConnectionListAttrs struct {
	ClusterName any
	// Link to the next page of results.
	NextLink any
	// Array of private endpoint connections
	Value any
}

var PrivateEndpointConnectionList = ubx.DataSourceBinding{
	WireType: "azure_kusto_private_endpoint_connection_list",
	Fields: ubx.FieldMap{
		"ClusterName": ubx.FieldSpec{WireName: "cluster_name"},
	},
}
