// Code generated by `ubx sdk gen` from azure_compute_containerservice_container_service_list. DO NOT EDIT.
package compute

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ContainerserviceContainerServiceList_Value_Properties_AgentPoolProfiles struct {
	Count     any
	DnsPrefix any
	Fqdn      any
	Name      any
	VmSize    any
}

type ContainerserviceContainerServiceList_Value_Properties_CustomProfile struct {
	Orchestrator any
}

type ContainerserviceContainerServiceList_Value_Properties_DiagnosticsProfile_VmDiagnostics struct {
	Enabled    any
	StorageUri any
}

type ContainerserviceContainerServiceList_Value_Properties_DiagnosticsProfile struct {
	VmDiagnostics any
}

type ContainerserviceContainerServiceList_Value_Properties_LinuxProfile_Ssh_PublicKeys struct {
	KeyData any
}

type ContainerserviceContainerServiceList_Value_Properties_LinuxProfile_Ssh struct {
	PublicKeys any
}

type ContainerserviceContainerServiceList_Value_Properties_LinuxProfile struct {
	AdminUsername any
	Ssh           any
}

type ContainerserviceContainerServiceList_Value_Properties_MasterProfile struct {
	Count     any
	DnsPrefix any
	Fqdn      any
}

type ContainerserviceContainerServiceList_Value_Properties_OrchestratorProfile struct {
	OrchestratorType any
}

type ContainerserviceContainerServiceList_Value_Properties_ServicePrincipalProfile struct {
	ClientId any
	Secret   any
}

type ContainerserviceContainerServiceList_Value_Properties_WindowsProfile struct {
	AdminPassword any
	AdminUsername any
}

type ContainerserviceContainerServiceList_Value_Properties struct {
	AgentPoolProfiles       any
	CustomProfile           any
	DiagnosticsProfile      any
	LinuxProfile            any
	MasterProfile           any
	OrchestratorProfile     any
	ProvisioningState       any
	ServicePrincipalProfile any
	WindowsProfile          any
}

type ContainerserviceContainerServiceList_Value struct {
	Properties any
}

type ContainerserviceContainerServiceListConfig struct {
	ApiVersion     any
	SubscriptionId any
}

type ContainerserviceContainerServiceListAttrs struct {
	ApiVersion any
	// The URL to get the next set of container service results.
	NextLink       any
	SubscriptionId any
	// the list of container services.
	Value any
}

var ContainerserviceContainerServiceList = ubx.DataSourceBinding{
	WireType: "azure_compute_containerservice_container_service_list",
	Fields: ubx.FieldMap{
		"ApiVersion":     ubx.FieldSpec{WireName: "api_version"},
		"SubscriptionId": ubx.FieldSpec{WireName: "subscription_id"},
	},
}
