# Code generated by `ubx sdk gen` from azure_devcenter_vdi_schedule. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class VdiSchedule_Value_Properties:
    provisioning_state: Any = None

@dataclasses.dataclass
class VdiSchedule_Value:
    properties: Any = None

@dataclasses.dataclass
class VdiScheduleConfig:
    pass

@dataclasses.dataclass
class VdiScheduleAttrs:
    # URL to get the next set of results if there are any.
    next_link: Any = None
    # Current page of results.
    value: Any = None

VdiSchedule = ubx.DataSourceBinding(
    wire_type="azure_devcenter_vdi_schedule",
    fields={
    },
)
