// Code generated by `ubx sdk gen` from azure_notificationhubs_shared_access_authorization_rule_resource. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface SharedAccessAuthorizationRuleResource_Value_Properties {
  claimType?: string | Computed<string>;
  claimValue?: string | Computed<string>;
  createdTime?: string | Computed<string>;
  keyName?: string | Computed<string>;
  modifiedTime?: string | Computed<string>;
  primaryKey?: string | Computed<string>;
  revision?: number | Computed<number>;
  rights?: string[] | Computed<string[]>;
  secondaryKey?: string | Computed<string>;
}

export interface SharedAccessAuthorizationRuleResource_Value {
  location?: string | Computed<string>;
  properties?: SharedAccessAuthorizationRuleResource_Value_Properties | Computed<SharedAccessAuthorizationRuleResource_Value_Properties>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
}

export interface SharedAccessAuthorizationRuleResourceConfig {
  namespaceName: string | Computed<string>;
}

export interface SharedAccessAuthorizationRuleResourceAttrs {
  namespaceName: string;
  /** Gets or sets link to the next set of results. */
  nextLink: string;
  /** Gets or sets result of the List AuthorizationRules operation. */
  value: SharedAccessAuthorizationRuleResource_Value[];
}

export const SharedAccessAuthorizationRuleResource: DataSourceBinding<SharedAccessAuthorizationRuleResourceConfig, SharedAccessAuthorizationRuleResourceAttrs> = {
  wireType: "azure_notificationhubs_shared_access_authorization_rule_resource",
  fields: {
    namespaceName: "namespace_name",
  },
};
