// Code generated by `ubx sdk gen` from azurerm_data_factory_pipeline. DO NOT EDIT.
package data

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type FactoryPipeline_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var FactoryPipeline_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Read": ubx.FieldSpec{WireName: "read"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

type FactoryPipelineConfig struct {
	ActivitiesJson any
	Annotations any
	Concurrency any
	DataFactoryId any
	Description any
	Folder any
	Id any
	MonitorMetricsAfterDuration any
	Name any
	Parameters any
	Variables any
	Timeouts any
}

var FactoryPipeline = ubx.ResourceBinding{
	WireType: "azurerm_data_factory_pipeline",
	Fields: ubx.FieldMap{
		"ActivitiesJson": ubx.FieldSpec{WireName: "activities_json"},
		"Annotations": ubx.FieldSpec{WireName: "annotations"},
		"Concurrency": ubx.FieldSpec{WireName: "concurrency"},
		"DataFactoryId": ubx.FieldSpec{WireName: "data_factory_id"},
		"Description": ubx.FieldSpec{WireName: "description"},
		"Folder": ubx.FieldSpec{WireName: "folder"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"MonitorMetricsAfterDuration": ubx.FieldSpec{WireName: "monitor_metrics_after_duration"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Parameters": ubx.FieldSpec{WireName: "parameters"},
		"Variables": ubx.FieldSpec{WireName: "variables"},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FactoryPipeline_TimeoutsFields,
		},
	},
}
