// Code generated by `ubx sdk gen` from azurerm_data_factory_linked_service_postgresql. DO NOT EDIT.
package data

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type FactoryLinkedServicePostgresql_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var FactoryLinkedServicePostgresql_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Read": ubx.FieldSpec{WireName: "read"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

type FactoryLinkedServicePostgresqlConfig struct {
	AdditionalProperties any
	Annotations any
	ConnectionString any
	DataFactoryId any
	Description any
	Id any
	IntegrationRuntimeName any
	Name any
	Parameters any
	Timeouts any
}

var FactoryLinkedServicePostgresql = ubx.ResourceBinding{
	WireType: "azurerm_data_factory_linked_service_postgresql",
	Fields: ubx.FieldMap{
		"AdditionalProperties": ubx.FieldSpec{WireName: "additional_properties"},
		"Annotations": ubx.FieldSpec{WireName: "annotations"},
		"ConnectionString": ubx.FieldSpec{WireName: "connection_string"},
		"DataFactoryId": ubx.FieldSpec{WireName: "data_factory_id"},
		"Description": ubx.FieldSpec{WireName: "description"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"IntegrationRuntimeName": ubx.FieldSpec{WireName: "integration_runtime_name"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Parameters": ubx.FieldSpec{WireName: "parameters"},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FactoryLinkedServicePostgresql_TimeoutsFields,
		},
	},
}
