// Code generated by `ubx sdk gen` from azurerm_data_protection_backup_vault. DO NOT EDIT.
package data

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ProtectionBackupVault_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type ProtectionBackupVault_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ProtectionBackupVault_IdentityFields = ubx.FieldMap{
		"IdentityIds": ubx.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": ubx.FieldSpec{WireName: "principal_id"},
		"TenantId": ubx.FieldSpec{WireName: "tenant_id"},
		"Type": ubx.FieldSpec{WireName: "type"},
	}

var ProtectionBackupVault_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Read": ubx.FieldSpec{WireName: "read"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

type ProtectionBackupVaultConfig struct {
	CrossRegionRestoreEnabled any
	DatastoreType any
	Id any
	Immutability any
	Location any
	Name any
	Redundancy any
	ResourceGroupName any
	RetentionDurationInDays any
	SoftDelete any
	Tags any
	Identity any
	Timeouts any
}

var ProtectionBackupVault = ubx.ResourceBinding{
	WireType: "azurerm_data_protection_backup_vault",
	Fields: ubx.FieldMap{
		"CrossRegionRestoreEnabled": ubx.FieldSpec{WireName: "cross_region_restore_enabled"},
		"DatastoreType": ubx.FieldSpec{WireName: "datastore_type"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"Immutability": ubx.FieldSpec{WireName: "immutability"},
		"Location": ubx.FieldSpec{WireName: "location"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Redundancy": ubx.FieldSpec{WireName: "redundancy"},
		"ResourceGroupName": ubx.FieldSpec{WireName: "resource_group_name"},
		"RetentionDurationInDays": ubx.FieldSpec{WireName: "retention_duration_in_days"},
		"SoftDelete": ubx.FieldSpec{WireName: "soft_delete"},
		"Tags": ubx.FieldSpec{WireName: "tags"},
		"Identity": ubx.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: ProtectionBackupVault_IdentityFields,
		},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ProtectionBackupVault_TimeoutsFields,
		},
	},
}
