# Code generated by `ubx sdk gen` from azure_attestation_private_link_resource. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class PrivateLinkResource_Value_Properties:
    group_id: Any = None
    required_members: Any = None
    required_zone_names: Any = None

@dataclasses.dataclass
class PrivateLinkResource_Value:
    properties: Any = None

@dataclasses.dataclass
class PrivateLinkResourceConfig:
    provider_name: Any = None

@dataclasses.dataclass
class PrivateLinkResourceAttrs:
    # The link to the next page of items
    next_link: Any = None
    provider_name: Any = None
    # The PrivateLinkResource items on this page
    value: Any = None

PrivateLinkResource = ubx.DataSourceBinding(
    wire_type="azure_attestation_private_link_resource",
    fields={
        "provider_name": ubx.FieldSpec(wire_name="provider_name"),
    },
)
