// Code generated by `ubx sdk gen` from azure_vmware_global_reach_connection. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface GlobalReachConnection_Properties {
  /** The network used for global reach carved out from the original network block provided for the private cloud */
  addressPrefix?: string | Computed<string>;
  /** Authorization key from the peer express route used for the global reach connection */
  authorizationKey?: string | Computed<string>;
  /** Global Reach Connection status */
  circuitConnectionStatus?: string | Computed<string>;
  /** The ID of the Private Cloud's ExpressRoute Circuit that is participating in the global reach connection */
  expressRouteId?: string | Computed<string>;
  /** Identifier of the ExpressRoute Circuit to peer with in the global reach connection */
  peerExpressRouteCircuit?: string | Computed<string>;
  /** Global Reach Connection provisioning state */
  provisioningState?: string | Computed<string>;
}

const GlobalReachConnection_PropertiesFields: FieldMap = {
  addressPrefix: "address_prefix",
  authorizationKey: "authorization_key",
  circuitConnectionStatus: "circuit_connection_status",
  expressRouteId: "express_route_id",
  peerExpressRouteCircuit: "peer_express_route_circuit",
  provisioningState: "provisioning_state",
};

export interface GlobalReachConnectionConfig {
  /** The properties of a global reach connection */
  properties?: GlobalReachConnection_Properties | Computed<GlobalReachConnection_Properties>;
}

export interface GlobalReachConnectionAttrs {
  /** The properties of a global reach connection */
  properties: GlobalReachConnection_Properties;
}

export const GlobalReachConnection: ResourceBinding<GlobalReachConnectionConfig, GlobalReachConnectionAttrs> = {
  wireType: "azure_vmware_global_reach_connection",
  fields: {
    properties: {
      wireName: "properties",
      kind: "object",
      fields: GlobalReachConnection_PropertiesFields,
    },
  },
};
