# Code generated by `ubx sdk gen` from azure@dynamic. DO NOT EDIT.
# This file is committed to git like any other reviewable generated code
# (docs/sdk.md — "ubx sdk gen: local, pinned, offline-after-generation") --
# re-run `ubx sdk gen` to regenerate after a provider version bump.
SOURCE_PROVENANCE = {"source": "azure", "version": "dynamic"}

from .machine import Machine, MachineConfig
from .machine_diagnostic_run_command import MachineDiagnosticRunCommand, MachineDiagnosticRunCommandConfig
from .machine_extension import MachineExtension, MachineExtensionConfig
from .machine_run_command import MachineRunCommand, MachineRunCommandConfig
from .machine_scale_set import MachineScaleSet, MachineScaleSetConfig
from .machine_scale_set_extension import MachineScaleSetExtension, MachineScaleSetExtensionConfig
from .machine_scale_set_vm import MachineScaleSetVm, MachineScaleSetVmConfig
from .machine_scale_set_vmextension import MachineScaleSetVmextension, MachineScaleSetVmextensionConfig
