# Code generated by `ubx sdk gen` from azure_virtual_machine_scale_set_extension. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class MachineScaleSetExtension_Properties_ProtectedSettingsFromKeyVault_SourceVault:
    # Resource Id
    id: Any = None

@dataclasses.dataclass
class MachineScaleSetExtension_Properties_ProtectedSettingsFromKeyVault:
    # The URL referencing a secret in a Key Vault.
    secret_url: Any = None
    source_vault: Any = None

@dataclasses.dataclass
class MachineScaleSetExtension_Properties:
    # Indicates whether the extension should use a newer minor version if one is available at deployment time. Once deployed, however, the extension will not upgrade minor versions unless redeployed, even with this property set to true.
    auto_upgrade_minor_version: Any = None
    # Indicates whether the extension should be automatically upgraded by the platform if there is a newer version of the extension available.
    enable_automatic_upgrade: Any = None
    # If a value is provided and is different from the previous value, the extension handler will be forced to update even if the extension configuration has not changed.
    force_update_tag: Any = None
    # The extension can contain either protectedSettings or protectedSettingsFromKeyVault or no protected settings at all.
    protected_settings: Any = None
    # Describes a reference to Key Vault Secret
    protected_settings_from_key_vault: Any = None
    # Collection of extension names after which this extension needs to be provisioned.
    provision_after_extensions: Any = None
    # The provisioning state, which only appears in the response.
    provisioning_state: Any = None
    # The name of the extension handler publisher.
    publisher: Any = None
    # Json formatted public settings for the extension.
    settings: Any = None
    # Indicates whether failures stemming from the extension will be suppressed (Operational failures such as not connecting to the VM will not be suppressed regardless of this value). The default is false.
    suppress_failures: Any = None
    # Specifies the type of the extension; an example is "CustomScriptExtension".
    type: Any = None
    # Specifies the Major.Minor version of the script handler. Customer is able to specify only the Major.Minor version of an extension, Azure platform will deliver the latest Patch.Hotfix version in the Major.Minor series.
    type_handler_version: Any = None

_MachineScaleSetExtension_Properties_ProtectedSettingsFromKeyVault_SourceVaultFields = {
    "id": ubx.FieldSpec(wire_name="id"),
}

_MachineScaleSetExtension_Properties_ProtectedSettingsFromKeyVaultFields = {
    "secret_url": ubx.FieldSpec(wire_name="secret_url"),
    "source_vault": ubx.FieldSpec(
        wire_name="source_vault",
        kind="object",
        fields=_MachineScaleSetExtension_Properties_ProtectedSettingsFromKeyVault_SourceVaultFields,
    ),
}

_MachineScaleSetExtension_PropertiesFields = {
    "auto_upgrade_minor_version": ubx.FieldSpec(wire_name="auto_upgrade_minor_version"),
    "enable_automatic_upgrade": ubx.FieldSpec(wire_name="enable_automatic_upgrade"),
    "force_update_tag": ubx.FieldSpec(wire_name="force_update_tag"),
    "protected_settings": ubx.FieldSpec(wire_name="protected_settings"),
    "protected_settings_from_key_vault": ubx.FieldSpec(
        wire_name="protected_settings_from_key_vault",
        kind="object",
        fields=_MachineScaleSetExtension_Properties_ProtectedSettingsFromKeyVaultFields,
    ),
    "provision_after_extensions": ubx.FieldSpec(wire_name="provision_after_extensions"),
    "provisioning_state": ubx.FieldSpec(wire_name="provisioning_state"),
    "publisher": ubx.FieldSpec(wire_name="publisher"),
    "settings": ubx.FieldSpec(wire_name="settings"),
    "suppress_failures": ubx.FieldSpec(wire_name="suppress_failures"),
    "type": ubx.FieldSpec(wire_name="type"),
    "type_handler_version": ubx.FieldSpec(wire_name="type_handler_version"),
}

@dataclasses.dataclass
class MachineScaleSetExtensionConfig:
    # Resource name
    name: Any = None
    # Describes the properties of a Virtual Machine Scale Set Extension.
    properties: Any = None

@dataclasses.dataclass
class MachineScaleSetExtensionAttrs:
    # Resource Id
    id: Any = None
    # Resource name
    name: Any = None
    # Describes the properties of a Virtual Machine Scale Set Extension.
    properties: Any = None
    # Resource type
    type: Any = None

MachineScaleSetExtension = ubx.ResourceBinding(
    wire_type="azure_virtual_machine_scale_set_extension",
    fields={
        "name": ubx.FieldSpec(wire_name="name"),
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_MachineScaleSetExtension_PropertiesFields,
        ),
    },
)
