// Code generated by `ubx sdk gen` from azure_resources_privatelinks_private_link_association. DO NOT EDIT.
package resources

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type PrivatelinksPrivateLinkAssociation_Properties struct {
	// The rmpl Resource ID.
	PrivateLink any
	// Whether public network access is enabled for resources covered by this private link association. (AI-inferred)
	PublicNetworkAccess any
	// The scope of the private link association.
	Scope any
	// The TenantID.
	TenantId any
}

var PrivatelinksPrivateLinkAssociation_PropertiesFields = ubx.FieldMap{
	"PrivateLink":         ubx.FieldSpec{WireName: "private_link"},
	"PublicNetworkAccess": ubx.FieldSpec{WireName: "public_network_access"},
	"Scope":               ubx.FieldSpec{WireName: "scope"},
	"TenantId":            ubx.FieldSpec{WireName: "tenant_id"},
}

type PrivatelinksPrivateLinkAssociationConfig struct {
	// The resource type-specific configuration for this resource, wrapping every field that isn't part of ARM's own standard envelope (id/name/type/location/tags). (AI-inferred)
	Properties any
}

type PrivatelinksPrivateLinkAssociationAttrs struct {
	// The plaResourceID.
	Id any
	// The pla name.
	Name any
	// The resource type-specific configuration for this resource, wrapping every field that isn't part of ARM's own standard envelope (id/name/type/location/tags). (AI-inferred)
	Properties any
	// The operation type.
	Type any
}

var PrivatelinksPrivateLinkAssociation = ubx.ResourceBinding{
	WireType: "azure_resources_privatelinks_private_link_association",
	Fields: ubx.FieldMap{
		"Properties": ubx.FieldSpec{
			WireName: "properties",
			Kind:     "object",
			Fields:   PrivatelinksPrivateLinkAssociation_PropertiesFields,
		},
	},
}
