// Code generated by `ubx sdk gen` from azure_cognitiveservices_project. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Project_Value_Identity_UserAssignedIdentities {
  clientId?: string | Computed<string>;
  principalId?: string | Computed<string>;
}

export interface Project_Value_Identity {
  principalId?: string | Computed<string>;
  tenantId?: string | Computed<string>;
  type?: string | Computed<string>;
  userAssignedIdentities?: Record<string, Project_Value_Identity_UserAssignedIdentities> | Computed<Record<string, Project_Value_Identity_UserAssignedIdentities>>;
}

export interface Project_Value_Properties {
  description?: string | Computed<string>;
  displayName?: string | Computed<string>;
  endpoints?: Record<string, string> | Computed<Record<string, string>>;
  isDefault?: boolean | Computed<boolean>;
  provisioningState?: string | Computed<string>;
}

export interface Project_Value {
  etag?: string | Computed<string>;
  identity?: Project_Value_Identity | Computed<Project_Value_Identity>;
  location?: string | Computed<string>;
  properties?: Project_Value_Properties | Computed<Project_Value_Properties>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
}

export interface ProjectConfig {
  accountName: string | Computed<string>;
}

export interface ProjectAttrs {
  accountName: string;
  /** The link used to get the next page of projects. */
  nextLink: string;
  /** Gets the list of Cognitive Services projects and their properties. */
  value: Project_Value[];
}

export const Project: DataSourceBinding<ProjectConfig, ProjectAttrs> = {
  wireType: "azure_cognitiveservices_project",
  fields: {
    accountName: "account_name",
  },
};
