// Code generated by `ubx sdk gen` from azure_storage_openapi_private_endpoint_connection_list. DO NOT EDIT.
package storage

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpenapiPrivateEndpointConnectionList_Value_Properties_PrivateEndpoint struct {
	Id any
}

type OpenapiPrivateEndpointConnectionList_Value_Properties_PrivateLinkServiceConnectionState struct {
	ActionRequired any
	Description any
	Status any
}

type OpenapiPrivateEndpointConnectionList_Value_Properties struct {
	PrivateEndpoint any
	PrivateLinkServiceConnectionState any
	ProvisioningState any
}

type OpenapiPrivateEndpointConnectionList_Value struct {
	Properties any
}

type OpenapiPrivateEndpointConnectionListConfig struct {
	AccountName any
}

type OpenapiPrivateEndpointConnectionListAttrs struct {
	AccountName any
	NextLink any
	// Array of private endpoint connections
	Value any
}

var OpenapiPrivateEndpointConnectionList = ubx.DataSourceBinding{
	WireType: "azure_storage_openapi_private_endpoint_connection_list",
	Fields: ubx.FieldMap{
		"AccountName": ubx.FieldSpec{WireName: "account_name"},
	},
}
