# Code generated by `ubx sdk gen` from azure_securityinsights_openapi_template_model. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OpenapiTemplateModel_Properties_Author:
    # Email of author contact
    email: Any = None
    # Link for author/vendor page
    link: Any = None
    # Name of the author. Company or person.
    name: Any = None

@dataclasses.dataclass
class OpenapiTemplateModel_Properties_Categories:
    # domain for the solution content item
    domains: Any = None
    # Industry verticals for the solution content item
    verticals: Any = None

@dataclasses.dataclass
class OpenapiTemplateModel_Properties_DependantTemplates:
    pass

@dataclasses.dataclass
class OpenapiTemplateModel_Properties_Dependencies:
    # Id of the content item we depend on
    content_id: Any = None
    # This is the list of dependencies we must fulfill, according to the AND/OR operator
    criteria: Any = None
    # The kind of content the metadata is for.
    kind: Any = None
    # Name of the content item
    name: Any = None
    # Operator used for list of dependencies in criteria array.
    operator: Any = None
    # Version of the the content item we depend on. Can be blank, * or missing to indicate any version fulfills the dependency. If version does not match our defined numeric format then an exact match is required.
    version: Any = None

@dataclasses.dataclass
class OpenapiTemplateModel_Properties_Source:
    # Source type of the content
    kind: Any = None
    # Name of the content source. The repo name, solution name, LA workspace name etc.
    name: Any = None
    # ID of the content source. The solution ID, workspace ID, etc
    source_id: Any = None

@dataclasses.dataclass
class OpenapiTemplateModel_Properties_Support:
    # Email of support contact
    email: Any = None
    # Link for support help, like to support page to open a ticket etc.
    link: Any = None
    # Name of the support contact. Company or person.
    name: Any = None
    # Type of support for content item
    tier: Any = None

@dataclasses.dataclass
class OpenapiTemplateModel_Properties:
    # Publisher or creator of the content item.
    author: Any = None
    # ies for the solution content item
    categories: Any = None
    # Static ID for the content. Used to identify dependencies and content from solutions or community. Hard-coded/static for out of the box content and solutions. Dynamic for user-created. This is the resource name
    content_id: Any = None
    # The kind of content the metadata is for.
    content_kind: Any = None
    # Unique ID for the content. It should be generated based on the contentId of the package, contentId of the template, contentKind of the template and the contentVersion of the template
    content_product_id: Any = None
    # Schema version of the content. Can be used to distinguish between different flow based on the schema version
    content_schema_version: Any = None
    # The custom version of the content. A optional free text
    custom_version: Any = None
    # Dependant templates. Expandable.
    dependant_templates: Any = None
    # Dependencies for the content item, what other content items it requires to work. Can describe more complex dependencies using a recursive/nested structure. For a single dependency an id/kind/version can be supplied or operator/criteria for complex dependencies.
    dependencies: Any = None
    # The display name of the template
    display_name: Any = None
    # first publish date content item
    first_publish_date: Any = None
    # the icon identifier. this id can later be fetched from the content metadata
    icon: Any = None
    # The boolean value the metadata is for.
    is_deprecated: Any = None
    # last publish date for the content item
    last_publish_date: Any = None
    # The JSON of the ARM template to deploy active content. Expandable.
    main_template: Any = None
    # the package Id contains this template
    package_id: Any = None
    # The package kind
    package_kind: Any = None
    # the name of the package contains this template
    package_name: Any = None
    # Version of the package. Default and recommended format is numeric (e.g. 1, 1.0, 1.0.0, 1.0.0.0), following ARM metadata best practices. Can also be any string, but then we cannot guarantee any version checks
    package_version: Any = None
    # preview image file names. These will be taken from the solution artifacts
    preview_images: Any = None
    # preview image file names. These will be taken from the solution artifacts. used for dark theme support
    preview_images_dark: Any = None
    # Providers for the content item
    providers: Any = None
    # The original source of the content item, where it comes from.
    source: Any = None
    # Support information for the content item.
    support: Any = None
    # the tactics the resource covers
    threat_analysis_tactics: Any = None
    # the techniques the resource covers, these have to be aligned with the tactics being used
    threat_analysis_techniques: Any = None
    # Version of the content. Default and recommended format is numeric (e.g. 1, 1.0, 1.0.0, 1.0.0.0), following ARM metadata best practices. Can also be any string, but then we cannot guarantee any version checks
    version: Any = None

_OpenapiTemplateModel_Properties_AuthorFields = {
    "email": ubx.FieldSpec(wire_name="email"),
    "link": ubx.FieldSpec(wire_name="link"),
    "name": ubx.FieldSpec(wire_name="name"),
}

_OpenapiTemplateModel_Properties_CategoriesFields = {
    "domains": ubx.FieldSpec(wire_name="domains"),
    "verticals": ubx.FieldSpec(wire_name="verticals"),
}

_OpenapiTemplateModel_Properties_DependantTemplatesFields = {
}

_OpenapiTemplateModel_Properties_DependenciesFields = {
    "content_id": ubx.FieldSpec(wire_name="content_id"),
    "criteria": ubx.FieldSpec(
        wire_name="criteria",
        kind="list",
        fields=_OpenapiTemplateModel_Properties_DependantTemplatesFields,
    ),
    "kind": ubx.FieldSpec(wire_name="kind"),
    "name": ubx.FieldSpec(wire_name="name"),
    "operator": ubx.FieldSpec(wire_name="operator"),
    "version": ubx.FieldSpec(wire_name="version"),
}

_OpenapiTemplateModel_Properties_SourceFields = {
    "kind": ubx.FieldSpec(wire_name="kind"),
    "name": ubx.FieldSpec(wire_name="name"),
    "source_id": ubx.FieldSpec(wire_name="source_id"),
}

_OpenapiTemplateModel_Properties_SupportFields = {
    "email": ubx.FieldSpec(wire_name="email"),
    "link": ubx.FieldSpec(wire_name="link"),
    "name": ubx.FieldSpec(wire_name="name"),
    "tier": ubx.FieldSpec(wire_name="tier"),
}

_OpenapiTemplateModel_PropertiesFields = {
    "author": ubx.FieldSpec(
        wire_name="author",
        kind="object",
        fields=_OpenapiTemplateModel_Properties_AuthorFields,
    ),
    "categories": ubx.FieldSpec(
        wire_name="categories",
        kind="object",
        fields=_OpenapiTemplateModel_Properties_CategoriesFields,
    ),
    "content_id": ubx.FieldSpec(wire_name="content_id"),
    "content_kind": ubx.FieldSpec(wire_name="content_kind"),
    "content_product_id": ubx.FieldSpec(wire_name="content_product_id"),
    "content_schema_version": ubx.FieldSpec(wire_name="content_schema_version"),
    "custom_version": ubx.FieldSpec(wire_name="custom_version"),
    "dependant_templates": ubx.FieldSpec(
        wire_name="dependant_templates",
        kind="list",
        fields=_OpenapiTemplateModel_Properties_DependantTemplatesFields,
    ),
    "dependencies": ubx.FieldSpec(
        wire_name="dependencies",
        kind="object",
        fields=_OpenapiTemplateModel_Properties_DependenciesFields,
    ),
    "display_name": ubx.FieldSpec(wire_name="display_name"),
    "first_publish_date": ubx.FieldSpec(wire_name="first_publish_date"),
    "icon": ubx.FieldSpec(wire_name="icon"),
    "is_deprecated": ubx.FieldSpec(wire_name="is_deprecated"),
    "last_publish_date": ubx.FieldSpec(wire_name="last_publish_date"),
    "main_template": ubx.FieldSpec(wire_name="main_template"),
    "package_id": ubx.FieldSpec(wire_name="package_id"),
    "package_kind": ubx.FieldSpec(wire_name="package_kind"),
    "package_name": ubx.FieldSpec(wire_name="package_name"),
    "package_version": ubx.FieldSpec(wire_name="package_version"),
    "preview_images": ubx.FieldSpec(wire_name="preview_images"),
    "preview_images_dark": ubx.FieldSpec(wire_name="preview_images_dark"),
    "providers": ubx.FieldSpec(wire_name="providers"),
    "source": ubx.FieldSpec(
        wire_name="source",
        kind="object",
        fields=_OpenapiTemplateModel_Properties_SourceFields,
    ),
    "support": ubx.FieldSpec(
        wire_name="support",
        kind="object",
        fields=_OpenapiTemplateModel_Properties_SupportFields,
    ),
    "threat_analysis_tactics": ubx.FieldSpec(wire_name="threat_analysis_tactics"),
    "threat_analysis_techniques": ubx.FieldSpec(wire_name="threat_analysis_techniques"),
    "version": ubx.FieldSpec(wire_name="version"),
}

@dataclasses.dataclass
class OpenapiTemplateModelConfig:
    # Etag of the azure resource
    etag: Any = None
    # Template property bag.
    properties: Any = None

@dataclasses.dataclass
class OpenapiTemplateModelAttrs:
    # Etag of the azure resource
    etag: Any = None
    # Template property bag.
    properties: Any = None

OpenapiTemplateModel = ubx.ResourceBinding(
    wire_type="azure_securityinsights_openapi_template_model",
    fields={
        "etag": ubx.FieldSpec(wire_name="etag"),
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_OpenapiTemplateModel_PropertiesFields,
        ),
    },
)
