// Code generated by `ubx sdk gen` from azurerm_healthcare_dicom_service. DO NOT EDIT.
package healthcare

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type DicomService_Cors struct {
	AllowCredentials any
	AllowedHeaders any
	AllowedMethods any
	AllowedOrigins any
	MaxAgeInSeconds any
}

type DicomService_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type DicomService_Storage struct {
	FileSystemName any
	StorageAccountId any
}

type DicomService_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var DicomService_CorsFields = ubx.FieldMap{
		"AllowCredentials": ubx.FieldSpec{WireName: "allow_credentials"},
		"AllowedHeaders": ubx.FieldSpec{WireName: "allowed_headers"},
		"AllowedMethods": ubx.FieldSpec{WireName: "allowed_methods"},
		"AllowedOrigins": ubx.FieldSpec{WireName: "allowed_origins"},
		"MaxAgeInSeconds": ubx.FieldSpec{WireName: "max_age_in_seconds"},
	}

var DicomService_IdentityFields = ubx.FieldMap{
		"IdentityIds": ubx.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": ubx.FieldSpec{WireName: "principal_id"},
		"TenantId": ubx.FieldSpec{WireName: "tenant_id"},
		"Type": ubx.FieldSpec{WireName: "type"},
	}

var DicomService_StorageFields = ubx.FieldMap{
		"FileSystemName": ubx.FieldSpec{WireName: "file_system_name"},
		"StorageAccountId": ubx.FieldSpec{WireName: "storage_account_id"},
	}

var DicomService_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Read": ubx.FieldSpec{WireName: "read"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

type DicomServiceConfig struct {
	DataPartitionsEnabled any
	EncryptionKeyUrl any
	Id any
	Location any
	Name any
	PublicNetworkAccessEnabled any
	Tags any
	WorkspaceId any
	Cors any
	Identity any
	Storage any
	Timeouts any
}

var DicomService = ubx.ResourceBinding{
	WireType: "azurerm_healthcare_dicom_service",
	Fields: ubx.FieldMap{
		"DataPartitionsEnabled": ubx.FieldSpec{WireName: "data_partitions_enabled"},
		"EncryptionKeyUrl": ubx.FieldSpec{WireName: "encryption_key_url"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"Location": ubx.FieldSpec{WireName: "location"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"PublicNetworkAccessEnabled": ubx.FieldSpec{WireName: "public_network_access_enabled"},
		"Tags": ubx.FieldSpec{WireName: "tags"},
		"WorkspaceId": ubx.FieldSpec{WireName: "workspace_id"},
		"Cors": ubx.FieldSpec{
			WireName: "cors",
			Kind: "list",
			Fields: DicomService_CorsFields,
		},
		"Identity": ubx.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: DicomService_IdentityFields,
		},
		"Storage": ubx.FieldSpec{
			WireName: "storage",
			Kind: "list",
			Fields: DicomService_StorageFields,
		},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: DicomService_TimeoutsFields,
		},
	},
}
