# Code generated by `ubx sdk gen` from azure_web_openapi_kube_environment. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OpenapiKubeEnvironment_ExtendedLocation:
    # Name of extended location.
    name: Any = None
    # Type of extended location.
    type: Any = None

@dataclasses.dataclass
class OpenapiKubeEnvironment_Properties_AppLogsConfiguration_LogAnalyticsConfiguration:
    customer_id: Any = None
    shared_key: Any = None

@dataclasses.dataclass
class OpenapiKubeEnvironment_Properties_AppLogsConfiguration:
    destination: Any = None
    log_analytics_configuration: Any = None

@dataclasses.dataclass
class OpenapiKubeEnvironment_Properties_ArcConfiguration_FrontEndServiceConfiguration:
    kind: Any = None

@dataclasses.dataclass
class OpenapiKubeEnvironment_Properties_ArcConfiguration:
    artifact_storage_access_mode: Any = None
    artifact_storage_class_name: Any = None
    artifact_storage_mount_path: Any = None
    artifact_storage_node_name: Any = None
    artifacts_storage_type: Any = None
    front_end_service_configuration: Any = None
    kube_config: Any = None

@dataclasses.dataclass
class OpenapiKubeEnvironment_Properties_ContainerAppsConfiguration:
    # Resource ID of a subnet for control plane infrastructure components. This subnet must be in the same VNET as the subnet defined in appSubnetResourceId. Must not overlap with the IP range defined in platformReservedCidr, if defined.
    app_subnet_resource_id: Any = None
    # Resource ID of a subnet for control plane infrastructure components. This subnet must be in the same VNET as the subnet defined in appSubnetResourceId. Must not overlap with the IP range defined in platformReservedCidr, if defined.
    control_plane_subnet_resource_id: Any = None
    # Azure Monitor instrumentation key used by Dapr to export Service to Service communication telemetry
    dapr_aiinstrumentation_key: Any = None
    # CIDR notation IP range assigned to the Docker bridge network. It must not overlap with any Subnet IP ranges or the IP range defined in platformReservedCidr, if defined.
    docker_bridge_cidr: Any = None
    # IP range in CIDR notation that can be reserved for environment infrastructure IP addresses. It must not overlap with any other Subnet IP ranges.
    platform_reserved_cidr: Any = None
    # An IP address from the IP range defined by platformReservedCidr that will be reserved for the internal DNS server
    platform_reserved_dns_ip: Any = None

@dataclasses.dataclass
class OpenapiKubeEnvironment_Properties:
    aks_resource_id: Any = None
    app_logs_configuration: Any = None
    arc_configuration: Any = None
    container_apps_configuration: Any = None
    # Default Domain Name for the cluster
    default_domain: Any = None
    # Any errors that occurred during deployment or deployment validation
    deployment_errors: Any = None
    # Type of Kubernetes Environment. Only supported for Container App Environments with value as Managed
    environment_type: Any = None
    # Only visible within Vnet/Subnet
    internal_load_balancer_enabled: Any = None
    # Provisioning state of the Kubernetes Environment.
    provisioning_state: Any = None
    # Static IP of the KubeEnvironment
    static_ip: Any = None

_OpenapiKubeEnvironment_ExtendedLocationFields = {
    "name": ubx.FieldSpec(wire_name="name"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_OpenapiKubeEnvironment_Properties_AppLogsConfiguration_LogAnalyticsConfigurationFields = {
    "customer_id": ubx.FieldSpec(wire_name="customer_id"),
    "shared_key": ubx.FieldSpec(wire_name="shared_key"),
}

_OpenapiKubeEnvironment_Properties_AppLogsConfigurationFields = {
    "destination": ubx.FieldSpec(wire_name="destination"),
    "log_analytics_configuration": ubx.FieldSpec(
        wire_name="log_analytics_configuration",
        kind="object",
        fields=_OpenapiKubeEnvironment_Properties_AppLogsConfiguration_LogAnalyticsConfigurationFields,
    ),
}

_OpenapiKubeEnvironment_Properties_ArcConfiguration_FrontEndServiceConfigurationFields = {
    "kind": ubx.FieldSpec(wire_name="kind"),
}

_OpenapiKubeEnvironment_Properties_ArcConfigurationFields = {
    "artifact_storage_access_mode": ubx.FieldSpec(wire_name="artifact_storage_access_mode"),
    "artifact_storage_class_name": ubx.FieldSpec(wire_name="artifact_storage_class_name"),
    "artifact_storage_mount_path": ubx.FieldSpec(wire_name="artifact_storage_mount_path"),
    "artifact_storage_node_name": ubx.FieldSpec(wire_name="artifact_storage_node_name"),
    "artifacts_storage_type": ubx.FieldSpec(wire_name="artifacts_storage_type"),
    "front_end_service_configuration": ubx.FieldSpec(
        wire_name="front_end_service_configuration",
        kind="object",
        fields=_OpenapiKubeEnvironment_Properties_ArcConfiguration_FrontEndServiceConfigurationFields,
    ),
    "kube_config": ubx.FieldSpec(wire_name="kube_config"),
}

_OpenapiKubeEnvironment_Properties_ContainerAppsConfigurationFields = {
    "app_subnet_resource_id": ubx.FieldSpec(wire_name="app_subnet_resource_id"),
    "control_plane_subnet_resource_id": ubx.FieldSpec(wire_name="control_plane_subnet_resource_id"),
    "dapr_aiinstrumentation_key": ubx.FieldSpec(wire_name="dapr_aiinstrumentation_key"),
    "docker_bridge_cidr": ubx.FieldSpec(wire_name="docker_bridge_cidr"),
    "platform_reserved_cidr": ubx.FieldSpec(wire_name="platform_reserved_cidr"),
    "platform_reserved_dns_ip": ubx.FieldSpec(wire_name="platform_reserved_dns_ip"),
}

_OpenapiKubeEnvironment_PropertiesFields = {
    "aks_resource_id": ubx.FieldSpec(wire_name="aks_resource_id"),
    "app_logs_configuration": ubx.FieldSpec(
        wire_name="app_logs_configuration",
        kind="object",
        fields=_OpenapiKubeEnvironment_Properties_AppLogsConfigurationFields,
    ),
    "arc_configuration": ubx.FieldSpec(
        wire_name="arc_configuration",
        kind="object",
        fields=_OpenapiKubeEnvironment_Properties_ArcConfigurationFields,
    ),
    "container_apps_configuration": ubx.FieldSpec(
        wire_name="container_apps_configuration",
        kind="object",
        fields=_OpenapiKubeEnvironment_Properties_ContainerAppsConfigurationFields,
    ),
    "default_domain": ubx.FieldSpec(wire_name="default_domain"),
    "deployment_errors": ubx.FieldSpec(wire_name="deployment_errors"),
    "environment_type": ubx.FieldSpec(wire_name="environment_type"),
    "internal_load_balancer_enabled": ubx.FieldSpec(wire_name="internal_load_balancer_enabled"),
    "provisioning_state": ubx.FieldSpec(wire_name="provisioning_state"),
    "static_ip": ubx.FieldSpec(wire_name="static_ip"),
}

@dataclasses.dataclass
class OpenapiKubeEnvironmentConfig:
    # Extended Location.
    extended_location: Any = None
    # Kind of resource.
    kind: Any = None
    # The geo-location where the resource lives
    location: Any = None
    # KubeEnvironment resource specific properties
    properties: Any = None
    # Resource tags.
    tags: Any = None
    # path parameter, not part of the API's own resource representation
    name: Any = None

@dataclasses.dataclass
class OpenapiKubeEnvironmentAttrs:
    # Extended Location.
    extended_location: Any = None
    # Kind of resource.
    kind: Any = None
    # The geo-location where the resource lives
    location: Any = None
    # KubeEnvironment resource specific properties
    properties: Any = None
    # Resource tags.
    tags: Any = None
    # path parameter, not part of the API's own resource representation
    name: Any = None

OpenapiKubeEnvironment = ubx.ResourceBinding(
    wire_type="azure_web_openapi_kube_environment",
    fields={
        "extended_location": ubx.FieldSpec(
            wire_name="extended_location",
            kind="object",
            fields=_OpenapiKubeEnvironment_ExtendedLocationFields,
        ),
        "kind": ubx.FieldSpec(wire_name="kind"),
        "location": ubx.FieldSpec(wire_name="location"),
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_OpenapiKubeEnvironment_PropertiesFields,
        ),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "name": ubx.FieldSpec(wire_name="name"),
    },
)
