// Code generated by `ubx sdk gen` from azure_oracle_openapi_db_system_shape_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface OpenapiDbSystemShapeList_Value_Properties {
  areServerTypesSupported?: boolean | Computed<boolean>;
  availableCoreCount?: number | Computed<number>;
  availableCoreCountPerNode?: number | Computed<number>;
  availableDataStorageInTbs?: number | Computed<number>;
  availableDataStoragePerServerInTbs?: number | Computed<number>;
  availableDbNodePerNodeInGbs?: number | Computed<number>;
  availableDbNodeStorageInGbs?: number | Computed<number>;
  availableMemoryInGbs?: number | Computed<number>;
  availableMemoryPerNodeInGbs?: number | Computed<number>;
  computeModel?: string | Computed<string>;
  coreCountIncrement?: number | Computed<number>;
  displayName?: string | Computed<string>;
  maxStorageCount?: number | Computed<number>;
  maximumNodeCount?: number | Computed<number>;
  minCoreCountPerNode?: number | Computed<number>;
  minDataStorageInTbs?: number | Computed<number>;
  minDbNodeStoragePerNodeInGbs?: number | Computed<number>;
  minMemoryPerNodeInGbs?: number | Computed<number>;
  minStorageCount?: number | Computed<number>;
  minimumCoreCount?: number | Computed<number>;
  minimumNodeCount?: number | Computed<number>;
  runtimeMinimumCoreCount?: number | Computed<number>;
  shapeAttributes?: string[] | Computed<string[]>;
  shapeFamily?: string | Computed<string>;
  shapeName?: string | Computed<string>;
}

export interface OpenapiDbSystemShapeList_Value {
  properties?: OpenapiDbSystemShapeList_Value_Properties | Computed<OpenapiDbSystemShapeList_Value_Properties>;
}

export interface OpenapiDbSystemShapeListConfig {
  shapeAttribute?: string | Computed<string>;
  zone?: string | Computed<string>;
}

export interface OpenapiDbSystemShapeListAttrs {
  /** The link to the next page of items */
  nextLink: string;
  shapeAttribute: string;
  /** The DbSystemShape items on this page */
  value: OpenapiDbSystemShapeList_Value[];
  zone: string;
}

export const OpenapiDbSystemShapeList: DataSourceBinding<OpenapiDbSystemShapeListConfig, OpenapiDbSystemShapeListAttrs> = {
  wireType: "azure_oracle_openapi_db_system_shape_list",
  fields: {
    shapeAttribute: "shape_attribute",
    zone: "zone",
  },
};
