// Code generated by `ubx sdk gen` from azure_machinelearningservices_openapi_environment_container. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface OpenapiEnvironmentContainer_Value_Properties {
  provisioningState?: string | Computed<string>;
}

export interface OpenapiEnvironmentContainer_Value {
  properties?: OpenapiEnvironmentContainer_Value_Properties | Computed<OpenapiEnvironmentContainer_Value_Properties>;
}

export interface OpenapiEnvironmentContainerConfig {
  listViewType?: string | Computed<string>;
  registryName: string | Computed<string>;
}

export interface OpenapiEnvironmentContainerAttrs {
  listViewType: string;
  /** The link to the next page of items */
  nextLink: string;
  registryName: string;
  /** The EnvironmentContainer items on this page */
  value: OpenapiEnvironmentContainer_Value[];
}

export const OpenapiEnvironmentContainer: DataSourceBinding<OpenapiEnvironmentContainerConfig, OpenapiEnvironmentContainerAttrs> = {
  wireType: "azure_machinelearningservices_openapi_environment_container",
  fields: {
    listViewType: "list_view_type",
    registryName: "registry_name",
  },
};
