# Code generated by `ubx sdk gen` from azure_elastic_open_aiintegration_rpmodel. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OpenAiintegrationRpmodel_Value_Properties:
    key: Any = None
    last_refresh_at: Any = None
    open_aiconnector_id: Any = None
    open_airesource_endpoint: Any = None
    open_airesource_id: Any = None

@dataclasses.dataclass
class OpenAiintegrationRpmodel_Value:
    properties: Any = None

@dataclasses.dataclass
class OpenAiintegrationRpmodelConfig:
    monitor_name: Any = None

@dataclasses.dataclass
class OpenAiintegrationRpmodelAttrs:
    monitor_name: Any = None
    # The link to the next page of items
    next_link: Any = None
    # The OpenAIIntegrationRPModel items on this page
    value: Any = None

OpenAiintegrationRpmodel = ubx.DataSourceBinding(
    wire_type="azure_elastic_open_aiintegration_rpmodel",
    fields={
        "monitor_name": ubx.FieldSpec(wire_name="monitor_name"),
    },
)
