// Code generated by `ubx sdk gen` from azure_servicefabric_cluster_list. DO NOT EDIT.
package servicefabric

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ClusterList_Value_Properties_ApplicationTypeVersionsCleanupPolicy struct {
	MaxUnusedVersionsToKeep any
}

type ClusterList_Value_Properties_AvailableClusterVersions struct {
	CodeVersion any
	Environment any
	SupportExpiryUtc any
}

type ClusterList_Value_Properties_AzureActiveDirectory struct {
	ClientApplication any
	ClusterApplication any
	TenantId any
}

type ClusterList_Value_Properties_Certificate struct {
	Thumbprint any
	ThumbprintSecondary any
	X509StoreName any
}

type ClusterList_Value_Properties_CertificateCommonNames_CommonNames struct {
	CertificateCommonName any
	CertificateIssuerThumbprint any
}

type ClusterList_Value_Properties_CertificateCommonNames struct {
	CommonNames any
	X509StoreName any
}

type ClusterList_Value_Properties_ClientCertificateCommonNames struct {
	CertificateCommonName any
	CertificateIssuerThumbprint any
	IsAdmin any
}

type ClusterList_Value_Properties_ClientCertificateThumbprints struct {
	CertificateThumbprint any
	IsAdmin any
}

type ClusterList_Value_Properties_DiagnosticsStorageAccountConfig struct {
	BlobEndpoint any
	ProtectedAccountKeyName any
	ProtectedAccountKeyName2 any
	QueueEndpoint any
	StorageAccountName any
	TableEndpoint any
}

type ClusterList_Value_Properties_FabricSettings_Parameters struct {
	Name any
	Value any
}

type ClusterList_Value_Properties_FabricSettings struct {
	Name any
	Parameters any
}

type ClusterList_Value_Properties_NodeTypes_ApplicationPorts struct {
	EndPort any
	StartPort any
}

type ClusterList_Value_Properties_NodeTypes struct {
	ApplicationPorts any
	Capacities any
	ClientConnectionEndpointPort any
	DurabilityLevel any
	EphemeralPorts any
	HttpGatewayEndpointPort any
	IsPrimary any
	IsStateless any
	MultipleAvailabilityZones any
	Name any
	PlacementProperties any
	ReverseProxyEndpointPort any
	VmInstanceCount any
}

type ClusterList_Value_Properties_Notifications_NotificationTargets struct {
	NotificationChannel any
	Receivers any
}

type ClusterList_Value_Properties_Notifications struct {
	IsEnabled any
	NotificationCategory any
	NotificationLevel any
	NotificationTargets any
}

type ClusterList_Value_Properties_UpgradeDescription_DeltaHealthPolicy_ApplicationDeltaHealthPolicies_DefaultServiceTypeDeltaHealthPolicy struct {
	MaxPercentDeltaUnhealthyServices any
}

type ClusterList_Value_Properties_UpgradeDescription_DeltaHealthPolicy_ApplicationDeltaHealthPolicies struct {
	DefaultServiceTypeDeltaHealthPolicy any
	ServiceTypeDeltaHealthPolicies any
}

type ClusterList_Value_Properties_UpgradeDescription_DeltaHealthPolicy struct {
	ApplicationDeltaHealthPolicies any
	MaxPercentDeltaUnhealthyApplications any
	MaxPercentDeltaUnhealthyNodes any
	MaxPercentUpgradeDomainDeltaUnhealthyNodes any
}

type ClusterList_Value_Properties_UpgradeDescription_HealthPolicy_ApplicationHealthPolicies_DefaultServiceTypeHealthPolicy struct {
	MaxPercentUnhealthyServices any
}

type ClusterList_Value_Properties_UpgradeDescription_HealthPolicy_ApplicationHealthPolicies struct {
	DefaultServiceTypeHealthPolicy any
	ServiceTypeHealthPolicies any
}

type ClusterList_Value_Properties_UpgradeDescription_HealthPolicy struct {
	ApplicationHealthPolicies any
	MaxPercentUnhealthyApplications any
	MaxPercentUnhealthyNodes any
}

type ClusterList_Value_Properties_UpgradeDescription struct {
	DeltaHealthPolicy any
	ForceRestart any
	HealthCheckRetryTimeout any
	HealthCheckStableDuration any
	HealthCheckWaitDuration any
	HealthPolicy any
	UpgradeDomainTimeout any
	UpgradeReplicaSetCheckTimeout any
	UpgradeTimeout any
}

type ClusterList_Value_Properties struct {
	AddOnFeatures any
	ApplicationTypeVersionsCleanupPolicy any
	AvailableClusterVersions any
	AzureActiveDirectory any
	Certificate any
	CertificateCommonNames any
	ClientCertificateCommonNames any
	ClientCertificateThumbprints any
	ClusterCodeVersion any
	ClusterEndpoint any
	ClusterId any
	ClusterState any
	DiagnosticsStorageAccountConfig any
	EventStoreServiceEnabled any
	FabricSettings any
	InfrastructureServiceManager any
	ManagementEndpoint any
	NodeTypes any
	Notifications any
	ProvisioningState any
	ReliabilityLevel any
	ReverseProxyCertificate any
	ReverseProxyCertificateCommonNames any
	SfZonalUpgradeMode any
	UpgradeDescription any
	UpgradeMode any
	UpgradePauseEndTimestampUtc any
	UpgradePauseStartTimestampUtc any
	UpgradeWave any
	VmImage any
	VmssZonalUpgradeMode any
	WaveUpgradePaused any
}

type ClusterList_Value struct {
	Properties any
}

type ClusterListConfig struct {
	ApiVersion any
	SubscriptionId any
}

type ClusterListAttrs struct {
	ApiVersion any
	// The URL to use for getting the next set of results.
	NextLink any
	SubscriptionId any
	Value any
}

var ClusterList = ubx.DataSourceBinding{
	WireType: "azure_servicefabric_cluster_list",
	Fields: ubx.FieldMap{
		"ApiVersion": ubx.FieldSpec{WireName: "api_version"},
		"SubscriptionId": ubx.FieldSpec{WireName: "subscription_id"},
	},
}
