// Code generated by `ubx sdk gen` from azure_dataprotection_backup_instance_resource. DO NOT EDIT.
package dataprotection

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type BackupInstanceResource_Value_Properties_DataSourceInfo_ResourceProperties struct {
	ObjectType any
}

type BackupInstanceResource_Value_Properties_DataSourceInfo struct {
	DatasourceType     any
	ObjectType         any
	ResourceId         any
	ResourceLocation   any
	ResourceName       any
	ResourceProperties any
	ResourceType       any
	ResourceUri        any
}

type BackupInstanceResource_Value_Properties_IdentityDetails struct {
	UseSystemAssignedIdentity  any
	UserAssignedIdentityArmUrl any
}

type BackupInstanceResource_Value_Properties_PolicyInfo_PolicyParameters_DataStoreParametersList struct {
	DataStoreType any
	ObjectType    any
}

type BackupInstanceResource_Value_Properties_PolicyInfo_PolicyParameters struct {
	BackupDatasourceParametersList any
	DataStoreParametersList        any
}

type BackupInstanceResource_Value_Properties_PolicyInfo struct {
	PolicyId         any
	PolicyParameters any
	PolicyVersion    any
}

type BackupInstanceResource_Value_Properties_ProtectionErrorDetails_Details struct {
}

type BackupInstanceResource_Value_Properties_ProtectionErrorDetails_InnerError struct {
	AdditionalInfo     any
	Code               any
	EmbeddedInnerError any
}

type BackupInstanceResource_Value_Properties_ProtectionErrorDetails struct {
	Code              any
	Details           any
	InnerError        any
	IsRetryable       any
	IsUserError       any
	Message           any
	Properties        any
	RecommendedAction any
	Target            any
}

type BackupInstanceResource_Value_Properties_ProtectionStatus struct {
	ErrorDetails any
	Status       any
}

type BackupInstanceResource_Value_Properties struct {
	CurrentProtectionState         any
	DataSourceInfo                 any
	DataSourceSetInfo              any
	DatasourceAuthCredentials      any
	FriendlyName                   any
	IdentityDetails                any
	ObjectType                     any
	PolicyInfo                     any
	ProtectionErrorDetails         any
	ProtectionStatus               any
	ProvisioningState              any
	ResourceGuardOperationRequests any
	ValidationType                 any
}

type BackupInstanceResource_Value struct {
	Properties any
	Tags       any
}

type BackupInstanceResourceConfig struct {
	VaultName any
}

type BackupInstanceResourceAttrs struct {
	// The uri to fetch the next page of resources. Call ListNext() fetches next page of resources.
	NextLink any
	// List of resources.
	Value     any
	VaultName any
}

var BackupInstanceResource = ubx.DataSourceBinding{
	WireType: "azure_dataprotection_backup_instance_resource",
	Fields: ubx.FieldMap{
		"VaultName": ubx.FieldSpec{WireName: "vault_name"},
	},
}
