# Code generated by `ubx sdk gen` from azure_powerbidedicated_openapi_dedicated_capacity. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OpenapiDedicatedCapacity_Properties:
    # The current deployment state of PowerBI Dedicated resource. The provisioningState is to indicate states for resource provisioning.
    provisioning_state: Any = None
    # The current state of PowerBI Dedicated resource. The state is to indicate more states outside of resource provisioning.
    state: Any = None

@dataclasses.dataclass
class OpenapiDedicatedCapacity_Sku:
    # The capacity of the SKU.
    capacity: Any = None
    # Name of the SKU level.
    name: Any = None
    # The name of the Azure pricing tier to which the SKU applies.
    tier: Any = None

_OpenapiDedicatedCapacity_PropertiesFields = {
    "provisioning_state": ubx.FieldSpec(wire_name="provisioning_state"),
    "state": ubx.FieldSpec(wire_name="state"),
}

_OpenapiDedicatedCapacity_SkuFields = {
    "capacity": ubx.FieldSpec(wire_name="capacity"),
    "name": ubx.FieldSpec(wire_name="name"),
    "tier": ubx.FieldSpec(wire_name="tier"),
}

@dataclasses.dataclass
class OpenapiDedicatedCapacityConfig:
    # The geo-location where the resource lives
    location: Any = None
    # Properties of Dedicated Capacity resource.
    properties: Any = None
    # Represents the SKU name and Azure pricing tier for PowerBI Dedicated capacity resource.
    sku: Any = None
    # Resource tags.
    tags: Any = None

@dataclasses.dataclass
class OpenapiDedicatedCapacityAttrs:
    # The geo-location where the resource lives
    location: Any = None
    # Properties of Dedicated Capacity resource.
    properties: Any = None
    # Represents the SKU name and Azure pricing tier for PowerBI Dedicated capacity resource.
    sku: Any = None
    # Resource tags.
    tags: Any = None

OpenapiDedicatedCapacity = ubx.ResourceBinding(
    wire_type="azure_powerbidedicated_openapi_dedicated_capacity",
    fields={
        "location": ubx.FieldSpec(wire_name="location"),
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_OpenapiDedicatedCapacity_PropertiesFields,
        ),
        "sku": ubx.FieldSpec(
            wire_name="sku",
            kind="object",
            fields=_OpenapiDedicatedCapacity_SkuFields,
        ),
        "tags": ubx.FieldSpec(wire_name="tags"),
    },
)
