// Code generated by `ubx sdk gen` from azure_web_openapi_custom_dns_suffix_configuration. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface OpenapiCustomDnsSuffixConfiguration_Properties {
  /** The URL referencing the Azure Key Vault certificate secret that should be used as the default SSL/TLS certificate for sites with the custom domain suffix. */
  certificateUrl?: string | Computed<string>;
  /** The default custom domain suffix to use for all sites deployed on the ASE. */
  dnsSuffix?: string | Computed<string>;
  /** The user-assigned identity to use for resolving the key vault certificate reference. If not specified, the system-assigned ASE identity will be used if available. */
  keyVaultReferenceIdentity?: string | Computed<string>;
  provisioningDetails?: string | Computed<string>;
  provisioningState?: string | Computed<string>;
}

export interface OpenapiCustomDnsSuffixConfigurationConfig {
  name: string | Computed<string>;
}

export interface OpenapiCustomDnsSuffixConfigurationAttrs {
  /** Kind of resource. */
  kind: string;
  name: string;
  /** CustomDnsSuffixConfiguration resource specific properties */
  properties: OpenapiCustomDnsSuffixConfiguration_Properties;
}

export const OpenapiCustomDnsSuffixConfiguration: DataSourceBinding<OpenapiCustomDnsSuffixConfigurationConfig, OpenapiCustomDnsSuffixConfigurationAttrs> = {
  wireType: "azure_web_openapi_custom_dns_suffix_configuration",
  fields: {
    name: "name",
  },
};
