// Code generated by `ubx sdk gen` from azure_web_openapi_site_extension_info_collection. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface OpenapiSiteExtensionInfoCollection_Value_Properties {
  authors?: string[] | Computed<string[]>;
  comment?: string | Computed<string>;
  description?: string | Computed<string>;
  downloadCount?: number | Computed<number>;
  extensionId?: string | Computed<string>;
  extensionType?: string | Computed<string>;
  extensionUrl?: string | Computed<string>;
  feedUrl?: string | Computed<string>;
  iconUrl?: string | Computed<string>;
  installedDateTime?: string | Computed<string>;
  installerCommandLineParams?: string | Computed<string>;
  licenseUrl?: string | Computed<string>;
  localIsLatestVersion?: boolean | Computed<boolean>;
  localPath?: string | Computed<string>;
  projectUrl?: string | Computed<string>;
  provisioningState?: string | Computed<string>;
  publishedDateTime?: string | Computed<string>;
  summary?: string | Computed<string>;
  title?: string | Computed<string>;
  version?: string | Computed<string>;
}

export interface OpenapiSiteExtensionInfoCollection_Value {
  kind?: string | Computed<string>;
  properties?: OpenapiSiteExtensionInfoCollection_Value_Properties | Computed<OpenapiSiteExtensionInfoCollection_Value_Properties>;
}

export interface OpenapiSiteExtensionInfoCollectionConfig {
  name: string | Computed<string>;
}

export interface OpenapiSiteExtensionInfoCollectionAttrs {
  name: string;
  /** The link to the next page of items */
  nextLink: string;
  /** The SiteExtensionInfo items on this page */
  value: OpenapiSiteExtensionInfoCollection_Value[];
}

export const OpenapiSiteExtensionInfoCollection: DataSourceBinding<OpenapiSiteExtensionInfoCollectionConfig, OpenapiSiteExtensionInfoCollectionAttrs> = {
  wireType: "azure_web_openapi_site_extension_info_collection",
  fields: {
    name: "name",
  },
};
