// Code generated by `ubx sdk gen` from azure_web_openapi_triggered_web_job. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface OpenapiTriggeredWebJob_Value_Properties_LatestRun {
  duration?: string | Computed<string>;
  endTime?: string | Computed<string>;
  errorUrl?: string | Computed<string>;
  jobName?: string | Computed<string>;
  outputUrl?: string | Computed<string>;
  startTime?: string | Computed<string>;
  status?: string | Computed<string>;
  trigger?: string | Computed<string>;
  url?: string | Computed<string>;
  webJobId?: string | Computed<string>;
  webJobName?: string | Computed<string>;
}

export interface OpenapiTriggeredWebJob_Value_Properties {
  error?: string | Computed<string>;
  extraInfoUrl?: string | Computed<string>;
  historyUrl?: string | Computed<string>;
  latestRun?: OpenapiTriggeredWebJob_Value_Properties_LatestRun | Computed<OpenapiTriggeredWebJob_Value_Properties_LatestRun>;
  publicNetworkAccess?: string | Computed<string>;
  runCommand?: string | Computed<string>;
  schedulerLogsUrl?: string | Computed<string>;
  settings?: Record<string, unknown> | Computed<Record<string, unknown>>;
  storageAccountRequired?: boolean | Computed<boolean>;
  url?: string | Computed<string>;
  usingSdk?: boolean | Computed<boolean>;
  webJobType?: string | Computed<string>;
}

export interface OpenapiTriggeredWebJob_Value {
  kind?: string | Computed<string>;
  properties?: OpenapiTriggeredWebJob_Value_Properties | Computed<OpenapiTriggeredWebJob_Value_Properties>;
}

export interface OpenapiTriggeredWebJobConfig {
  name: string | Computed<string>;
  slot: string | Computed<string>;
}

export interface OpenapiTriggeredWebJobAttrs {
  name: string;
  /** The link to the next page of items */
  nextLink: string;
  slot: string;
  /** The TriggeredWebJob items on this page */
  value: OpenapiTriggeredWebJob_Value[];
}

export const OpenapiTriggeredWebJob: DataSourceBinding<OpenapiTriggeredWebJobConfig, OpenapiTriggeredWebJobAttrs> = {
  wireType: "azure_web_openapi_triggered_web_job",
  fields: {
    name: "name",
    slot: "slot",
  },
};
