// Code generated by `ubx sdk gen` from azure_web_openapi_static_site_build_armresource. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface OpenapiStaticSiteBuildArmresource_Properties_DatabaseConnections_ConfigurationFiles {
  contents?: string | Computed<string>;
  fileName?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface OpenapiStaticSiteBuildArmresource_Properties_DatabaseConnections {
  configurationFiles?: OpenapiStaticSiteBuildArmresource_Properties_DatabaseConnections_ConfigurationFiles[] | Computed<OpenapiStaticSiteBuildArmresource_Properties_DatabaseConnections_ConfigurationFiles[]>;
  connectionIdentity?: string | Computed<string>;
  name?: string | Computed<string>;
  region?: string | Computed<string>;
  resourceId?: string | Computed<string>;
}

export interface OpenapiStaticSiteBuildArmresource_Properties_LinkedBackends {
  backendResourceId?: string | Computed<string>;
  createdOn?: string | Computed<string>;
  provisioningState?: string | Computed<string>;
  region?: string | Computed<string>;
}

export interface OpenapiStaticSiteBuildArmresource_Properties_UserProvidedFunctionApps_Properties {
  createdOn?: string | Computed<string>;
  functionAppRegion?: string | Computed<string>;
  functionAppResourceId?: string | Computed<string>;
}

export interface OpenapiStaticSiteBuildArmresource_Properties_UserProvidedFunctionApps {
  properties?: OpenapiStaticSiteBuildArmresource_Properties_UserProvidedFunctionApps_Properties | Computed<OpenapiStaticSiteBuildArmresource_Properties_UserProvidedFunctionApps_Properties>;
}

export interface OpenapiStaticSiteBuildArmresource_Properties {
  /** An identifier for the static site build. */
  buildId?: string | Computed<string>;
  /** When this build was created. */
  createdTimeUtc?: string | Computed<string>;
  /** Database connections for the static site build */
  databaseConnections?: OpenapiStaticSiteBuildArmresource_Properties_DatabaseConnections[] | Computed<OpenapiStaticSiteBuildArmresource_Properties_DatabaseConnections[]>;
  /** The hostname for a static site build. */
  hostname?: string | Computed<string>;
  /** When this build was updated. */
  lastUpdatedOn?: string | Computed<string>;
  /** Backends linked to the static side build */
  linkedBackends?: OpenapiStaticSiteBuildArmresource_Properties_LinkedBackends[] | Computed<OpenapiStaticSiteBuildArmresource_Properties_LinkedBackends[]>;
  /** The title of a pull request that a static site build is related to. */
  pullRequestTitle?: string | Computed<string>;
  /** The source branch. */
  sourceBranch?: string | Computed<string>;
  /** The status of the static site build. */
  status?: string | Computed<string>;
  /** User provided function apps registered with the static site build */
  userProvidedFunctionApps?: OpenapiStaticSiteBuildArmresource_Properties_UserProvidedFunctionApps[] | Computed<OpenapiStaticSiteBuildArmresource_Properties_UserProvidedFunctionApps[]>;
}

export interface OpenapiStaticSiteBuildArmresourceConfig {
  environmentName: string | Computed<string>;
  name: string | Computed<string>;
}

export interface OpenapiStaticSiteBuildArmresourceAttrs {
  environmentName: string;
  /** Kind of resource. */
  kind: string;
  name: string;
  /** StaticSiteBuildARMResource resource specific properties */
  properties: OpenapiStaticSiteBuildArmresource_Properties;
}

export const OpenapiStaticSiteBuildArmresource: DataSourceBinding<OpenapiStaticSiteBuildArmresourceConfig, OpenapiStaticSiteBuildArmresourceAttrs> = {
  wireType: "azure_web_openapi_static_site_build_armresource",
  fields: {
    environmentName: "environment_name",
    name: "name",
  },
};
