// Code generated by `ubx sdk gen` from azure_web_openapi_msdeploy_log. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface OpenapiMsdeployLog_Properties_Entries {
  message?: string | Computed<string>;
  time?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface OpenapiMsdeployLog_Properties {
  /** List of log entry messages */
  entries?: OpenapiMsdeployLog_Properties_Entries[] | Computed<OpenapiMsdeployLog_Properties_Entries[]>;
}

export interface OpenapiMsdeployLogConfig {
}

export interface OpenapiMsdeployLogAttrs {
  /** Resource Id. */
  id: string;
  /** Kind of resource. */
  kind: string;
  name: string;
  /** MSDeployLog resource specific properties */
  properties: OpenapiMsdeployLog_Properties;
  /** Resource type. */
  type: string;
}

export const OpenapiMsdeployLog: DataSourceBinding<OpenapiMsdeployLogConfig, OpenapiMsdeployLogAttrs> = {
  wireType: "azure_web_openapi_msdeploy_log",
  fields: {
  },
};
