// Code generated by `ubx sdk gen` from azure_network_networksecurityperimeter_nsp_association. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface NetworksecurityperimeterNspAssociation_Properties_PrivateLinkResource {
  /** Resource ID. */
  id?: string | Computed<string>;
}

export interface NetworksecurityperimeterNspAssociation_Properties {
  /** Access mode on the association. */
  accessMode?: string | Computed<string>;
  /** Specifies if there are provisioning issues */
  hasProvisioningIssues?: string | Computed<string>;
  /** Reference to another subresource. */
  privateLinkResource?: NetworksecurityperimeterNspAssociation_Properties_PrivateLinkResource | Computed<NetworksecurityperimeterNspAssociation_Properties_PrivateLinkResource>;
  /** Reference to another subresource. */
  profile?: NetworksecurityperimeterNspAssociation_Properties_PrivateLinkResource | Computed<NetworksecurityperimeterNspAssociation_Properties_PrivateLinkResource>;
  /** The current provisioning state. */
  provisioningState?: string | Computed<string>;
}

const NetworksecurityperimeterNspAssociation_Properties_PrivateLinkResourceFields: FieldMap = {
  id: "id",
};

const NetworksecurityperimeterNspAssociation_PropertiesFields: FieldMap = {
  accessMode: "access_mode",
  hasProvisioningIssues: "has_provisioning_issues",
  privateLinkResource: {
    wireName: "private_link_resource",
    kind: "object",
    fields: NetworksecurityperimeterNspAssociation_Properties_PrivateLinkResourceFields,
  },
  profile: {
    wireName: "profile",
    kind: "object",
    fields: NetworksecurityperimeterNspAssociation_Properties_PrivateLinkResourceFields,
  },
  provisioningState: "provisioning_state",
};

export interface NetworksecurityperimeterNspAssociationConfig {
  properties?: NetworksecurityperimeterNspAssociation_Properties | Computed<NetworksecurityperimeterNspAssociation_Properties>;
}

export interface NetworksecurityperimeterNspAssociationAttrs {
  properties: NetworksecurityperimeterNspAssociation_Properties;
}

export const NetworksecurityperimeterNspAssociation: ResourceBinding<NetworksecurityperimeterNspAssociationConfig, NetworksecurityperimeterNspAssociationAttrs> = {
  wireType: "azure_network_networksecurityperimeter_nsp_association",
  fields: {
    properties: {
      wireName: "properties",
      kind: "object",
      fields: NetworksecurityperimeterNspAssociation_PropertiesFields,
    },
  },
};
