// Code generated by `ubx sdk gen` from azure_network_virtualnetwork_swap_resource. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface VirtualnetworkSwapResource_Properties {
  /** Specifies slot info on a cloud service */
  slotType?: string | Computed<string>;
}

const VirtualnetworkSwapResource_PropertiesFields: FieldMap = {
  slotType: "slot_type",
};

export interface VirtualnetworkSwapResourceConfig {
  /** Swap resource properties */
  properties?: VirtualnetworkSwapResource_Properties | Computed<VirtualnetworkSwapResource_Properties>;
}

export interface VirtualnetworkSwapResourceAttrs {
  /** Resource ID. */
  id: string;
  /** Resource name. */
  name: string;
  /** Swap resource properties */
  properties: VirtualnetworkSwapResource_Properties;
  /** Resource type. */
  type: string;
}

export const VirtualnetworkSwapResource: ResourceBinding<VirtualnetworkSwapResourceConfig, VirtualnetworkSwapResourceAttrs> = {
  wireType: "azure_network_virtualnetwork_swap_resource",
  fields: {
    properties: {
      wireName: "properties",
      kind: "object",
      fields: VirtualnetworkSwapResource_PropertiesFields,
    },
  },
};
