// Code generated by `ubx sdk gen` from azure_network_virtualnetwork_verifier_workspace. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface VirtualnetworkVerifierWorkspace_Properties {
  description?: string | Computed<string>;
  /** Provisioning states of a resource. */
  provisioningState?: string | Computed<string>;
}

export interface VirtualnetworkVerifierWorkspace_SystemData {
  /** The timestamp of resource creation (UTC). */
  createdAt?: string | Computed<string>;
  /** The identity that created the resource. */
  createdBy?: string | Computed<string>;
  /** The type of identity that created the resource. */
  createdByType?: string | Computed<string>;
  /** The timestamp of resource last modification (UTC) */
  lastModifiedAt?: string | Computed<string>;
  /** The identity that last modified the resource. */
  lastModifiedBy?: string | Computed<string>;
  /** The type of identity that last modified the resource. */
  lastModifiedByType?: string | Computed<string>;
}

const VirtualnetworkVerifierWorkspace_PropertiesFields: FieldMap = {
  description: "description",
  provisioningState: "provisioning_state",
};

const VirtualnetworkVerifierWorkspace_SystemDataFields: FieldMap = {
  createdAt: "created_at",
  createdBy: "created_by",
  createdByType: "created_by_type",
  lastModifiedAt: "last_modified_at",
  lastModifiedBy: "last_modified_by",
  lastModifiedByType: "last_modified_by_type",
};

export interface VirtualnetworkVerifierWorkspaceConfig {
  /** String representing unique etag for the resource document. */
  etag?: string | Computed<string>;
  /** Properties of Verifier Workspace resource. */
  properties?: VirtualnetworkVerifierWorkspace_Properties | Computed<VirtualnetworkVerifierWorkspace_Properties>;
  /** Metadata pertaining to creation and last modification of the resource. */
  systemData?: VirtualnetworkVerifierWorkspace_SystemData | Computed<VirtualnetworkVerifierWorkspace_SystemData>;
}

export interface VirtualnetworkVerifierWorkspaceAttrs {
  /** String representing unique etag for the resource document. */
  etag: string;
  /** Properties of Verifier Workspace resource. */
  properties: VirtualnetworkVerifierWorkspace_Properties;
  /** Metadata pertaining to creation and last modification of the resource. */
  systemData: VirtualnetworkVerifierWorkspace_SystemData;
}

export const VirtualnetworkVerifierWorkspace: ResourceBinding<VirtualnetworkVerifierWorkspaceConfig, VirtualnetworkVerifierWorkspaceAttrs> = {
  wireType: "azure_network_virtualnetwork_verifier_workspace",
  fields: {
    etag: "etag",
    properties: {
      wireName: "properties",
      kind: "object",
      fields: VirtualnetworkVerifierWorkspace_PropertiesFields,
    },
    systemData: {
      wireName: "system_data",
      kind: "object",
      fields: VirtualnetworkVerifierWorkspace_SystemDataFields,
    },
  },
};
