// Code generated by `ubx sdk gen` from azure_network_virtualwan_route_map. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface VirtualwanRouteMap_Properties_Rules_Actions_Parameters {
  /** The BGP AS-path attribute observed for this route. (AI-inferred) */
  asPath?: string[] | Computed<string[]>;
  /** A BGP community value attached to this route. (AI-inferred) */
  community?: string[] | Computed<string[]>;
  /** The route prefix this rule matches. (AI-inferred) */
  routePrefix?: string[] | Computed<string[]>;
}

export interface VirtualwanRouteMap_Properties_Rules_Actions {
  /** The parameter(s) making up this configuration. (AI-inferred) */
  parameters?: VirtualwanRouteMap_Properties_Rules_Actions_Parameters[] | Computed<VirtualwanRouteMap_Properties_Rules_Actions_Parameters[]>;
  /** The Azure resource type, in the form `{resource-provider}/{resource-type}`, e.g. `Microsoft.Network/loadBalancers`. (AI-inferred) */
  type?: string | Computed<string>;
}

export interface VirtualwanRouteMap_Properties_Rules_MatchCriteria {
  /** The BGP AS-path attribute observed for this route. (AI-inferred) */
  asPath?: string[] | Computed<string[]>;
  /** A BGP community value attached to this route. (AI-inferred) */
  community?: string[] | Computed<string[]>;
  /** The condition that must hold for this rule to apply. (AI-inferred) */
  matchCondition?: string | Computed<string>;
  /** The route prefix this rule matches. (AI-inferred) */
  routePrefix?: string[] | Computed<string[]>;
}

export interface VirtualwanRouteMap_Properties_Rules {
  /** The action(s) this rule or policy applies. (AI-inferred) */
  actions?: VirtualwanRouteMap_Properties_Rules_Actions[] | Computed<VirtualwanRouteMap_Properties_Rules_Actions[]>;
  /** Whether all or any of this rule's own conditions must match. (AI-inferred) */
  matchCriteria?: VirtualwanRouteMap_Properties_Rules_MatchCriteria[] | Computed<VirtualwanRouteMap_Properties_Rules_MatchCriteria[]>;
  /** The resource's own name, unique within its parent scope. (AI-inferred) */
  name?: string | Computed<string>;
  /** What happens next when this rule's own condition matches. (AI-inferred) */
  nextStepIfMatched?: string | Computed<string>;
}

export interface VirtualwanRouteMap_Properties {
  /** List of connections which have this RoutMap associated for inbound traffic. */
  associatedInboundConnections?: string[] | Computed<string[]>;
  /** List of connections which have this RoutMap associated for outbound traffic. */
  associatedOutboundConnections?: string[] | Computed<string[]>;
  /** Provisioning states of a resource. */
  provisioningState?: string | Computed<string>;
  /** List of RouteMap rules to be applied. */
  rules?: VirtualwanRouteMap_Properties_Rules[] | Computed<VirtualwanRouteMap_Properties_Rules[]>;
}

const VirtualwanRouteMap_Properties_Rules_Actions_ParametersFields: FieldMap = {
  asPath: "as_path",
  community: "community",
  routePrefix: "route_prefix",
};

const VirtualwanRouteMap_Properties_Rules_ActionsFields: FieldMap = {
  parameters: {
    wireName: "parameters",
    kind: "list",
    fields: VirtualwanRouteMap_Properties_Rules_Actions_ParametersFields,
  },
  type: "type",
};

const VirtualwanRouteMap_Properties_Rules_MatchCriteriaFields: FieldMap = {
  asPath: "as_path",
  community: "community",
  matchCondition: "match_condition",
  routePrefix: "route_prefix",
};

const VirtualwanRouteMap_Properties_RulesFields: FieldMap = {
  actions: {
    wireName: "actions",
    kind: "list",
    fields: VirtualwanRouteMap_Properties_Rules_ActionsFields,
  },
  matchCriteria: {
    wireName: "match_criteria",
    kind: "list",
    fields: VirtualwanRouteMap_Properties_Rules_MatchCriteriaFields,
  },
  name: "name",
  nextStepIfMatched: "next_step_if_matched",
};

const VirtualwanRouteMap_PropertiesFields: FieldMap = {
  associatedInboundConnections: "associated_inbound_connections",
  associatedOutboundConnections: "associated_outbound_connections",
  provisioningState: "provisioning_state",
  rules: {
    wireName: "rules",
    kind: "list",
    fields: VirtualwanRouteMap_Properties_RulesFields,
  },
};

export interface VirtualwanRouteMapConfig {
  /** Properties of RouteMap resource */
  properties?: VirtualwanRouteMap_Properties | Computed<VirtualwanRouteMap_Properties>;
}

export interface VirtualwanRouteMapAttrs {
  /** A unique read-only string that changes whenever the resource is updated. */
  etag: string;
  /** Resource ID. */
  id: string;
  /** Name of the resource. */
  name: string;
  /** Properties of RouteMap resource */
  properties: VirtualwanRouteMap_Properties;
  /** Type of the resource. */
  type: string;
}

export const VirtualwanRouteMap: ResourceBinding<VirtualwanRouteMapConfig, VirtualwanRouteMapAttrs> = {
  wireType: "azure_network_virtualwan_route_map",
  fields: {
    properties: {
      wireName: "properties",
      kind: "object",
      fields: VirtualwanRouteMap_PropertiesFields,
    },
  },
};
