# Code generated by `ubx sdk gen` from azure_vmware_global_reach_connection_list. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class GlobalReachConnectionList_Value_Properties:
    address_prefix: Any = None
    authorization_key: Any = None
    circuit_connection_status: Any = None
    express_route_id: Any = None
    peer_express_route_circuit: Any = None
    provisioning_state: Any = None

@dataclasses.dataclass
class GlobalReachConnectionList_Value:
    properties: Any = None

@dataclasses.dataclass
class GlobalReachConnectionListConfig:
    private_cloud_name: Any = None

@dataclasses.dataclass
class GlobalReachConnectionListAttrs:
    # The link to the next page of items
    next_link: Any = None
    private_cloud_name: Any = None
    # The GlobalReachConnection items on this page
    value: Any = None

GlobalReachConnectionList = ubx.DataSourceBinding(
    wire_type="azure_vmware_global_reach_connection_list",
    fields={
        "private_cloud_name": ubx.FieldSpec(wire_name="private_cloud_name"),
    },
)
