// Code generated by `ubx sdk gen` from azure_hybridcompute_openapi_license. DO NOT EDIT.
package hybridcompute

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpenapiLicense_Properties_LicenseDetails_VolumeLicenseDetails struct {
	InvoiceId   any
	ProgramYear any
}

type OpenapiLicense_Properties_LicenseDetails struct {
	// Describes the number of assigned licenses.
	AssignedLicenses any
	// Describes the edition of the license. The values are either Standard or Datacenter.
	Edition any
	// Describes the immutable id.
	ImmutableId any
	// Describes the number of processors.
	Processors any
	// Describes the state of the license.
	State any
	// Describes the license target server.
	Target any
	// Describes the license core type (pCore or vCore).
	Type any
	// A list of volume license details.
	VolumeLicenseDetails any
}

type OpenapiLicense_Properties struct {
	// Describes the properties of a License.
	LicenseDetails any
	// The type of the license resource.
	LicenseType any
	// The provisioning state, which only appears in the response.
	ProvisioningState any
	// Describes the tenant id.
	TenantId any
}

var OpenapiLicense_Properties_LicenseDetails_VolumeLicenseDetailsFields = ubx.FieldMap{
	"InvoiceId":   ubx.FieldSpec{WireName: "invoice_id"},
	"ProgramYear": ubx.FieldSpec{WireName: "program_year"},
}

var OpenapiLicense_Properties_LicenseDetailsFields = ubx.FieldMap{
	"AssignedLicenses": ubx.FieldSpec{WireName: "assigned_licenses"},
	"Edition":          ubx.FieldSpec{WireName: "edition"},
	"ImmutableId":      ubx.FieldSpec{WireName: "immutable_id"},
	"Processors":       ubx.FieldSpec{WireName: "processors"},
	"State":            ubx.FieldSpec{WireName: "state"},
	"Target":           ubx.FieldSpec{WireName: "target"},
	"Type":             ubx.FieldSpec{WireName: "type"},
	"VolumeLicenseDetails": ubx.FieldSpec{
		WireName: "volume_license_details",
		Kind:     "list",
		Fields:   OpenapiLicense_Properties_LicenseDetails_VolumeLicenseDetailsFields,
	},
}

var OpenapiLicense_PropertiesFields = ubx.FieldMap{
	"LicenseDetails": ubx.FieldSpec{
		WireName: "license_details",
		Kind:     "object",
		Fields:   OpenapiLicense_Properties_LicenseDetailsFields,
	},
	"LicenseType":       ubx.FieldSpec{WireName: "license_type"},
	"ProvisioningState": ubx.FieldSpec{WireName: "provisioning_state"},
	"TenantId":          ubx.FieldSpec{WireName: "tenant_id"},
}

type OpenapiLicenseConfig struct {
	// The geo-location where the resource lives
	Location any
	// Describes the properties of a License Profile.
	Properties any
	// Resource tags.
	Tags any
}

type OpenapiLicenseAttrs struct {
	// The geo-location where the resource lives
	Location any
	// Describes the properties of a License Profile.
	Properties any
	// Resource tags.
	Tags any
}

var OpenapiLicense = ubx.ResourceBinding{
	WireType: "azure_hybridcompute_openapi_license",
	Fields: ubx.FieldMap{
		"Location": ubx.FieldSpec{WireName: "location"},
		"Properties": ubx.FieldSpec{
			WireName: "properties",
			Kind:     "object",
			Fields:   OpenapiLicense_PropertiesFields,
		},
		"Tags": ubx.FieldSpec{WireName: "tags"},
	},
}
