# Code generated by `ubx sdk gen` from azure_recoveryservicessiterecovery_service_recovery_plan. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ServiceRecoveryPlan_Properties_Groups_EndGroupActions_CustomDetails:
    instance_type: Any = None

@dataclasses.dataclass
class ServiceRecoveryPlan_Properties_Groups_EndGroupActions:
    action_name: Any = None
    custom_details: Any = None
    failover_directions: Any = None
    failover_types: Any = None

@dataclasses.dataclass
class ServiceRecoveryPlan_Properties_Groups_ReplicationProtectedItems:
    id: Any = None
    virtual_machine_id: Any = None

@dataclasses.dataclass
class ServiceRecoveryPlan_Properties_Groups:
    end_group_actions: Any = None
    group_type: Any = None
    replication_protected_items: Any = None
    start_group_actions: Any = None

@dataclasses.dataclass
class ServiceRecoveryPlan_Properties:
    # The failover deployment model.
    failover_deployment_model: Any = None
    # The recovery plan groups.
    groups: Any = None
    # The primary fabric Id.
    primary_fabric_id: Any = None
    # The provider specific input.
    provider_specific_input: Any = None
    # The recovery fabric Id.
    recovery_fabric_id: Any = None

_ServiceRecoveryPlan_Properties_Groups_EndGroupActions_CustomDetailsFields = {
    "instance_type": ubx.FieldSpec(wire_name="instance_type"),
}

_ServiceRecoveryPlan_Properties_Groups_EndGroupActionsFields = {
    "action_name": ubx.FieldSpec(wire_name="action_name"),
    "custom_details": ubx.FieldSpec(
        wire_name="custom_details",
        kind="object",
        fields=_ServiceRecoveryPlan_Properties_Groups_EndGroupActions_CustomDetailsFields,
    ),
    "failover_directions": ubx.FieldSpec(wire_name="failover_directions"),
    "failover_types": ubx.FieldSpec(wire_name="failover_types"),
}

_ServiceRecoveryPlan_Properties_Groups_ReplicationProtectedItemsFields = {
    "id": ubx.FieldSpec(wire_name="id"),
    "virtual_machine_id": ubx.FieldSpec(wire_name="virtual_machine_id"),
}

_ServiceRecoveryPlan_Properties_GroupsFields = {
    "end_group_actions": ubx.FieldSpec(
        wire_name="end_group_actions",
        kind="list",
        fields=_ServiceRecoveryPlan_Properties_Groups_EndGroupActionsFields,
    ),
    "group_type": ubx.FieldSpec(wire_name="group_type"),
    "replication_protected_items": ubx.FieldSpec(
        wire_name="replication_protected_items",
        kind="list",
        fields=_ServiceRecoveryPlan_Properties_Groups_ReplicationProtectedItemsFields,
    ),
    "start_group_actions": ubx.FieldSpec(
        wire_name="start_group_actions",
        kind="list",
        fields=_ServiceRecoveryPlan_Properties_Groups_EndGroupActionsFields,
    ),
}

_ServiceRecoveryPlan_PropertiesFields = {
    "failover_deployment_model": ubx.FieldSpec(wire_name="failover_deployment_model"),
    "groups": ubx.FieldSpec(
        wire_name="groups",
        kind="list",
        fields=_ServiceRecoveryPlan_Properties_GroupsFields,
    ),
    "primary_fabric_id": ubx.FieldSpec(wire_name="primary_fabric_id"),
    "provider_specific_input": ubx.FieldSpec(
        wire_name="provider_specific_input",
        kind="list",
        fields=_ServiceRecoveryPlan_Properties_Groups_EndGroupActions_CustomDetailsFields,
    ),
    "recovery_fabric_id": ubx.FieldSpec(wire_name="recovery_fabric_id"),
}

@dataclasses.dataclass
class ServiceRecoveryPlanConfig:
    # Recovery plan creation properties.
    properties: Any = None

@dataclasses.dataclass
class ServiceRecoveryPlanAttrs:
    # Resource Location
    location: Any = None
    # Recovery plan creation properties.
    properties: Any = None

ServiceRecoveryPlan = ubx.ResourceBinding(
    wire_type="azure_recoveryservicessiterecovery_service_recovery_plan",
    fields={
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_ServiceRecoveryPlan_PropertiesFields,
        ),
    },
)
