# Code generated by `ubx sdk gen` from azure_machinelearningservices_openapi_model_container. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OpenapiModelContainer_Properties:
    # Provisioning state of registry asset.
    provisioning_state: Any = None

_OpenapiModelContainer_PropertiesFields = {
    "provisioning_state": ubx.FieldSpec(wire_name="provisioning_state"),
}

@dataclasses.dataclass
class OpenapiModelContainerConfig:
    # The resource type-specific configuration for this resource, wrapping every field that isn't part of ARM's own standard envelope (id/name/type/location/tags). (AI-inferred)
    properties: Any = None

@dataclasses.dataclass
class OpenapiModelContainerAttrs:
    # The resource type-specific configuration for this resource, wrapping every field that isn't part of ARM's own standard envelope (id/name/type/location/tags). (AI-inferred)
    properties: Any = None

OpenapiModelContainer = ubx.ResourceBinding(
    wire_type="azure_machinelearningservices_openapi_model_container",
    fields={
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_OpenapiModelContainer_PropertiesFields,
        ),
    },
)
