# Code generated by `ubx sdk gen` from azure_machinelearningservices_openapi_job_base. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OpenapiJobBase_Properties_Identity:
    # Enum to determine identity framework.
    identity_type: Any = None

@dataclasses.dataclass
class OpenapiJobBase_Properties_NotificationSetting_Webhooks:
    event_type: Any = None
    webhook_type: Any = None

@dataclasses.dataclass
class OpenapiJobBase_Properties_NotificationSetting:
    # Send email notification to user on specified notification type
    email_on: Any = None
    # This is the email recipient list which has a limitation of 499 characters in total concat with comma separator
    emails: Any = None
    # Send webhook callback to a service. Key is a user-provided name for the webhook.
    webhooks: Any = None

@dataclasses.dataclass
class OpenapiJobBase_Properties_Services_Nodes:
    nodes_value_type: Any = None

@dataclasses.dataclass
class OpenapiJobBase_Properties_Services:
    endpoint: Any = None
    error_message: Any = None
    job_service_type: Any = None
    nodes: Any = None
    port: Any = None
    properties: Any = None
    status: Any = None

@dataclasses.dataclass
class OpenapiJobBase_Properties:
    # ARM resource ID of the component resource.
    component_id: Any = None
    # ARM resource ID of the compute resource.
    compute_id: Any = None
    # Display name of job.
    display_name: Any = None
    # The name of the experiment the job belongs to. If not set, the job is placed in the "Default" experiment.
    experiment_name: Any = None
    # Base definition for identity configuration.
    identity: Any = None
    # Is the asset archived?
    is_archived: Any = None
    # Enum to determine the type of job.
    job_type: Any = None
    # Configuration for notification.
    notification_setting: Any = None
    # List of JobEndpoints. For local jobs, a job endpoint will have an endpoint value of FileStreamObject.
    services: Any = None
    # The status of a job.
    status: Any = None

_OpenapiJobBase_Properties_IdentityFields = {
    "identity_type": ubx.FieldSpec(wire_name="identity_type"),
}

_OpenapiJobBase_Properties_NotificationSetting_WebhooksFields = {
    "event_type": ubx.FieldSpec(wire_name="event_type"),
    "webhook_type": ubx.FieldSpec(wire_name="webhook_type"),
}

_OpenapiJobBase_Properties_NotificationSettingFields = {
    "email_on": ubx.FieldSpec(wire_name="email_on"),
    "emails": ubx.FieldSpec(wire_name="emails"),
    "webhooks": ubx.FieldSpec(
        wire_name="webhooks",
        kind="map",
        fields=_OpenapiJobBase_Properties_NotificationSetting_WebhooksFields,
    ),
}

_OpenapiJobBase_Properties_Services_NodesFields = {
    "nodes_value_type": ubx.FieldSpec(wire_name="nodes_value_type"),
}

_OpenapiJobBase_Properties_ServicesFields = {
    "endpoint": ubx.FieldSpec(wire_name="endpoint"),
    "error_message": ubx.FieldSpec(wire_name="error_message"),
    "job_service_type": ubx.FieldSpec(wire_name="job_service_type"),
    "nodes": ubx.FieldSpec(
        wire_name="nodes",
        kind="object",
        fields=_OpenapiJobBase_Properties_Services_NodesFields,
    ),
    "port": ubx.FieldSpec(wire_name="port"),
    "properties": ubx.FieldSpec(wire_name="properties"),
    "status": ubx.FieldSpec(wire_name="status"),
}

_OpenapiJobBase_PropertiesFields = {
    "component_id": ubx.FieldSpec(wire_name="component_id"),
    "compute_id": ubx.FieldSpec(wire_name="compute_id"),
    "display_name": ubx.FieldSpec(wire_name="display_name"),
    "experiment_name": ubx.FieldSpec(wire_name="experiment_name"),
    "identity": ubx.FieldSpec(
        wire_name="identity",
        kind="object",
        fields=_OpenapiJobBase_Properties_IdentityFields,
    ),
    "is_archived": ubx.FieldSpec(wire_name="is_archived"),
    "job_type": ubx.FieldSpec(wire_name="job_type"),
    "notification_setting": ubx.FieldSpec(
        wire_name="notification_setting",
        kind="object",
        fields=_OpenapiJobBase_Properties_NotificationSettingFields,
    ),
    "services": ubx.FieldSpec(
        wire_name="services",
        kind="map",
        fields=_OpenapiJobBase_Properties_ServicesFields,
    ),
    "status": ubx.FieldSpec(wire_name="status"),
}

@dataclasses.dataclass
class OpenapiJobBaseConfig:
    # Base definition for a job.
    properties: Any = None
    # path parameter, not part of the API's own resource representation
    id: Any = None

@dataclasses.dataclass
class OpenapiJobBaseAttrs:
    # Base definition for a job.
    properties: Any = None
    # path parameter, not part of the API's own resource representation
    id: Any = None

OpenapiJobBase = ubx.ResourceBinding(
    wire_type="azure_machinelearningservices_openapi_job_base",
    fields={
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_OpenapiJobBase_PropertiesFields,
        ),
        "id": ubx.FieldSpec(wire_name="id"),
    },
)
