// Code generated by `ubx sdk gen` from azure_containerservice_managedclusters_outbound_environment_endpoint. DO NOT EDIT.
package containerservice

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagedclustersOutboundEnvironmentEndpoint_Value_Endpoints_EndpointDetails struct {
	Description any
	IpAddress any
	Port any
	Protocol any
}

type ManagedclustersOutboundEnvironmentEndpoint_Value_Endpoints struct {
	DomainName any
	EndpointDetails any
}

type ManagedclustersOutboundEnvironmentEndpoint_Value struct {
	Category any
	Endpoints any
}

type ManagedclustersOutboundEnvironmentEndpointConfig struct {
	ResourceName any
}

type ManagedclustersOutboundEnvironmentEndpointAttrs struct {
	// The link to the next page of items
	NextLink any
	ResourceName any
	// The OutboundEnvironmentEndpoint items on this page
	Value any
}

var ManagedclustersOutboundEnvironmentEndpoint = ubx.DataSourceBinding{
	WireType: "azure_containerservice_managedclusters_outbound_environment_endpoint",
	Fields: ubx.FieldMap{
		"ResourceName": ubx.FieldSpec{WireName: "resource_name"},
	},
}
