// Code generated by `ubx sdk gen` from azure_datadog_monitoring_tag_rules. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface MonitoringTagRules_Value_Properties_AgentRules_FilteringTags {
  action?: string | Computed<string>;
  name?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface MonitoringTagRules_Value_Properties_AgentRules {
  enableAgentMonitoring?: boolean | Computed<boolean>;
  filteringTags?: MonitoringTagRules_Value_Properties_AgentRules_FilteringTags[] | Computed<MonitoringTagRules_Value_Properties_AgentRules_FilteringTags[]>;
}

export interface MonitoringTagRules_Value_Properties_LogRules {
  filteringTags?: MonitoringTagRules_Value_Properties_AgentRules_FilteringTags[] | Computed<MonitoringTagRules_Value_Properties_AgentRules_FilteringTags[]>;
  sendAadLogs?: boolean | Computed<boolean>;
  sendResourceLogs?: boolean | Computed<boolean>;
  sendSubscriptionLogs?: boolean | Computed<boolean>;
}

export interface MonitoringTagRules_Value_Properties_MetricRules {
  filteringTags?: MonitoringTagRules_Value_Properties_AgentRules_FilteringTags[] | Computed<MonitoringTagRules_Value_Properties_AgentRules_FilteringTags[]>;
}

export interface MonitoringTagRules_Value_Properties {
  agentRules?: MonitoringTagRules_Value_Properties_AgentRules | Computed<MonitoringTagRules_Value_Properties_AgentRules>;
  automuting?: boolean | Computed<boolean>;
  customMetrics?: boolean | Computed<boolean>;
  logRules?: MonitoringTagRules_Value_Properties_LogRules | Computed<MonitoringTagRules_Value_Properties_LogRules>;
  metricRules?: MonitoringTagRules_Value_Properties_MetricRules | Computed<MonitoringTagRules_Value_Properties_MetricRules>;
  provisioningState?: string | Computed<string>;
}

export interface MonitoringTagRules_Value {
  properties?: MonitoringTagRules_Value_Properties | Computed<MonitoringTagRules_Value_Properties>;
}

export interface MonitoringTagRulesConfig {
  monitorName: string | Computed<string>;
}

export interface MonitoringTagRulesAttrs {
  monitorName: string;
  /** The link to the next page of items */
  nextLink: string;
  /** The MonitoringTagRules items on this page */
  value: MonitoringTagRules_Value[];
}

export const MonitoringTagRules: DataSourceBinding<MonitoringTagRulesConfig, MonitoringTagRulesAttrs> = {
  wireType: "azure_datadog_monitoring_tag_rules",
  fields: {
    monitorName: "monitor_name",
  },
};
