// Code generated by `ubx sdk gen` from azure_graphservicesprod_microsoft_graph_service. DO NOT EDIT.
package graphservicesprod

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type MicrosoftGraphService_Value_Display struct {
	Description any
	Operation any
	Provider any
	Resource any
}

type MicrosoftGraphService_Value struct {
	ActionType any
	Display any
	IsDataAction any
	Name any
	Origin any
}

type MicrosoftGraphServiceConfig struct {
}

type MicrosoftGraphServiceAttrs struct {
	// URL to get the next set of operation list results (if there are any).
	NextLink any
	// List of operations supported by the resource provider
	Value any
}

var MicrosoftGraphService = ubx.DataSourceBinding{
	WireType: "azure_graphservicesprod_microsoft_graph_service",
	Fields: ubx.FieldMap{
	},
}
