// Code generated by `ubx sdk gen` from azurerm_api_management. DO NOT EDIT.
package api

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Management_AdditionalLocation_VirtualNetworkConfiguration struct {
	SubnetId any
}

type Management_AdditionalLocation struct {
	Capacity any
	GatewayDisabled any
	GatewayRegionalUrl any
	Location any
	PrivateIpAddresses any
	PublicIpAddressId any
	PublicIpAddresses any
	Zones any
	VirtualNetworkConfiguration any
}

type Management_Certificate struct {
	CertificatePassword any
	EncodedCertificate any
	Expiry any
	StoreName any
	Subject any
	Thumbprint any
}

type Management_Delegation struct {
	SubscriptionsEnabled any
	Url any
	UserRegistrationEnabled any
	ValidationKey any
}

type Management_HostnameConfiguration_DeveloperPortal struct {
	Certificate any
	CertificatePassword any
	CertificateSource any
	CertificateStatus any
	Expiry any
	HostName any
	KeyVaultCertificateId any
	NegotiateClientCertificate any
	SslKeyvaultIdentityClientId any
	Subject any
	Thumbprint any
}

type Management_HostnameConfiguration_Proxy struct {
	Certificate any
	CertificatePassword any
	CertificateSource any
	CertificateStatus any
	DefaultSslBinding any
	Expiry any
	HostName any
	KeyVaultCertificateId any
	NegotiateClientCertificate any
	SslKeyvaultIdentityClientId any
	Subject any
	Thumbprint any
}

type Management_HostnameConfiguration struct {
	DeveloperPortal any
	Management any
	Portal any
	Proxy any
	Scm any
}

type Management_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type Management_Protocols struct {
	Http2Enabled any
}

type Management_Security struct {
	BackendSsl30Enabled any
	BackendTls10Enabled any
	BackendTls11Enabled any
	FrontendSsl30Enabled any
	FrontendTls10Enabled any
	FrontendTls11Enabled any
	TlsEcdheEcdsaWithAes128CbcShaCiphersEnabled any
	TlsEcdheEcdsaWithAes256CbcShaCiphersEnabled any
	TlsEcdheRsaWithAes128CbcShaCiphersEnabled any
	TlsEcdheRsaWithAes256CbcShaCiphersEnabled any
	TlsRsaWithAes128CbcSha256CiphersEnabled any
	TlsRsaWithAes128CbcShaCiphersEnabled any
	TlsRsaWithAes128GcmSha256CiphersEnabled any
	TlsRsaWithAes256CbcSha256CiphersEnabled any
	TlsRsaWithAes256CbcShaCiphersEnabled any
	TlsRsaWithAes256GcmSha384CiphersEnabled any
	TripleDesCiphersEnabled any
}

type Management_SignIn struct {
	Enabled any
}

type Management_SignUp_TermsOfService struct {
	ConsentRequired any
	Enabled any
	Text any
}

type Management_SignUp struct {
	Enabled any
	TermsOfService any
}

type Management_TenantAccess struct {
	Enabled any
	PrimaryKey any
	SecondaryKey any
	TenantId any
}

type Management_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Management_AdditionalLocation_VirtualNetworkConfigurationFields = ubx.FieldMap{
		"SubnetId": ubx.FieldSpec{WireName: "subnet_id"},
	}

var Management_AdditionalLocationFields = ubx.FieldMap{
		"Capacity": ubx.FieldSpec{WireName: "capacity"},
		"GatewayDisabled": ubx.FieldSpec{WireName: "gateway_disabled"},
		"GatewayRegionalUrl": ubx.FieldSpec{WireName: "gateway_regional_url"},
		"Location": ubx.FieldSpec{WireName: "location"},
		"PrivateIpAddresses": ubx.FieldSpec{WireName: "private_ip_addresses"},
		"PublicIpAddressId": ubx.FieldSpec{WireName: "public_ip_address_id"},
		"PublicIpAddresses": ubx.FieldSpec{WireName: "public_ip_addresses"},
		"Zones": ubx.FieldSpec{WireName: "zones"},
		"VirtualNetworkConfiguration": ubx.FieldSpec{
			WireName: "virtual_network_configuration",
			Kind: "list",
			Fields: Management_AdditionalLocation_VirtualNetworkConfigurationFields,
		},
	}

var Management_CertificateFields = ubx.FieldMap{
		"CertificatePassword": ubx.FieldSpec{WireName: "certificate_password"},
		"EncodedCertificate": ubx.FieldSpec{WireName: "encoded_certificate"},
		"Expiry": ubx.FieldSpec{WireName: "expiry"},
		"StoreName": ubx.FieldSpec{WireName: "store_name"},
		"Subject": ubx.FieldSpec{WireName: "subject"},
		"Thumbprint": ubx.FieldSpec{WireName: "thumbprint"},
	}

var Management_DelegationFields = ubx.FieldMap{
		"SubscriptionsEnabled": ubx.FieldSpec{WireName: "subscriptions_enabled"},
		"Url": ubx.FieldSpec{WireName: "url"},
		"UserRegistrationEnabled": ubx.FieldSpec{WireName: "user_registration_enabled"},
		"ValidationKey": ubx.FieldSpec{WireName: "validation_key"},
	}

var Management_HostnameConfiguration_DeveloperPortalFields = ubx.FieldMap{
		"Certificate": ubx.FieldSpec{WireName: "certificate"},
		"CertificatePassword": ubx.FieldSpec{WireName: "certificate_password"},
		"CertificateSource": ubx.FieldSpec{WireName: "certificate_source"},
		"CertificateStatus": ubx.FieldSpec{WireName: "certificate_status"},
		"Expiry": ubx.FieldSpec{WireName: "expiry"},
		"HostName": ubx.FieldSpec{WireName: "host_name"},
		"KeyVaultCertificateId": ubx.FieldSpec{WireName: "key_vault_certificate_id"},
		"NegotiateClientCertificate": ubx.FieldSpec{WireName: "negotiate_client_certificate"},
		"SslKeyvaultIdentityClientId": ubx.FieldSpec{WireName: "ssl_keyvault_identity_client_id"},
		"Subject": ubx.FieldSpec{WireName: "subject"},
		"Thumbprint": ubx.FieldSpec{WireName: "thumbprint"},
	}

var Management_HostnameConfiguration_ProxyFields = ubx.FieldMap{
		"Certificate": ubx.FieldSpec{WireName: "certificate"},
		"CertificatePassword": ubx.FieldSpec{WireName: "certificate_password"},
		"CertificateSource": ubx.FieldSpec{WireName: "certificate_source"},
		"CertificateStatus": ubx.FieldSpec{WireName: "certificate_status"},
		"DefaultSslBinding": ubx.FieldSpec{WireName: "default_ssl_binding"},
		"Expiry": ubx.FieldSpec{WireName: "expiry"},
		"HostName": ubx.FieldSpec{WireName: "host_name"},
		"KeyVaultCertificateId": ubx.FieldSpec{WireName: "key_vault_certificate_id"},
		"NegotiateClientCertificate": ubx.FieldSpec{WireName: "negotiate_client_certificate"},
		"SslKeyvaultIdentityClientId": ubx.FieldSpec{WireName: "ssl_keyvault_identity_client_id"},
		"Subject": ubx.FieldSpec{WireName: "subject"},
		"Thumbprint": ubx.FieldSpec{WireName: "thumbprint"},
	}

var Management_HostnameConfigurationFields = ubx.FieldMap{
		"DeveloperPortal": ubx.FieldSpec{
			WireName: "developer_portal",
			Kind: "list",
			Fields: Management_HostnameConfiguration_DeveloperPortalFields,
		},
		"Management": ubx.FieldSpec{
			WireName: "management",
			Kind: "list",
			Fields: Management_HostnameConfiguration_DeveloperPortalFields,
		},
		"Portal": ubx.FieldSpec{
			WireName: "portal",
			Kind: "list",
			Fields: Management_HostnameConfiguration_DeveloperPortalFields,
		},
		"Proxy": ubx.FieldSpec{
			WireName: "proxy",
			Kind: "list",
			Fields: Management_HostnameConfiguration_ProxyFields,
		},
		"Scm": ubx.FieldSpec{
			WireName: "scm",
			Kind: "list",
			Fields: Management_HostnameConfiguration_DeveloperPortalFields,
		},
	}

var Management_IdentityFields = ubx.FieldMap{
		"IdentityIds": ubx.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": ubx.FieldSpec{WireName: "principal_id"},
		"TenantId": ubx.FieldSpec{WireName: "tenant_id"},
		"Type": ubx.FieldSpec{WireName: "type"},
	}

var Management_ProtocolsFields = ubx.FieldMap{
		"Http2Enabled": ubx.FieldSpec{WireName: "http2_enabled"},
	}

var Management_SecurityFields = ubx.FieldMap{
		"BackendSsl30Enabled": ubx.FieldSpec{WireName: "backend_ssl30_enabled"},
		"BackendTls10Enabled": ubx.FieldSpec{WireName: "backend_tls10_enabled"},
		"BackendTls11Enabled": ubx.FieldSpec{WireName: "backend_tls11_enabled"},
		"FrontendSsl30Enabled": ubx.FieldSpec{WireName: "frontend_ssl30_enabled"},
		"FrontendTls10Enabled": ubx.FieldSpec{WireName: "frontend_tls10_enabled"},
		"FrontendTls11Enabled": ubx.FieldSpec{WireName: "frontend_tls11_enabled"},
		"TlsEcdheEcdsaWithAes128CbcShaCiphersEnabled": ubx.FieldSpec{WireName: "tls_ecdhe_ecdsa_with_aes128_cbc_sha_ciphers_enabled"},
		"TlsEcdheEcdsaWithAes256CbcShaCiphersEnabled": ubx.FieldSpec{WireName: "tls_ecdhe_ecdsa_with_aes256_cbc_sha_ciphers_enabled"},
		"TlsEcdheRsaWithAes128CbcShaCiphersEnabled": ubx.FieldSpec{WireName: "tls_ecdhe_rsa_with_aes128_cbc_sha_ciphers_enabled"},
		"TlsEcdheRsaWithAes256CbcShaCiphersEnabled": ubx.FieldSpec{WireName: "tls_ecdhe_rsa_with_aes256_cbc_sha_ciphers_enabled"},
		"TlsRsaWithAes128CbcSha256CiphersEnabled": ubx.FieldSpec{WireName: "tls_rsa_with_aes128_cbc_sha256_ciphers_enabled"},
		"TlsRsaWithAes128CbcShaCiphersEnabled": ubx.FieldSpec{WireName: "tls_rsa_with_aes128_cbc_sha_ciphers_enabled"},
		"TlsRsaWithAes128GcmSha256CiphersEnabled": ubx.FieldSpec{WireName: "tls_rsa_with_aes128_gcm_sha256_ciphers_enabled"},
		"TlsRsaWithAes256CbcSha256CiphersEnabled": ubx.FieldSpec{WireName: "tls_rsa_with_aes256_cbc_sha256_ciphers_enabled"},
		"TlsRsaWithAes256CbcShaCiphersEnabled": ubx.FieldSpec{WireName: "tls_rsa_with_aes256_cbc_sha_ciphers_enabled"},
		"TlsRsaWithAes256GcmSha384CiphersEnabled": ubx.FieldSpec{WireName: "tls_rsa_with_aes256_gcm_sha384_ciphers_enabled"},
		"TripleDesCiphersEnabled": ubx.FieldSpec{WireName: "triple_des_ciphers_enabled"},
	}

var Management_SignInFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
	}

var Management_SignUp_TermsOfServiceFields = ubx.FieldMap{
		"ConsentRequired": ubx.FieldSpec{WireName: "consent_required"},
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"Text": ubx.FieldSpec{WireName: "text"},
	}

var Management_SignUpFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"TermsOfService": ubx.FieldSpec{
			WireName: "terms_of_service",
			Kind: "list",
			Fields: Management_SignUp_TermsOfServiceFields,
		},
	}

var Management_TenantAccessFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"PrimaryKey": ubx.FieldSpec{WireName: "primary_key"},
		"SecondaryKey": ubx.FieldSpec{WireName: "secondary_key"},
		"TenantId": ubx.FieldSpec{WireName: "tenant_id"},
	}

var Management_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Read": ubx.FieldSpec{WireName: "read"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

type ManagementConfig struct {
	ClientCertificateEnabled any
	GatewayDisabled any
	Id any
	Location any
	MinApiVersion any
	Name any
	NotificationSenderEmail any
	PublicIpAddressId any
	PublicNetworkAccessEnabled any
	PublisherEmail any
	PublisherName any
	ResourceGroupName any
	SkuName any
	Tags any
	VirtualNetworkType any
	Zones any
	AdditionalLocation any
	Certificate any
	Delegation any
	HostnameConfiguration any
	Identity any
	Protocols any
	Security any
	SignIn any
	SignUp any
	TenantAccess any
	Timeouts any
	VirtualNetworkConfiguration any
}

var Management = ubx.ResourceBinding{
	WireType: "azurerm_api_management",
	Fields: ubx.FieldMap{
		"ClientCertificateEnabled": ubx.FieldSpec{WireName: "client_certificate_enabled"},
		"GatewayDisabled": ubx.FieldSpec{WireName: "gateway_disabled"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"Location": ubx.FieldSpec{WireName: "location"},
		"MinApiVersion": ubx.FieldSpec{WireName: "min_api_version"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"NotificationSenderEmail": ubx.FieldSpec{WireName: "notification_sender_email"},
		"PublicIpAddressId": ubx.FieldSpec{WireName: "public_ip_address_id"},
		"PublicNetworkAccessEnabled": ubx.FieldSpec{WireName: "public_network_access_enabled"},
		"PublisherEmail": ubx.FieldSpec{WireName: "publisher_email"},
		"PublisherName": ubx.FieldSpec{WireName: "publisher_name"},
		"ResourceGroupName": ubx.FieldSpec{WireName: "resource_group_name"},
		"SkuName": ubx.FieldSpec{WireName: "sku_name"},
		"Tags": ubx.FieldSpec{WireName: "tags"},
		"VirtualNetworkType": ubx.FieldSpec{WireName: "virtual_network_type"},
		"Zones": ubx.FieldSpec{WireName: "zones"},
		"AdditionalLocation": ubx.FieldSpec{
			WireName: "additional_location",
			Kind: "list",
			Fields: Management_AdditionalLocationFields,
		},
		"Certificate": ubx.FieldSpec{
			WireName: "certificate",
			Kind: "list",
			Fields: Management_CertificateFields,
		},
		"Delegation": ubx.FieldSpec{
			WireName: "delegation",
			Kind: "list",
			Fields: Management_DelegationFields,
		},
		"HostnameConfiguration": ubx.FieldSpec{
			WireName: "hostname_configuration",
			Kind: "list",
			Fields: Management_HostnameConfigurationFields,
		},
		"Identity": ubx.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: Management_IdentityFields,
		},
		"Protocols": ubx.FieldSpec{
			WireName: "protocols",
			Kind: "list",
			Fields: Management_ProtocolsFields,
		},
		"Security": ubx.FieldSpec{
			WireName: "security",
			Kind: "list",
			Fields: Management_SecurityFields,
		},
		"SignIn": ubx.FieldSpec{
			WireName: "sign_in",
			Kind: "list",
			Fields: Management_SignInFields,
		},
		"SignUp": ubx.FieldSpec{
			WireName: "sign_up",
			Kind: "list",
			Fields: Management_SignUpFields,
		},
		"TenantAccess": ubx.FieldSpec{
			WireName: "tenant_access",
			Kind: "list",
			Fields: Management_TenantAccessFields,
		},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Management_TimeoutsFields,
		},
		"VirtualNetworkConfiguration": ubx.FieldSpec{
			WireName: "virtual_network_configuration",
			Kind: "list",
			Fields: Management_AdditionalLocation_VirtualNetworkConfigurationFields,
		},
	},
}
