// Code generated by `ubx sdk gen` from azure_postgresql_openapi_administrator_microsoft_entra. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface OpenapiAdministratorMicrosoftEntra_Properties {
  /** Object identifier of the Microsoft Entra principal. */
  objectId?: string | Computed<string>;
  /** Name of the Microsoft Entra principal. */
  principalName?: string | Computed<string>;
  /** Type of Microsoft Entra principal to which the server administrator is associated. */
  principalType?: string | Computed<string>;
  /** Identifier of the tenant in which the Microsoft Entra principal exists. */
  tenantId?: string | Computed<string>;
}

const OpenapiAdministratorMicrosoftEntra_PropertiesFields: FieldMap = {
  objectId: "object_id",
  principalName: "principal_name",
  principalType: "principal_type",
  tenantId: "tenant_id",
};

export interface OpenapiAdministratorMicrosoftEntraConfig {
  /** Properties of a server administrator associated to a Microsoft Entra principal. */
  properties?: OpenapiAdministratorMicrosoftEntra_Properties | Computed<OpenapiAdministratorMicrosoftEntra_Properties>;
}

export interface OpenapiAdministratorMicrosoftEntraAttrs {
  /** Properties of a server administrator associated to a Microsoft Entra principal. */
  properties: OpenapiAdministratorMicrosoftEntra_Properties;
}

export const OpenapiAdministratorMicrosoftEntra: ResourceBinding<OpenapiAdministratorMicrosoftEntraConfig, OpenapiAdministratorMicrosoftEntraAttrs> = {
  wireType: "azure_postgresql_openapi_administrator_microsoft_entra",
  fields: {
    properties: {
      wireName: "properties",
      kind: "object",
      fields: OpenapiAdministratorMicrosoftEntra_PropertiesFields,
    },
  },
};
