// Code generated by `ubx sdk gen` from azure_machinelearningservices_openapi_private_endpoint_connection. DO NOT EDIT.
package machinelearningservices

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpenapiPrivateEndpointConnection_Value_Identity_UserAssignedIdentities struct {
	ClientId    any
	PrincipalId any
}

type OpenapiPrivateEndpointConnection_Value_Identity struct {
	PrincipalId            any
	TenantId               any
	Type                   any
	UserAssignedIdentities any
}

type OpenapiPrivateEndpointConnection_Value_Properties_PrivateEndpoint struct {
	Id          any
	SubnetArmId any
}

type OpenapiPrivateEndpointConnection_Value_Properties_PrivateLinkServiceConnectionState struct {
	ActionsRequired any
	Description     any
	Status          any
}

type OpenapiPrivateEndpointConnection_Value_Properties struct {
	PrivateEndpoint                   any
	PrivateLinkServiceConnectionState any
	ProvisioningState                 any
}

type OpenapiPrivateEndpointConnection_Value_Sku struct {
	Capacity any
	Family   any
	Name     any
	Size     any
	Tier     any
}

type OpenapiPrivateEndpointConnection_Value struct {
	Identity   any
	Location   any
	Properties any
	Sku        any
	Tags       any
}

type OpenapiPrivateEndpointConnectionConfig struct {
	WorkspaceName any
}

type OpenapiPrivateEndpointConnectionAttrs struct {
	NextLink any
	// Array of private endpoint connections
	Value         any
	WorkspaceName any
}

var OpenapiPrivateEndpointConnection = ubx.DataSourceBinding{
	WireType: "azure_machinelearningservices_openapi_private_endpoint_connection",
	Fields: ubx.FieldMap{
		"WorkspaceName": ubx.FieldSpec{WireName: "workspace_name"},
	},
}
