// Code generated by `ubx sdk gen` from azurerm_iotcentral_application_network_rule_set. DO NOT EDIT.
package iotcentral

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ApplicationNetworkRuleSet_IpRule struct {
	IpMask any
	Name any
}

type ApplicationNetworkRuleSet_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ApplicationNetworkRuleSet_IpRuleFields = ubx.FieldMap{
		"IpMask": ubx.FieldSpec{WireName: "ip_mask"},
		"Name": ubx.FieldSpec{WireName: "name"},
	}

var ApplicationNetworkRuleSet_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Read": ubx.FieldSpec{WireName: "read"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

type ApplicationNetworkRuleSetConfig struct {
	ApplyToDevice any
	DefaultAction any
	Id any
	IotcentralApplicationId any
	IpRule any
	Timeouts any
}

var ApplicationNetworkRuleSet = ubx.ResourceBinding{
	WireType: "azurerm_iotcentral_application_network_rule_set",
	Fields: ubx.FieldMap{
		"ApplyToDevice": ubx.FieldSpec{WireName: "apply_to_device"},
		"DefaultAction": ubx.FieldSpec{WireName: "default_action"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"IotcentralApplicationId": ubx.FieldSpec{WireName: "iotcentral_application_id"},
		"IpRule": ubx.FieldSpec{
			WireName: "ip_rule",
			Kind: "list",
			Fields: ApplicationNetworkRuleSet_IpRuleFields,
		},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ApplicationNetworkRuleSet_TimeoutsFields,
		},
	},
}
