// Code generated by `ubx sdk gen` from azure_web_openapi_sku_info_list. DO NOT EDIT.
package web

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpenapiSkuInfoList_Value_Capacity struct {
	Default        any
	ElasticMaximum any
	Maximum        any
	Minimum        any
	ScaleType      any
}

type OpenapiSkuInfoList_Value_Sku_Capabilities struct {
	Name   any
	Reason any
	Value  any
}

type OpenapiSkuInfoList_Value_Sku struct {
	Capabilities any
	Capacity     any
	Family       any
	Locations    any
	Name         any
	Size         any
	SkuCapacity  any
	Tier         any
}

type OpenapiSkuInfoList_Value struct {
	Capacity     any
	ResourceType any
	Sku          any
}

type OpenapiSkuInfoListConfig struct {
	Name any
}

type OpenapiSkuInfoListAttrs struct {
	Name any
	// The link to the next page of items
	NextLink any
	// The SkuInfo items on this page
	Value any
}

var OpenapiSkuInfoList = ubx.DataSourceBinding{
	WireType: "azure_web_openapi_sku_info_list",
	Fields: ubx.FieldMap{
		"Name": ubx.FieldSpec{WireName: "name"},
	},
}
