// Code generated by `ubx sdk gen` from azure_network_networkgateway_virtual_network_gateway_connection_list_entity. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_GatewayCustomBgpIpAddresses {
  customBgpIpAddress?: string | Computed<string>;
  ipConfigurationId?: string | Computed<string>;
}

export interface NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_IpsecPolicies {
  dhGroup?: string | Computed<string>;
  ikeEncryption?: string | Computed<string>;
  ikeIntegrity?: string | Computed<string>;
  ipsecEncryption?: string | Computed<string>;
  ipsecIntegrity?: string | Computed<string>;
  pfsGroup?: string | Computed<string>;
  saDataSizeKilobytes?: number | Computed<number>;
  saLifeTimeSeconds?: number | Computed<number>;
}

export interface NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2 {
  id?: string | Computed<string>;
}

export interface NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_RoutingConfiguration_PropagatedRouteTables {
  ids?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2[] | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2[]>;
  labels?: string[] | Computed<string[]>;
}

export interface NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_RoutingConfiguration_VnetRoutes_StaticRoutes {
  addressPrefixes?: string[] | Computed<string[]>;
  name?: string | Computed<string>;
  nextHopIpAddress?: string | Computed<string>;
}

export interface NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_RoutingConfiguration_VnetRoutes_StaticRoutesConfig {
  propagateStaticRoutes?: boolean | Computed<boolean>;
  vnetLocalRouteOverrideCriteria?: string | Computed<string>;
}

export interface NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_RoutingConfiguration_VnetRoutes {
  bgpConnections?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2[] | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2[]>;
  staticRoutes?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_RoutingConfiguration_VnetRoutes_StaticRoutes[] | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_RoutingConfiguration_VnetRoutes_StaticRoutes[]>;
  staticRoutesConfig?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_RoutingConfiguration_VnetRoutes_StaticRoutesConfig | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_RoutingConfiguration_VnetRoutes_StaticRoutesConfig>;
}

export interface NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_RoutingConfiguration {
  associatedRouteTable?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2 | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2>;
  inboundRouteMap?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2 | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2>;
  outboundRouteMap?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2 | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2>;
  propagatedRouteTables?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_RoutingConfiguration_PropagatedRouteTables | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_RoutingConfiguration_PropagatedRouteTables>;
  vnetRoutes?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_RoutingConfiguration_VnetRoutes | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_RoutingConfiguration_VnetRoutes>;
}

export interface NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_TrafficSelectorPolicies {
  localAddressRanges?: string[] | Computed<string[]>;
  remoteAddressRanges?: string[] | Computed<string[]>;
}

export interface NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_TunnelConnectionStatus {
  connectionStatus?: string | Computed<string>;
  egressBytesTransferred?: number | Computed<number>;
  ingressBytesTransferred?: number | Computed<number>;
  lastConnectionEstablishedUtcTime?: string | Computed<string>;
  tunnel?: string | Computed<string>;
}

export interface NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties {
  authorizationKey?: string | Computed<string>;
  connectionMode?: string | Computed<string>;
  connectionProtocol?: string | Computed<string>;
  connectionStatus?: string | Computed<string>;
  connectionType?: string | Computed<string>;
  egressBytesTransferred?: number | Computed<number>;
  enableBgp?: boolean | Computed<boolean>;
  enablePrivateLinkFastPath?: boolean | Computed<boolean>;
  expressRouteGatewayBypass?: boolean | Computed<boolean>;
  gatewayCustomBgpIpAddresses?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_GatewayCustomBgpIpAddresses[] | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_GatewayCustomBgpIpAddresses[]>;
  ingressBytesTransferred?: number | Computed<number>;
  ipsecPolicies?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_IpsecPolicies[] | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_IpsecPolicies[]>;
  localNetworkGateway2?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2 | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2>;
  peer?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2 | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2>;
  provisioningState?: string | Computed<string>;
  resourceGuid?: string | Computed<string>;
  routingConfiguration?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_RoutingConfiguration | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_RoutingConfiguration>;
  routingWeight?: number | Computed<number>;
  sharedKey?: string | Computed<string>;
  trafficSelectorPolicies?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_TrafficSelectorPolicies[] | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_TrafficSelectorPolicies[]>;
  tunnelConnectionStatus?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_TunnelConnectionStatus[] | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_TunnelConnectionStatus[]>;
  usePolicyBasedTrafficSelectors?: boolean | Computed<boolean>;
  virtualNetworkGateway1?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2 | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2>;
  virtualNetworkGateway2?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2 | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties_LocalNetworkGateway2>;
}

export interface NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value {
  etag?: string | Computed<string>;
  properties?: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties | Computed<NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value_Properties>;
}

export interface NetworkgatewayVirtualNetworkGatewayConnectionListEntityConfig {
  virtualNetworkGatewayName: string | Computed<string>;
}

export interface NetworkgatewayVirtualNetworkGatewayConnectionListEntityAttrs {
  /** The link to the next page of items */
  nextLink: string;
  /** The VirtualNetworkGatewayConnectionListEntity items on this page */
  value: NetworkgatewayVirtualNetworkGatewayConnectionListEntity_Value[];
  virtualNetworkGatewayName: string;
}

export const NetworkgatewayVirtualNetworkGatewayConnectionListEntity: DataSourceBinding<NetworkgatewayVirtualNetworkGatewayConnectionListEntityConfig, NetworkgatewayVirtualNetworkGatewayConnectionListEntityAttrs> = {
  wireType: "azure_network_networkgateway_virtual_network_gateway_connection_list_entity",
  fields: {
    virtualNetworkGatewayName: "virtual_network_gateway_name",
  },
};
