// Code generated by `ubx sdk gen` from azure_network_networkmanager_scope_connection. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface NetworkmanagerScopeConnection_Value_Properties {
  connectionState?: string | Computed<string>;
  description?: string | Computed<string>;
  resourceId?: string | Computed<string>;
  tenantId?: string | Computed<string>;
}

export interface NetworkmanagerScopeConnection_Value_SystemData {
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  createdByType?: string | Computed<string>;
  lastModifiedAt?: string | Computed<string>;
  lastModifiedBy?: string | Computed<string>;
  lastModifiedByType?: string | Computed<string>;
}

export interface NetworkmanagerScopeConnection_Value {
  etag?: string | Computed<string>;
  properties?: NetworkmanagerScopeConnection_Value_Properties | Computed<NetworkmanagerScopeConnection_Value_Properties>;
  systemData?: NetworkmanagerScopeConnection_Value_SystemData | Computed<NetworkmanagerScopeConnection_Value_SystemData>;
}

export interface NetworkmanagerScopeConnectionConfig {
  networkManagerName: string | Computed<string>;
}

export interface NetworkmanagerScopeConnectionAttrs {
  networkManagerName: string;
  /** The link to the next page of items */
  nextLink: string;
  /** The ScopeConnection items on this page */
  value: NetworkmanagerScopeConnection_Value[];
}

export const NetworkmanagerScopeConnection: DataSourceBinding<NetworkmanagerScopeConnectionConfig, NetworkmanagerScopeConnectionAttrs> = {
  wireType: "azure_network_networkmanager_scope_connection",
  fields: {
    networkManagerName: "network_manager_name",
  },
};
