# Code generated by `ubx sdk gen` from azure_help_discovery_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class DiscoveryResponse_Value_Properties:
    description: Any = None
    required_parameter_sets: Any = None
    solution_id: Any = None
    solution_type: Any = None

@dataclasses.dataclass
class DiscoveryResponse_Value:
    properties: Any = None

@dataclasses.dataclass
class DiscoveryResponseConfig:
    api_version: Any = None
    scope: Any = None

@dataclasses.dataclass
class DiscoveryResponseAttrs:
    api_version: Any = None
    # The link used to get the next page of solution metadata.
    next_link: Any = None
    scope: Any = None
    # The list of solution metadata.
    value: Any = None

DiscoveryResponse = ubx.DataSourceBinding(
    wire_type="azure_help_discovery_response",
    fields={
        "api_version": ubx.FieldSpec(wire_name="api_version"),
        "scope": ubx.FieldSpec(wire_name="scope"),
    },
)
