# Code generated by `ubx sdk gen` from azure_oracle_openapi_db_system. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OpenapiDbSystem_Properties:
    # Password string.
    admin_password: Any = None
    # Database edition type enum.
    database_edition: Any = None
    # A valid Oracle Database version. For a list of supported versions, use the ListDbVersions operation.
    db_version: Any = None
    # The name of the pluggable database. The name must begin with an alphabetic character and can contain a maximum of thirty alphanumeric characters. Special characters are not permitted. Pluggable database should not be same as database name.
    pdb_name: Any = None

_OpenapiDbSystem_PropertiesFields = {
    "admin_password": ubx.FieldSpec(wire_name="admin_password"),
    "database_edition": ubx.FieldSpec(wire_name="database_edition"),
    "db_version": ubx.FieldSpec(wire_name="db_version"),
    "pdb_name": ubx.FieldSpec(wire_name="pdb_name"),
}

@dataclasses.dataclass
class OpenapiDbSystemConfig:
    # The geo-location where the resource lives
    location: Any = None
    # DbSystem resource model.
    properties: Any = None
    # Resource tags.
    tags: Any = None
    # The availability zones.
    zones: Any = None

@dataclasses.dataclass
class OpenapiDbSystemAttrs:
    # The geo-location where the resource lives
    location: Any = None
    # DbSystem resource model.
    properties: Any = None
    # Resource tags.
    tags: Any = None
    # The availability zones.
    zones: Any = None

OpenapiDbSystem = ubx.ResourceBinding(
    wire_type="azure_oracle_openapi_db_system",
    fields={
        "location": ubx.FieldSpec(wire_name="location"),
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_OpenapiDbSystem_PropertiesFields,
        ),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "zones": ubx.FieldSpec(wire_name="zones"),
    },
)
