// Code generated by `ubx sdk gen` from azure_apimanagement_apimpolicies_service. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ApimpoliciesService_Value_Properties {
  format?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface ApimpoliciesService_Value {
  properties?: ApimpoliciesService_Value_Properties | Computed<ApimpoliciesService_Value_Properties>;
}

export interface ApimpoliciesServiceConfig {
}

export interface ApimpoliciesServiceAttrs {
  /** Total record count number. */
  count: number;
  /** Next page link if any. */
  nextLink: string;
  /** Policy Contract value. */
  value: ApimpoliciesService_Value[];
}

export const ApimpoliciesService: DataSourceBinding<ApimpoliciesServiceConfig, ApimpoliciesServiceAttrs> = {
  wireType: "azure_apimanagement_apimpolicies_service",
  fields: {
  },
};
