// Code generated by `ubx sdk gen` from azure_securityinsights_openapi_alert_rule_templates_list. DO NOT EDIT.
package securityinsights

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpenapiAlertRuleTemplatesList_Value struct {
	Kind any
}

type OpenapiAlertRuleTemplatesListConfig struct {
	WorkspaceName any
}

type OpenapiAlertRuleTemplatesListAttrs struct {
	// The link to the next page of items
	NextLink any
	// The AlertRuleTemplate items on this page
	Value any
	WorkspaceName any
}

var OpenapiAlertRuleTemplatesList = ubx.DataSourceBinding{
	WireType: "azure_securityinsights_openapi_alert_rule_templates_list",
	Fields: ubx.FieldMap{
		"WorkspaceName": ubx.FieldSpec{WireName: "workspace_name"},
	},
}
