// Code generated by `ubx sdk gen` from azure_securityinsights_openapi_security_mlanalytics_setting. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface OpenapiSecurityMlanalyticsSetting_Value {
  etag?: string | Computed<string>;
  kind?: string | Computed<string>;
}

export interface OpenapiSecurityMlanalyticsSettingConfig {
  workspaceName: string | Computed<string>;
}

export interface OpenapiSecurityMlanalyticsSettingAttrs {
  /** The link to the next page of items */
  nextLink: string;
  /** The SecurityMLAnalyticsSetting items on this page */
  value: OpenapiSecurityMlanalyticsSetting_Value[];
  workspaceName: string;
}

export const OpenapiSecurityMlanalyticsSetting: DataSourceBinding<OpenapiSecurityMlanalyticsSettingConfig, OpenapiSecurityMlanalyticsSettingAttrs> = {
  wireType: "azure_securityinsights_openapi_security_mlanalytics_setting",
  fields: {
    workspaceName: "workspace_name",
  },
};
