// Code generated by `ubx sdk gen` from azure_securityinsights_openapi_product_template_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface OpenapiProductTemplateList_Value_Properties_Author {
  email?: string | Computed<string>;
  link?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface OpenapiProductTemplateList_Value_Properties_Categories {
  domains?: string[] | Computed<string[]>;
  verticals?: string[] | Computed<string[]>;
}

export interface OpenapiProductTemplateList_Value_Properties_Dependencies_Criteria {
}

export interface OpenapiProductTemplateList_Value_Properties_Dependencies {
  contentId?: string | Computed<string>;
  criteria?: OpenapiProductTemplateList_Value_Properties_Dependencies_Criteria[] | Computed<OpenapiProductTemplateList_Value_Properties_Dependencies_Criteria[]>;
  kind?: string | Computed<string>;
  name?: string | Computed<string>;
  operator?: string | Computed<string>;
  version?: string | Computed<string>;
}

export interface OpenapiProductTemplateList_Value_Properties_Source {
  kind?: string | Computed<string>;
  name?: string | Computed<string>;
  sourceId?: string | Computed<string>;
}

export interface OpenapiProductTemplateList_Value_Properties_Support {
  email?: string | Computed<string>;
  link?: string | Computed<string>;
  name?: string | Computed<string>;
  tier?: string | Computed<string>;
}

export interface OpenapiProductTemplateList_Value_Properties {
  author?: OpenapiProductTemplateList_Value_Properties_Author | Computed<OpenapiProductTemplateList_Value_Properties_Author>;
  categories?: OpenapiProductTemplateList_Value_Properties_Categories | Computed<OpenapiProductTemplateList_Value_Properties_Categories>;
  contentId?: string | Computed<string>;
  contentKind?: string | Computed<string>;
  contentProductId?: string | Computed<string>;
  contentSchemaVersion?: string | Computed<string>;
  customVersion?: string | Computed<string>;
  dependencies?: OpenapiProductTemplateList_Value_Properties_Dependencies | Computed<OpenapiProductTemplateList_Value_Properties_Dependencies>;
  displayName?: string | Computed<string>;
  firstPublishDate?: string | Computed<string>;
  icon?: string | Computed<string>;
  isDeprecated?: string | Computed<string>;
  lastPublishDate?: string | Computed<string>;
  packageId?: string | Computed<string>;
  packageKind?: string | Computed<string>;
  packageName?: string | Computed<string>;
  packageVersion?: string | Computed<string>;
  packagedContent?: unknown | Computed<unknown>;
  previewImages?: string[] | Computed<string[]>;
  previewImagesDark?: string[] | Computed<string[]>;
  providers?: string[] | Computed<string[]>;
  source?: OpenapiProductTemplateList_Value_Properties_Source | Computed<OpenapiProductTemplateList_Value_Properties_Source>;
  support?: OpenapiProductTemplateList_Value_Properties_Support | Computed<OpenapiProductTemplateList_Value_Properties_Support>;
  threatAnalysisTactics?: string[] | Computed<string[]>;
  threatAnalysisTechniques?: string[] | Computed<string[]>;
  version?: string | Computed<string>;
}

export interface OpenapiProductTemplateList_Value {
  etag?: string | Computed<string>;
  properties?: OpenapiProductTemplateList_Value_Properties | Computed<OpenapiProductTemplateList_Value_Properties>;
}

export interface OpenapiProductTemplateListConfig {
  workspaceName: string | Computed<string>;
}

export interface OpenapiProductTemplateListAttrs {
  /** The link to the next page of items */
  nextLink: string;
  /** The ProductTemplateModel items on this page */
  value: OpenapiProductTemplateList_Value[];
  workspaceName: string;
}

export const OpenapiProductTemplateList: DataSourceBinding<OpenapiProductTemplateListConfig, OpenapiProductTemplateListAttrs> = {
  wireType: "azure_securityinsights_openapi_product_template_list",
  fields: {
    workspaceName: "workspace_name",
  },
};
