# Code generated by `ubx sdk gen` from azure_apimanagement_apimtags_operation_link. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ApimtagsOperationLink_Properties:
    # Tag name.
    display_name: Any = None

_ApimtagsOperationLink_PropertiesFields = {
    "display_name": ubx.FieldSpec(wire_name="display_name"),
}

@dataclasses.dataclass
class ApimtagsOperationLinkConfig:
    # Tag contract Properties.
    properties: Any = None

@dataclasses.dataclass
class ApimtagsOperationLinkAttrs:
    # Tag contract Properties.
    properties: Any = None

ApimtagsOperationLink = ubx.ResourceBinding(
    wire_type="azure_apimanagement_apimtags_operation_link",
    fields={
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_ApimtagsOperationLink_PropertiesFields,
        ),
    },
)
