# Code generated by `ubx sdk gen` from azure_apimanagement_apimworkspaces_named_value_contract. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ApimworkspacesNamedValueContract_Value_Properties_KeyVault_LastStatus:
    code: Any = None
    message: Any = None
    time_stamp_utc: Any = None

@dataclasses.dataclass
class ApimworkspacesNamedValueContract_Value_Properties_KeyVault:
    last_status: Any = None

@dataclasses.dataclass
class ApimworkspacesNamedValueContract_Value_Properties:
    display_name: Any = None
    key_vault: Any = None
    provisioning_state: Any = None
    value: Any = None

@dataclasses.dataclass
class ApimworkspacesNamedValueContract_Value:
    properties: Any = None

@dataclasses.dataclass
class ApimworkspacesNamedValueContractConfig:
    is_key_vault_refresh_failed: Any = None

@dataclasses.dataclass
class ApimworkspacesNamedValueContractAttrs:
    # Total record count number across all pages.
    count: Any = None
    is_key_vault_refresh_failed: Any = None
    # Next page link if any.
    next_link: Any = None
    # Page values.
    value: Any = None

ApimworkspacesNamedValueContract = ubx.DataSourceBinding(
    wire_type="azure_apimanagement_apimworkspaces_named_value_contract",
    fields={
        "is_key_vault_refresh_failed": ubx.FieldSpec(wire_name="is_key_vault_refresh_failed"),
    },
)
