# Code generated by `ubx sdk gen` from azure_apimanagement_apimloggers_logger_contract. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ApimloggersLoggerContract_Value_Properties:
    credentials: Any = None
    description: Any = None
    is_buffered: Any = None
    logger_type: Any = None
    resource_id: Any = None

@dataclasses.dataclass
class ApimloggersLoggerContract_Value:
    properties: Any = None

@dataclasses.dataclass
class ApimloggersLoggerContractConfig:
    pass

@dataclasses.dataclass
class ApimloggersLoggerContractAttrs:
    # Total record count number across all pages.
    count: Any = None
    # Next page link if any.
    next_link: Any = None
    # Logger values.
    value: Any = None

ApimloggersLoggerContract = ubx.DataSourceBinding(
    wire_type="azure_apimanagement_apimloggers_logger_contract",
    fields={
    },
)
