// Code generated by `ubx sdk gen` from azure_healthcareapis_healthcare_apis_iot_fhir_destination. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface HealthcareApisIotFhirDestination_Properties_FhirMapping {
  /** The mapping. */
  content?: unknown | Computed<unknown>;
}

export interface HealthcareApisIotFhirDestination_Properties {
  /** The mapping content. */
  fhirMapping: HealthcareApisIotFhirDestination_Properties_FhirMapping | Computed<HealthcareApisIotFhirDestination_Properties_FhirMapping>;
  /** Fully qualified resource id of the FHIR service to connect to. */
  fhirServiceResourceId: string | Computed<string>;
  /** The type of IoT identity resolution to use with the destination. */
  resourceIdentityResolutionType: string | Computed<string>;
}

export interface HealthcareApisIotFhirDestination_SystemData {
  /** The timestamp of resource creation (UTC). */
  createdAt?: string | Computed<string>;
  /** The identity that created the resource. */
  createdBy?: string | Computed<string>;
  /** The type of identity that created the resource. */
  createdByType?: string | Computed<string>;
  /** The timestamp of resource last modification (UTC) */
  lastModifiedAt?: string | Computed<string>;
  /** The identity that last modified the resource. */
  lastModifiedBy?: string | Computed<string>;
  /** The type of identity that last modified the resource. */
  lastModifiedByType?: string | Computed<string>;
}

const HealthcareApisIotFhirDestination_Properties_FhirMappingFields: FieldMap = {
  content: "content",
};

const HealthcareApisIotFhirDestination_PropertiesFields: FieldMap = {
  fhirMapping: {
    wireName: "fhir_mapping",
    kind: "object",
    fields: HealthcareApisIotFhirDestination_Properties_FhirMappingFields,
  },
  fhirServiceResourceId: "fhir_service_resource_id",
  resourceIdentityResolutionType: "resource_identity_resolution_type",
};

export interface HealthcareApisIotFhirDestinationConfig {
  /** The resource location. */
  location?: string | Computed<string>;
  /** IoT Connector destination properties for an Azure FHIR service. */
  properties: HealthcareApisIotFhirDestination_Properties | Computed<HealthcareApisIotFhirDestination_Properties>;
}

export interface HealthcareApisIotFhirDestinationAttrs {
  /** The resource location. */
  location: string;
  /** IoT Connector destination properties for an Azure FHIR service. */
  properties: HealthcareApisIotFhirDestination_Properties;
  /** Metadata pertaining to creation and last modification of the resource. */
  systemData: HealthcareApisIotFhirDestination_SystemData;
}

export const HealthcareApisIotFhirDestination: ResourceBinding<HealthcareApisIotFhirDestinationConfig, HealthcareApisIotFhirDestinationAttrs> = {
  wireType: "azure_healthcareapis_healthcare_apis_iot_fhir_destination",
  fields: {
    location: "location",
    properties: {
      wireName: "properties",
      kind: "object",
      fields: HealthcareApisIotFhirDestination_PropertiesFields,
    },
  },
};
