// Code generated by `ubx sdk gen` from azurerm_automation_webhook. DO NOT EDIT.
package automation

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Webhook_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Webhook_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Read": ubx.FieldSpec{WireName: "read"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

type WebhookConfig struct {
	AutomationAccountName any
	Enabled any
	ExpiryTime any
	Id any
	Name any
	Parameters any
	ResourceGroupName any
	RunOnWorkerGroup any
	RunbookName any
	Uri any
	Timeouts any
}

var Webhook = ubx.ResourceBinding{
	WireType: "azurerm_automation_webhook",
	Fields: ubx.FieldMap{
		"AutomationAccountName": ubx.FieldSpec{WireName: "automation_account_name"},
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"ExpiryTime": ubx.FieldSpec{WireName: "expiry_time"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Parameters": ubx.FieldSpec{WireName: "parameters"},
		"ResourceGroupName": ubx.FieldSpec{WireName: "resource_group_name"},
		"RunOnWorkerGroup": ubx.FieldSpec{WireName: "run_on_worker_group"},
		"RunbookName": ubx.FieldSpec{WireName: "runbook_name"},
		"Uri": ubx.FieldSpec{WireName: "uri"},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Webhook_TimeoutsFields,
		},
	},
}
