# Code generated by `ubx sdk gen` from azure_healthcareapis_healthcare_apis_dicom_service. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class HealthcareApisDicomService_Properties_AuthenticationConfiguration:
    # The audiences for the service
    audiences: Any = None
    # The authority url for the service
    authority: Any = None

@dataclasses.dataclass
class HealthcareApisDicomService_Properties_CorsConfiguration:
    # If credentials are allowed via CORS.
    allow_credentials: Any = None
    # The headers to be allowed via CORS.
    headers: Any = None
    # The max age to be allowed via CORS.
    max_age: Any = None
    # The methods to be allowed via CORS.
    methods: Any = None
    # The origins to be allowed via CORS.
    origins: Any = None

@dataclasses.dataclass
class HealthcareApisDicomService_Properties_Encryption_CustomerManagedKeyEncryption:
    # The URL of the key to use for encryption
    key_encryption_key_url: Any = None

@dataclasses.dataclass
class HealthcareApisDicomService_Properties_Encryption:
    # The encryption settings for the customer-managed key
    customer_managed_key_encryption: Any = None

@dataclasses.dataclass
class HealthcareApisDicomService_Properties_PrivateEndpointConnections_Properties_PrivateEndpoint:
    id: Any = None

@dataclasses.dataclass
class HealthcareApisDicomService_Properties_PrivateEndpointConnections_Properties_PrivateLinkServiceConnectionState:
    actions_required: Any = None
    description: Any = None
    status: Any = None

@dataclasses.dataclass
class HealthcareApisDicomService_Properties_PrivateEndpointConnections_Properties:
    private_endpoint: Any = None
    private_link_service_connection_state: Any = None
    provisioning_state: Any = None

@dataclasses.dataclass
class HealthcareApisDicomService_Properties_PrivateEndpointConnections:
    properties: Any = None

@dataclasses.dataclass
class HealthcareApisDicomService_Properties_StorageConfiguration:
    # The filesystem name of connected storage account.
    file_system_name: Any = None
    # The resource id of connected storage account.
    storage_resource_id: Any = None

@dataclasses.dataclass
class HealthcareApisDicomService_Properties:
    # Authentication configuration information
    authentication_configuration: Any = None
    # The settings for the CORS configuration of the service instance.
    cors_configuration: Any = None
    # Boolean to indicate if data partitions is enabled or not.
    enable_data_partitions: Any = None
    # Settings to encrypt a service
    encryption: Any = None
    # Indicates the current status of event support for the resource.
    event_state: Any = None
    # The list of private endpoint connections that are set up for this resource.
    private_endpoint_connections: Any = None
    # The provisioning state.
    provisioning_state: Any = None
    # Control permission for data plane traffic coming from public networks while private endpoint is enabled.
    public_network_access: Any = None
    # The url of the Dicom Services.
    service_url: Any = None
    # The configuration of connected storage
    storage_configuration: Any = None

@dataclasses.dataclass
class HealthcareApisDicomService_SystemData:
    # The timestamp of resource creation (UTC).
    created_at: Any = None
    # The identity that created the resource.
    created_by: Any = None
    # The type of identity that created the resource.
    created_by_type: Any = None
    # The timestamp of resource last modification (UTC)
    last_modified_at: Any = None
    # The identity that last modified the resource.
    last_modified_by: Any = None
    # The type of identity that last modified the resource.
    last_modified_by_type: Any = None

_HealthcareApisDicomService_Properties_AuthenticationConfigurationFields = {
    "audiences": ubx.FieldSpec(wire_name="audiences"),
    "authority": ubx.FieldSpec(wire_name="authority"),
}

_HealthcareApisDicomService_Properties_CorsConfigurationFields = {
    "allow_credentials": ubx.FieldSpec(wire_name="allow_credentials"),
    "headers": ubx.FieldSpec(wire_name="headers"),
    "max_age": ubx.FieldSpec(wire_name="max_age"),
    "methods": ubx.FieldSpec(wire_name="methods"),
    "origins": ubx.FieldSpec(wire_name="origins"),
}

_HealthcareApisDicomService_Properties_Encryption_CustomerManagedKeyEncryptionFields = {
    "key_encryption_key_url": ubx.FieldSpec(wire_name="key_encryption_key_url"),
}

_HealthcareApisDicomService_Properties_EncryptionFields = {
    "customer_managed_key_encryption": ubx.FieldSpec(
        wire_name="customer_managed_key_encryption",
        kind="object",
        fields=_HealthcareApisDicomService_Properties_Encryption_CustomerManagedKeyEncryptionFields,
    ),
}

_HealthcareApisDicomService_Properties_PrivateEndpointConnections_Properties_PrivateEndpointFields = {
    "id": ubx.FieldSpec(wire_name="id"),
}

_HealthcareApisDicomService_Properties_PrivateEndpointConnections_Properties_PrivateLinkServiceConnectionStateFields = {
    "actions_required": ubx.FieldSpec(wire_name="actions_required"),
    "description": ubx.FieldSpec(wire_name="description"),
    "status": ubx.FieldSpec(wire_name="status"),
}

_HealthcareApisDicomService_Properties_PrivateEndpointConnections_PropertiesFields = {
    "private_endpoint": ubx.FieldSpec(
        wire_name="private_endpoint",
        kind="object",
        fields=_HealthcareApisDicomService_Properties_PrivateEndpointConnections_Properties_PrivateEndpointFields,
    ),
    "private_link_service_connection_state": ubx.FieldSpec(
        wire_name="private_link_service_connection_state",
        kind="object",
        fields=_HealthcareApisDicomService_Properties_PrivateEndpointConnections_Properties_PrivateLinkServiceConnectionStateFields,
    ),
    "provisioning_state": ubx.FieldSpec(wire_name="provisioning_state"),
}

_HealthcareApisDicomService_Properties_PrivateEndpointConnectionsFields = {
    "properties": ubx.FieldSpec(
        wire_name="properties",
        kind="object",
        fields=_HealthcareApisDicomService_Properties_PrivateEndpointConnections_PropertiesFields,
    ),
}

_HealthcareApisDicomService_Properties_StorageConfigurationFields = {
    "file_system_name": ubx.FieldSpec(wire_name="file_system_name"),
    "storage_resource_id": ubx.FieldSpec(wire_name="storage_resource_id"),
}

_HealthcareApisDicomService_PropertiesFields = {
    "authentication_configuration": ubx.FieldSpec(
        wire_name="authentication_configuration",
        kind="object",
        fields=_HealthcareApisDicomService_Properties_AuthenticationConfigurationFields,
    ),
    "cors_configuration": ubx.FieldSpec(
        wire_name="cors_configuration",
        kind="object",
        fields=_HealthcareApisDicomService_Properties_CorsConfigurationFields,
    ),
    "enable_data_partitions": ubx.FieldSpec(wire_name="enable_data_partitions"),
    "encryption": ubx.FieldSpec(
        wire_name="encryption",
        kind="object",
        fields=_HealthcareApisDicomService_Properties_EncryptionFields,
    ),
    "event_state": ubx.FieldSpec(wire_name="event_state"),
    "private_endpoint_connections": ubx.FieldSpec(
        wire_name="private_endpoint_connections",
        kind="list",
        fields=_HealthcareApisDicomService_Properties_PrivateEndpointConnectionsFields,
    ),
    "provisioning_state": ubx.FieldSpec(wire_name="provisioning_state"),
    "public_network_access": ubx.FieldSpec(wire_name="public_network_access"),
    "service_url": ubx.FieldSpec(wire_name="service_url"),
    "storage_configuration": ubx.FieldSpec(
        wire_name="storage_configuration",
        kind="object",
        fields=_HealthcareApisDicomService_Properties_StorageConfigurationFields,
    ),
}

_HealthcareApisDicomService_SystemDataFields = {
    "created_at": ubx.FieldSpec(wire_name="created_at"),
    "created_by": ubx.FieldSpec(wire_name="created_by"),
    "created_by_type": ubx.FieldSpec(wire_name="created_by_type"),
    "last_modified_at": ubx.FieldSpec(wire_name="last_modified_at"),
    "last_modified_by": ubx.FieldSpec(wire_name="last_modified_by"),
    "last_modified_by_type": ubx.FieldSpec(wire_name="last_modified_by_type"),
}

@dataclasses.dataclass
class HealthcareApisDicomServiceConfig:
    # Dicom Service properties.
    properties: Any = None
    # Metadata pertaining to creation and last modification of the resource.
    system_data: Any = None

@dataclasses.dataclass
class HealthcareApisDicomServiceAttrs:
    # Dicom Service properties.
    properties: Any = None
    # Metadata pertaining to creation and last modification of the resource.
    system_data: Any = None

HealthcareApisDicomService = ubx.ResourceBinding(
    wire_type="azure_healthcareapis_healthcare_apis_dicom_service",
    fields={
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_HealthcareApisDicomService_PropertiesFields,
        ),
        "system_data": ubx.FieldSpec(
            wire_name="system_data",
            kind="object",
            fields=_HealthcareApisDicomService_SystemDataFields,
        ),
    },
)
