// Code generated by `ubx sdk gen` from azure_ssh_public_key_resource. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface PublicKeyResource_Properties {
  /** SSH public key used to authenticate to a virtual machine through ssh. If this property is not initially provided when the resource is created, the publicKey property will be populated when generateKeyPair is called. If the public key is provided upon resource creation, the provided public key needs to be at least 2048-bit and in ssh-rsa format. */
  publicKey?: string | Computed<string>;
}

const PublicKeyResource_PropertiesFields: FieldMap = {
  publicKey: "public_key",
};

export interface PublicKeyResourceConfig {
  /** Properties of the SSH public key. */
  properties?: PublicKeyResource_Properties | Computed<PublicKeyResource_Properties>;
}

export interface PublicKeyResourceAttrs {
  /** Properties of the SSH public key. */
  properties: PublicKeyResource_Properties;
}

export const PublicKeyResource: ResourceBinding<PublicKeyResourceConfig, PublicKeyResourceAttrs> = {
  wireType: "azure_ssh_public_key_resource",
  fields: {
    properties: {
      wireName: "properties",
      kind: "object",
      fields: PublicKeyResource_PropertiesFields,
    },
  },
};
