// Code generated by `ubx sdk gen` from azure_logic_integration_account_agreement. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_AcknowledgementConnectionSettings {
  /** Indicates whether to ignore mismatch in certificate name. */
  ignoreCertificateNameMismatch: boolean | Computed<boolean>;
  /** Indicates whether to keep the connection alive. */
  keepHttpConnectionAlive: boolean | Computed<boolean>;
  /** Indicates whether to support HTTP status code 'CONTINUE'. */
  supportHttpStatusCodeContinue: boolean | Computed<boolean>;
  /** Indicates whether to unfold the HTTP headers. */
  unfoldHttpHeaders: boolean | Computed<boolean>;
}

export interface IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_EnvelopeSettings {
  /** The value indicating whether to auto generate file name. */
  autogenerateFileName: boolean | Computed<boolean>;
  /** The template for file name. */
  fileNameTemplate: string | Computed<string>;
  /** The message content type. */
  messageContentType: string | Computed<string>;
  /** The value indicating whether to suspend message on file name generation error. */
  suspendMessageOnFileNameGenerationError: boolean | Computed<boolean>;
  /** The value indicating whether to transmit file name in mime header. */
  transmitFileNameInMimeHeader: boolean | Computed<boolean>;
}

export interface IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_ErrorSettings {
  /** The value indicating whether to resend message If MDN is not received. */
  resendIfMdnnotReceived: boolean | Computed<boolean>;
  /** The value indicating whether to suspend duplicate message. */
  suspendDuplicateMessage: boolean | Computed<boolean>;
}

export interface IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_MdnSettings {
  /** The disposition notification to header value. */
  dispositionNotificationTo?: string | Computed<string>;
  /** The MDN text. */
  mdnText?: string | Computed<string>;
  /** The signing or hashing algorithm. */
  micHashingAlgorithm: string | Computed<string>;
  /** The value indicating whether to send or request a MDN. */
  needMdn: boolean | Computed<boolean>;
  /** The receipt delivery URL. */
  receiptDeliveryUrl?: string | Computed<string>;
  /** The value indicating whether to send inbound MDN to message box. */
  sendInboundMdntoMessageBox: boolean | Computed<boolean>;
  /** The value indicating whether to send the asynchronous MDN. */
  sendMdnasynchronously: boolean | Computed<boolean>;
  /** The value indicating whether the MDN needs to be signed or not. */
  signMdn: boolean | Computed<boolean>;
  /** The value indicating whether to sign the outbound MDN if optional. */
  signOutboundMdnifOptional: boolean | Computed<boolean>;
}

export interface IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_SecuritySettings {
  /** The value indicating whether to enable NRR for inbound decoded messages. */
  enableNrrforInboundDecodedMessages: boolean | Computed<boolean>;
  /** The value indicating whether to enable NRR for inbound encoded messages. */
  enableNrrforInboundEncodedMessages: boolean | Computed<boolean>;
  /** The value indicating whether to enable NRR for inbound MDN. */
  enableNrrforInboundMdn: boolean | Computed<boolean>;
  /** The value indicating whether to enable NRR for outbound decoded messages. */
  enableNrrforOutboundDecodedMessages: boolean | Computed<boolean>;
  /** The value indicating whether to enable NRR for outbound encoded messages. */
  enableNrrforOutboundEncodedMessages: boolean | Computed<boolean>;
  /** The value indicating whether to enable NRR for outbound MDN. */
  enableNrrforOutboundMdn: boolean | Computed<boolean>;
  /** The name of the encryption certificate. */
  encryptionCertificateName?: string | Computed<string>;
  /** The value indicating whether to send or request a MDN. */
  overrideGroupSigningCertificate: boolean | Computed<boolean>;
  /** The Sha2 algorithm format. Valid values are Sha2, ShaHashSize, ShaHyphenHashSize, Sha2UnderscoreHashSize. */
  sha2AlgorithmFormat?: string | Computed<string>;
  /** The name of the signing certificate. */
  signingCertificateName?: string | Computed<string>;
}

export interface IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_ValidationSettings {
  /** The value indicating whether to check for certificate revocation list on receive. */
  checkCertificateRevocationListOnReceive: boolean | Computed<boolean>;
  /** The value indicating whether to check for certificate revocation list on send. */
  checkCertificateRevocationListOnSend: boolean | Computed<boolean>;
  /** The value indicating whether to check for duplicate message. */
  checkDuplicateMessage: boolean | Computed<boolean>;
  /** The value indicating whether the message has to be compressed. */
  compressMessage: boolean | Computed<boolean>;
  /** The value indicating whether the message has to be encrypted. */
  encryptMessage: boolean | Computed<boolean>;
  /** The encryption algorithm. */
  encryptionAlgorithm: string | Computed<string>;
  /** The number of days to look back for duplicate interchange. */
  interchangeDuplicatesValidityDays: number | Computed<number>;
  /** The value indicating whether to override incoming message properties with those in agreement. */
  overrideMessageProperties: boolean | Computed<boolean>;
  /** The value indicating whether the message has to be signed. */
  signMessage: boolean | Computed<boolean>;
  /** The signing or hashing algorithm. */
  signingAlgorithm?: string | Computed<string>;
}

export interface IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings {
  /** The AS2 agreement acknowledgement connection settings. */
  acknowledgementConnectionSettings: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_AcknowledgementConnectionSettings | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_AcknowledgementConnectionSettings>;
  /** The AS2 agreement envelope settings. */
  envelopeSettings: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_EnvelopeSettings | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_EnvelopeSettings>;
  /** The AS2 agreement error settings. */
  errorSettings: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_ErrorSettings | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_ErrorSettings>;
  /** The AS2 agreement mdn settings. */
  mdnSettings: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_MdnSettings | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_MdnSettings>;
  /** The AS2 agreement message connection settings. */
  messageConnectionSettings: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_AcknowledgementConnectionSettings | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_AcknowledgementConnectionSettings>;
  /** The AS2 agreement security settings. */
  securitySettings: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_SecuritySettings | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_SecuritySettings>;
  /** The AS2 agreement validation settings. */
  validationSettings: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_ValidationSettings | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_ValidationSettings>;
}

export interface IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity {
  /** The business identity qualifier e.g. as2identity, ZZ, ZZZ, 31, 32 */
  qualifier: string | Computed<string>;
  /** The user defined business identity value. */
  value: string | Computed<string>;
}

export interface IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement {
  /** The AS2 agreement protocol settings. */
  protocolSettings: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings>;
  /** The integration account partner's business identity. */
  receiverBusinessIdentity: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity>;
  /** The integration account partner's business identity. */
  senderBusinessIdentity: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity>;
}

export interface IntegrationAccountAgreement_Properties_Content_AS2 {
  /** The integration account AS2 one-way agreement. */
  receiveAgreement: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement>;
  /** The integration account AS2 one-way agreement. */
  sendAgreement: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement>;
}

export interface IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_AcknowledgementSettings {
  /** The acknowledgement control number lower bound. */
  acknowledgementControlNumberLowerBound: number | Computed<number>;
  /** The acknowledgement control number prefix. */
  acknowledgementControlNumberPrefix?: string | Computed<string>;
  /** The acknowledgement control number suffix. */
  acknowledgementControlNumberSuffix?: string | Computed<string>;
  /** The acknowledgement control number upper bound. */
  acknowledgementControlNumberUpperBound: number | Computed<number>;
  /** The value indicating whether to batch functional acknowledgements. */
  batchFunctionalAcknowledgements: boolean | Computed<boolean>;
  /** The value indicating whether to batch the technical acknowledgements. */
  batchTechnicalAcknowledgements: boolean | Computed<boolean>;
  /** The value indicating whether functional acknowledgement is needed. */
  needFunctionalAcknowledgement: boolean | Computed<boolean>;
  /** The value indicating whether a loop is needed for valid messages. */
  needLoopForValidMessages: boolean | Computed<boolean>;
  /** The value indicating whether technical acknowledgement is needed. */
  needTechnicalAcknowledgement: boolean | Computed<boolean>;
  /** The value indicating whether to rollover acknowledgement control number. */
  rolloverAcknowledgementControlNumber: boolean | Computed<boolean>;
  /** The value indicating whether to send synchronous acknowledgement. */
  sendSynchronousAcknowledgement: boolean | Computed<boolean>;
}

export interface IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_EdifactDelimiterOverrides {
  /** The character separating individual data elements within a composite element. (AI-inferred) */
  componentSeparator?: number | Computed<number>;
  /** The character separating individual data elements within a segment. (AI-inferred) */
  dataElementSeparator?: number | Computed<number>;
  /** The character used as the decimal point in numeric values. (AI-inferred) */
  decimalPointIndicator?: string | Computed<string>;
  /** The code identifying the association responsible for this specific message type. (AI-inferred) */
  messageAssociationAssignedCode?: string | Computed<string>;
  /** The identifier for this message type. (AI-inferred) */
  messageId?: string | Computed<string>;
  /** The release number of this message definition. (AI-inferred) */
  messageRelease?: string | Computed<string>;
  /** The version number of this message definition. (AI-inferred) */
  messageVersion?: string | Computed<string>;
  /** The character marking a subsequent character as an escaped literal, rather than a delimiter. (AI-inferred) */
  releaseIndicator?: number | Computed<number>;
  /** The character separating repeated instances of a data element. (AI-inferred) */
  repetitionSeparator?: number | Computed<number>;
  /** The character marking the end of a segment. (AI-inferred) */
  segmentTerminator?: number | Computed<number>;
  /** An additional character appended after the segment terminator, e.g. a line break. (AI-inferred) */
  segmentTerminatorSuffix?: string | Computed<string>;
  /** The XML namespace this schema is defined in. (AI-inferred) */
  targetNamespace?: string | Computed<string>;
}

export interface IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_EnvelopeOverrides {
  /** The password used to authenticate this trading partner agreement's own application. (AI-inferred) */
  applicationPassword?: string | Computed<string>;
  /** The code identifying the association responsible for this message definition. (AI-inferred) */
  associationAssignedCode?: string | Computed<string>;
  /** The code identifying the standards agency governing this message definition. (AI-inferred) */
  controllingAgencyCode?: string | Computed<string>;
  /** The identifier for this X12 functional group. (AI-inferred) */
  functionalGroupId?: string | Computed<string>;
  /** The release number declared in this EDIFACT group header. (AI-inferred) */
  groupHeaderMessageRelease?: string | Computed<string>;
  /** The version number declared in this EDIFACT group header. (AI-inferred) */
  groupHeaderMessageVersion?: string | Computed<string>;
  /** The code identifying the association responsible for this specific message type. (AI-inferred) */
  messageAssociationAssignedCode?: string | Computed<string>;
  /** The identifier for this message type. (AI-inferred) */
  messageId?: string | Computed<string>;
  /** The release number of this message definition. (AI-inferred) */
  messageRelease?: string | Computed<string>;
  /** The version number of this message definition. (AI-inferred) */
  messageVersion?: string | Computed<string>;
  /** The identifier of the receiving trading partner's own application. (AI-inferred) */
  receiverApplicationId?: string | Computed<string>;
  /** The code qualifying the type of `receiver_application_id`. (AI-inferred) */
  receiverApplicationQualifier?: string | Computed<string>;
  /** The identifier of the sending trading partner's own application. (AI-inferred) */
  senderApplicationId?: string | Computed<string>;
  /** The code qualifying the type of `sender_application_id`. (AI-inferred) */
  senderApplicationQualifier?: string | Computed<string>;
  /** The XML namespace this schema is defined in. (AI-inferred) */
  targetNamespace?: string | Computed<string>;
}

export interface IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_EnvelopeSettings {
  /** The application reference id. */
  applicationReferenceId?: string | Computed<string>;
  /** The value indicating whether to apply delimiter string advice. */
  applyDelimiterStringAdvice: boolean | Computed<boolean>;
  /** The communication agreement id. */
  communicationAgreementId?: string | Computed<string>;
  /** The value indicating whether to create grouping segments. */
  createGroupingSegments: boolean | Computed<boolean>;
  /** The value indicating whether to enable default group headers. */
  enableDefaultGroupHeaders: boolean | Computed<boolean>;
  /** The functional group id. */
  functionalGroupId?: string | Computed<string>;
  /** The group application password. */
  groupApplicationPassword?: string | Computed<string>;
  /** The group application receiver id. */
  groupApplicationReceiverId?: string | Computed<string>;
  /** The group application receiver qualifier. */
  groupApplicationReceiverQualifier?: string | Computed<string>;
  /** The group application sender id. */
  groupApplicationSenderId?: string | Computed<string>;
  /** The group application sender qualifier. */
  groupApplicationSenderQualifier?: string | Computed<string>;
  /** The group association assigned code. */
  groupAssociationAssignedCode?: string | Computed<string>;
  /** The group control number lower bound. */
  groupControlNumberLowerBound: number | Computed<number>;
  /** The group control number prefix. */
  groupControlNumberPrefix?: string | Computed<string>;
  /** The group control number suffix. */
  groupControlNumberSuffix?: string | Computed<string>;
  /** The group control number upper bound. */
  groupControlNumberUpperBound: number | Computed<number>;
  /** The group controlling agency code. */
  groupControllingAgencyCode?: string | Computed<string>;
  /** The group message release. */
  groupMessageRelease?: string | Computed<string>;
  /** The group message version. */
  groupMessageVersion?: string | Computed<string>;
  /** The interchange control number lower bound. */
  interchangeControlNumberLowerBound: number | Computed<number>;
  /** The interchange control number prefix. */
  interchangeControlNumberPrefix?: string | Computed<string>;
  /** The interchange control number suffix. */
  interchangeControlNumberSuffix?: string | Computed<string>;
  /** The interchange control number upper bound. */
  interchangeControlNumberUpperBound: number | Computed<number>;
  /** The value indicating whether the message is a test interchange. */
  isTestInterchange: boolean | Computed<boolean>;
  /** The value indicating whether to overwrite existing transaction set control number. */
  overwriteExistingTransactionSetControlNumber: boolean | Computed<boolean>;
  /** The processing priority code. */
  processingPriorityCode?: string | Computed<string>;
  /** The receiver internal identification. */
  receiverInternalIdentification?: string | Computed<string>;
  /** The receiver internal sub identification. */
  receiverInternalSubIdentification?: string | Computed<string>;
  /** The receiver reverse routing address. */
  receiverReverseRoutingAddress?: string | Computed<string>;
  /** The recipient reference password qualifier. */
  recipientReferencePasswordQualifier?: string | Computed<string>;
  /** The recipient reference password value. */
  recipientReferencePasswordValue?: string | Computed<string>;
  /** The value indicating whether to rollover group control number. */
  rolloverGroupControlNumber: boolean | Computed<boolean>;
  /** The value indicating whether to rollover interchange control number. */
  rolloverInterchangeControlNumber: boolean | Computed<boolean>;
  /** The value indicating whether to rollover transaction set control number. */
  rolloverTransactionSetControlNumber: boolean | Computed<boolean>;
  /** The sender internal identification. */
  senderInternalIdentification?: string | Computed<string>;
  /** The sender internal sub identification. */
  senderInternalSubIdentification?: string | Computed<string>;
  /** The sender reverse routing address. */
  senderReverseRoutingAddress?: string | Computed<string>;
  /** The transaction set control number lower bound. */
  transactionSetControlNumberLowerBound: number | Computed<number>;
  /** The transaction set control number prefix. */
  transactionSetControlNumberPrefix?: string | Computed<string>;
  /** The transaction set control number suffix. */
  transactionSetControlNumberSuffix?: string | Computed<string>;
  /** The transaction set control number upper bound. */
  transactionSetControlNumberUpperBound: number | Computed<number>;
}

export interface IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_FramingSettings {
  /** The character encoding. */
  characterEncoding?: string | Computed<string>;
  /** The edifact character set. */
  characterSet: string | Computed<string>;
  /** The component separator. */
  componentSeparator: number | Computed<number>;
  /** The data element separator. */
  dataElementSeparator: number | Computed<number>;
  /** The edifact decimal indicator. */
  decimalPointIndicator: string | Computed<string>;
  /** The protocol version. */
  protocolVersion: number | Computed<number>;
  /** The release indicator. */
  releaseIndicator: number | Computed<number>;
  /** The repetition separator. */
  repetitionSeparator: number | Computed<number>;
  /** The segment terminator. */
  segmentTerminator: number | Computed<number>;
  /** The segment terminator suffix. */
  segmentTerminatorSuffix: string | Computed<string>;
  /** The service code list directory version. */
  serviceCodeListDirectoryVersion?: string | Computed<string>;
}

export interface IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilter {
  /** The message filter type. */
  messageFilterType: string | Computed<string>;
}

export interface IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilterList {
  /** The identifier for this message type. (AI-inferred) */
  messageId?: string | Computed<string>;
}

export interface IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ProcessingSettings {
  /** The value indicating whether to create empty xml tags for trailing separators. */
  createEmptyXmlTagsForTrailingSeparators: boolean | Computed<boolean>;
  /** The value indicating whether to mask security information. */
  maskSecurityInfo: boolean | Computed<boolean>;
  /** The value indicating whether to preserve interchange. */
  preserveInterchange: boolean | Computed<boolean>;
  /** The value indicating whether to suspend interchange on error. */
  suspendInterchangeOnError: boolean | Computed<boolean>;
  /** The value indicating whether to use dot as decimal separator. */
  useDotAsDecimalSeparator: boolean | Computed<boolean>;
}

export interface IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_SchemaReferences {
  /** The code identifying the association responsible for this message definition. (AI-inferred) */
  associationAssignedCode?: string | Computed<string>;
  /** The identifier for this message type. (AI-inferred) */
  messageId?: string | Computed<string>;
  /** The release number of this message definition. (AI-inferred) */
  messageRelease?: string | Computed<string>;
  /** The version number of this message definition. (AI-inferred) */
  messageVersion?: string | Computed<string>;
  /** The name of this schema. (AI-inferred) */
  schemaName?: string | Computed<string>;
  /** The identifier of the sending trading partner's own application. (AI-inferred) */
  senderApplicationId?: string | Computed<string>;
  /** The code qualifying the type of `sender_application_id`. (AI-inferred) */
  senderApplicationQualifier?: string | Computed<string>;
}

export interface IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ValidationOverrides {
  /** Whether leading/trailing spaces and leading zeroes are permitted in a value. (AI-inferred) */
  allowLeadingAndTrailingSpacesAndZeroes?: boolean | Computed<boolean>;
  /** Whether values are validated against the permitted character set. (AI-inferred) */
  enforceCharacterSet?: boolean | Computed<boolean>;
  /** The identifier for this message type. (AI-inferred) */
  messageId?: string | Computed<string>;
  /** How trailing, otherwise-empty separators at the end of a segment are handled. (AI-inferred) */
  trailingSeparatorPolicy?: string | Computed<string>;
  /** Whether leading/trailing spaces and leading zeroes are stripped from a value. (AI-inferred) */
  trimLeadingAndTrailingSpacesAndZeroes?: boolean | Computed<boolean>;
  /** Whether EDI data types are validated against the schema. (AI-inferred) */
  validateEditypes?: boolean | Computed<boolean>;
  /** Whether values are validated against their own declared XSD types. (AI-inferred) */
  validateXsdtypes?: boolean | Computed<boolean>;
}

export interface IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ValidationSettings {
  /** The value indicating whether to allow leading and trailing spaces and zeroes. */
  allowLeadingAndTrailingSpacesAndZeroes: boolean | Computed<boolean>;
  /** The value indicating whether to check for duplicate group control number. */
  checkDuplicateGroupControlNumber: boolean | Computed<boolean>;
  /** The value indicating whether to check for duplicate interchange control number. */
  checkDuplicateInterchangeControlNumber: boolean | Computed<boolean>;
  /** The value indicating whether to check for duplicate transaction set control number. */
  checkDuplicateTransactionSetControlNumber: boolean | Computed<boolean>;
  /** The validity period of interchange control number. */
  interchangeControlNumberValidityDays: number | Computed<number>;
  /** The trailing separator policy. */
  trailingSeparatorPolicy: string | Computed<string>;
  /** The value indicating whether to trim leading and trailing spaces and zeroes. */
  trimLeadingAndTrailingSpacesAndZeroes: boolean | Computed<boolean>;
  /** The value indicating whether to validate character set in the message. */
  validateCharacterSet: boolean | Computed<boolean>;
  /** The value indicating whether to Whether to validate EDI types. */
  validateEditypes: boolean | Computed<boolean>;
  /** The value indicating whether to Whether to validate XSD types. */
  validateXsdtypes: boolean | Computed<boolean>;
}

export interface IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings {
  /** The Edifact agreement acknowledgement settings. */
  acknowledgementSettings: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_AcknowledgementSettings | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_AcknowledgementSettings>;
  /** The EDIFACT delimiter override settings. */
  edifactDelimiterOverrides?: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_EdifactDelimiterOverrides[] | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_EdifactDelimiterOverrides[]>;
  /** The EDIFACT envelope override settings. */
  envelopeOverrides?: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_EnvelopeOverrides[] | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_EnvelopeOverrides[]>;
  /** The Edifact agreement envelope settings. */
  envelopeSettings: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_EnvelopeSettings | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_EnvelopeSettings>;
  /** The Edifact agreement framing settings. */
  framingSettings: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_FramingSettings | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_FramingSettings>;
  /** The Edifact message filter for odata query. */
  messageFilter: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilter | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilter>;
  /** The EDIFACT message filter list. */
  messageFilterList?: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilterList[] | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilterList[]>;
  /** The Edifact agreement protocol settings. */
  processingSettings: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ProcessingSettings | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ProcessingSettings>;
  /** The EDIFACT schema references. */
  schemaReferences: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_SchemaReferences[] | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_SchemaReferences[]>;
  /** The EDIFACT validation override settings. */
  validationOverrides?: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ValidationOverrides[] | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ValidationOverrides[]>;
  /** The Edifact agreement validation settings. */
  validationSettings: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ValidationSettings | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ValidationSettings>;
}

export interface IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement {
  /** The Edifact agreement protocol settings. */
  protocolSettings: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings>;
  /** The integration account partner's business identity. */
  receiverBusinessIdentity: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity>;
  /** The integration account partner's business identity. */
  senderBusinessIdentity: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity>;
}

export interface IntegrationAccountAgreement_Properties_Content_Edifact {
  /** The Edifact one way agreement. */
  receiveAgreement: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement>;
  /** The Edifact one way agreement. */
  sendAgreement: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement>;
}

export interface IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_AcknowledgementSettings {
  /** The acknowledgement control number lower bound. */
  acknowledgementControlNumberLowerBound: number | Computed<number>;
  /** The acknowledgement control number prefix. */
  acknowledgementControlNumberPrefix?: string | Computed<string>;
  /** The acknowledgement control number suffix. */
  acknowledgementControlNumberSuffix?: string | Computed<string>;
  /** The acknowledgement control number upper bound. */
  acknowledgementControlNumberUpperBound: number | Computed<number>;
  /** The value indicating whether to batch functional acknowledgements. */
  batchFunctionalAcknowledgements: boolean | Computed<boolean>;
  /** The value indicating whether to batch implementation acknowledgements. */
  batchImplementationAcknowledgements: boolean | Computed<boolean>;
  /** The value indicating whether to batch the technical acknowledgements. */
  batchTechnicalAcknowledgements: boolean | Computed<boolean>;
  /** The functional acknowledgement version. */
  functionalAcknowledgementVersion?: string | Computed<string>;
  /** The implementation acknowledgement version. */
  implementationAcknowledgementVersion?: string | Computed<string>;
  /** The value indicating whether functional acknowledgement is needed. */
  needFunctionalAcknowledgement: boolean | Computed<boolean>;
  /** The value indicating whether implementation acknowledgement is needed. */
  needImplementationAcknowledgement: boolean | Computed<boolean>;
  /** The value indicating whether a loop is needed for valid messages. */
  needLoopForValidMessages: boolean | Computed<boolean>;
  /** The value indicating whether technical acknowledgement is needed. */
  needTechnicalAcknowledgement: boolean | Computed<boolean>;
  /** The value indicating whether to rollover acknowledgement control number. */
  rolloverAcknowledgementControlNumber: boolean | Computed<boolean>;
  /** The value indicating whether to send synchronous acknowledgement. */
  sendSynchronousAcknowledgement: boolean | Computed<boolean>;
}

export interface IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_EnvelopeOverrides {
  /** The format dates are expressed in. (AI-inferred) */
  dateFormat?: string | Computed<string>;
  /** The code identifying the kind of transaction set(s) in this functional group. (AI-inferred) */
  functionalIdentifierCode?: string | Computed<string>;
  /** The version identifier declared in this message header. (AI-inferred) */
  headerVersion?: string | Computed<string>;
  /** The identifier for this message type. (AI-inferred) */
  messageId?: string | Computed<string>;
  /** The version of the underlying EDI protocol this agreement uses. (AI-inferred) */
  protocolVersion?: string | Computed<string>;
  /** The identifier of the receiving trading partner's own application. (AI-inferred) */
  receiverApplicationId?: string | Computed<string>;
  /** The code identifying the agency responsible for this message definition. (AI-inferred) */
  responsibleAgencyCode?: string | Computed<string>;
  /** The identifier of the sending trading partner's own application. (AI-inferred) */
  senderApplicationId?: string | Computed<string>;
  /** The XML namespace this schema is defined in. (AI-inferred) */
  targetNamespace?: string | Computed<string>;
  /** The format times are expressed in. (AI-inferred) */
  timeFormat?: string | Computed<string>;
}

export interface IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_EnvelopeSettings {
  /** The controls standards id. */
  controlStandardsId: number | Computed<number>;
  /** The control version number. */
  controlVersionNumber: string | Computed<string>;
  /** The value indicating whether to enable default group headers. */
  enableDefaultGroupHeaders: boolean | Computed<boolean>;
  /** The functional group id. */
  functionalGroupId?: string | Computed<string>;
  /** The group control number lower bound. */
  groupControlNumberLowerBound: number | Computed<number>;
  /** The group control number upper bound. */
  groupControlNumberUpperBound: number | Computed<number>;
  /** The group header agency code. */
  groupHeaderAgencyCode: string | Computed<string>;
  /** The x12 date format. */
  groupHeaderDateFormat: string | Computed<string>;
  /** The x12 time format. */
  groupHeaderTimeFormat: string | Computed<string>;
  /** The group header version. */
  groupHeaderVersion: string | Computed<string>;
  /** The interchange control number lower bound. */
  interchangeControlNumberLowerBound: number | Computed<number>;
  /** The interchange control number upper bound. */
  interchangeControlNumberUpperBound: number | Computed<number>;
  /** The value indicating whether to overwrite existing transaction set control number. */
  overwriteExistingTransactionSetControlNumber: boolean | Computed<boolean>;
  /** The receiver application id. */
  receiverApplicationId: string | Computed<string>;
  /** The value indicating whether to rollover group control number. */
  rolloverGroupControlNumber: boolean | Computed<boolean>;
  /** The value indicating whether to rollover interchange control number. */
  rolloverInterchangeControlNumber: boolean | Computed<boolean>;
  /** The value indicating whether to rollover transaction set control number. */
  rolloverTransactionSetControlNumber: boolean | Computed<boolean>;
  /** The sender application id. */
  senderApplicationId: string | Computed<string>;
  /** The transaction set control number lower bound. */
  transactionSetControlNumberLowerBound: number | Computed<number>;
  /** The transaction set control number prefix. */
  transactionSetControlNumberPrefix?: string | Computed<string>;
  /** The transaction set control number suffix. */
  transactionSetControlNumberSuffix?: string | Computed<string>;
  /** The transaction set control number upper bound. */
  transactionSetControlNumberUpperBound: number | Computed<number>;
  /** The usage indicator. */
  usageIndicator: string | Computed<string>;
  /** The value indicating whether to use control standards id as repetition character. */
  useControlStandardsIdAsRepetitionCharacter: boolean | Computed<boolean>;
}

export interface IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_FramingSettings {
  /** The X12 character set. */
  characterSet: string | Computed<string>;
  /** The component separator. */
  componentSeparator: number | Computed<number>;
  /** The data element separator. */
  dataElementSeparator: number | Computed<number>;
  /** The replacement character. */
  replaceCharacter: number | Computed<number>;
  /** The value indicating whether to replace separators in payload. */
  replaceSeparatorsInPayload: boolean | Computed<boolean>;
  /** The segment terminator. */
  segmentTerminator: number | Computed<number>;
  /** The segment terminator suffix. */
  segmentTerminatorSuffix: string | Computed<string>;
}

export interface IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_ProcessingSettings {
  /** The value indicating whether to convert numerical type to implied decimal. */
  convertImpliedDecimal: boolean | Computed<boolean>;
  /** The value indicating whether to create empty xml tags for trailing separators. */
  createEmptyXmlTagsForTrailingSeparators: boolean | Computed<boolean>;
  /** The value indicating whether to mask security information. */
  maskSecurityInfo: boolean | Computed<boolean>;
  /** The value indicating whether to preserve interchange. */
  preserveInterchange: boolean | Computed<boolean>;
  /** The value indicating whether to suspend interchange on error. */
  suspendInterchangeOnError: boolean | Computed<boolean>;
  /** The value indicating whether to use dot as decimal separator. */
  useDotAsDecimalSeparator: boolean | Computed<boolean>;
}

export interface IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_SchemaReferences {
  /** The identifier for this message type. (AI-inferred) */
  messageId?: string | Computed<string>;
  /** The name of this schema. (AI-inferred) */
  schemaName?: string | Computed<string>;
  /** The version of this schema. (AI-inferred) */
  schemaVersion?: string | Computed<string>;
  /** The identifier of the sending trading partner's own application. (AI-inferred) */
  senderApplicationId?: string | Computed<string>;
}

export interface IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_SecuritySettings {
  /** The authorization qualifier. */
  authorizationQualifier: string | Computed<string>;
  /** The authorization value. */
  authorizationValue?: string | Computed<string>;
  /** The password value. */
  passwordValue?: string | Computed<string>;
  /** The security qualifier. */
  securityQualifier: string | Computed<string>;
}

export interface IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_ValidationOverrides {
  /** Whether leading/trailing spaces and leading zeroes are permitted in a value. (AI-inferred) */
  allowLeadingAndTrailingSpacesAndZeroes?: boolean | Computed<boolean>;
  /** The identifier for this message type. (AI-inferred) */
  messageId?: string | Computed<string>;
  /** How trailing, otherwise-empty separators at the end of a segment are handled. (AI-inferred) */
  trailingSeparatorPolicy?: string | Computed<string>;
  /** Whether leading/trailing spaces and leading zeroes are stripped from a value. (AI-inferred) */
  trimLeadingAndTrailingSpacesAndZeroes?: boolean | Computed<boolean>;
  /** Whether values are validated against the permitted character set. (AI-inferred) */
  validateCharacterSet?: boolean | Computed<boolean>;
  /** Whether EDI data types are validated against the schema. (AI-inferred) */
  validateEditypes?: boolean | Computed<boolean>;
  /** Whether values are validated against their own declared XSD types. (AI-inferred) */
  validateXsdtypes?: boolean | Computed<boolean>;
}

export interface IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_X12DelimiterOverrides {
  /** The character separating individual data elements within a composite element. (AI-inferred) */
  componentSeparator?: number | Computed<number>;
  /** The character separating individual data elements within a segment. (AI-inferred) */
  dataElementSeparator?: number | Computed<number>;
  /** The identifier for this message type. (AI-inferred) */
  messageId?: string | Computed<string>;
  /** The version of the underlying EDI protocol this agreement uses. (AI-inferred) */
  protocolVersion?: string | Computed<string>;
  /** The character substituted in place of a disallowed one. (AI-inferred) */
  replaceCharacter?: number | Computed<number>;
  /** Whether delimiter characters appearing inside data values are replaced, to avoid ambiguity with the message's own structural delimiters. (AI-inferred) */
  replaceSeparatorsInPayload?: boolean | Computed<boolean>;
  /** The character marking the end of a segment. (AI-inferred) */
  segmentTerminator?: number | Computed<number>;
  /** An additional character appended after the segment terminator, e.g. a line break. (AI-inferred) */
  segmentTerminatorSuffix?: string | Computed<string>;
  /** The XML namespace this schema is defined in. (AI-inferred) */
  targetNamespace?: string | Computed<string>;
}

export interface IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings {
  /** The X12 agreement acknowledgement settings. */
  acknowledgementSettings: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_AcknowledgementSettings | Computed<IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_AcknowledgementSettings>;
  /** The X12 envelope override settings. */
  envelopeOverrides?: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_EnvelopeOverrides[] | Computed<IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_EnvelopeOverrides[]>;
  /** The X12 agreement envelope settings. */
  envelopeSettings: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_EnvelopeSettings | Computed<IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_EnvelopeSettings>;
  /** The X12 agreement framing settings. */
  framingSettings: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_FramingSettings | Computed<IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_FramingSettings>;
  /** The X12 message filter for odata query. */
  messageFilter: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilter | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilter>;
  /** The X12 message filter list. */
  messageFilterList?: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilterList[] | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilterList[]>;
  /** The X12 processing settings. */
  processingSettings: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_ProcessingSettings | Computed<IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_ProcessingSettings>;
  /** The X12 schema references. */
  schemaReferences: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_SchemaReferences[] | Computed<IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_SchemaReferences[]>;
  /** The X12 agreement security settings. */
  securitySettings: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_SecuritySettings | Computed<IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_SecuritySettings>;
  /** The X12 validation override settings. */
  validationOverrides?: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_ValidationOverrides[] | Computed<IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_ValidationOverrides[]>;
  /** The X12 agreement validation settings. */
  validationSettings: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ValidationSettings | Computed<IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ValidationSettings>;
  /** The X12 delimiter override settings. */
  x12DelimiterOverrides?: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_X12DelimiterOverrides[] | Computed<IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_X12DelimiterOverrides[]>;
}

export interface IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement {
  /** The X12 agreement protocol settings. */
  protocolSettings: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings | Computed<IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings>;
  /** The integration account partner's business identity. */
  receiverBusinessIdentity: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity>;
  /** The integration account partner's business identity. */
  senderBusinessIdentity: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity>;
}

export interface IntegrationAccountAgreement_Properties_Content_X12 {
  /** The X12 one-way agreement. */
  receiveAgreement: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement | Computed<IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement>;
  /** The X12 one-way agreement. */
  sendAgreement: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement | Computed<IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement>;
}

export interface IntegrationAccountAgreement_Properties_Content {
  /** The integration account AS2 agreement content. */
  aS2?: IntegrationAccountAgreement_Properties_Content_AS2 | Computed<IntegrationAccountAgreement_Properties_Content_AS2>;
  /** The Edifact agreement content. */
  edifact?: IntegrationAccountAgreement_Properties_Content_Edifact | Computed<IntegrationAccountAgreement_Properties_Content_Edifact>;
  /** The X12 agreement content. */
  x12?: IntegrationAccountAgreement_Properties_Content_X12 | Computed<IntegrationAccountAgreement_Properties_Content_X12>;
}

export interface IntegrationAccountAgreement_Properties {
  /** The agreement type. */
  agreementType: string | Computed<string>;
  /** The changed time. */
  changedTime?: string | Computed<string>;
  /** The integration account agreement content. */
  content: IntegrationAccountAgreement_Properties_Content | Computed<IntegrationAccountAgreement_Properties_Content>;
  /** The created time. */
  createdTime?: string | Computed<string>;
  /** The integration account partner's business identity. */
  guestIdentity: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity>;
  /** The integration account partner that is set as guest partner for this agreement. */
  guestPartner: string | Computed<string>;
  /** The integration account partner's business identity. */
  hostIdentity: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity | Computed<IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentity>;
  /** The integration account partner that is set as host partner for this agreement. */
  hostPartner: string | Computed<string>;
  /** The metadata. */
  metadata?: unknown | Computed<unknown>;
}

const IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_AcknowledgementConnectionSettingsFields: FieldMap = {
  ignoreCertificateNameMismatch: "ignore_certificate_name_mismatch",
  keepHttpConnectionAlive: "keep_http_connection_alive",
  supportHttpStatusCodeContinue: "support_http_status_code_continue",
  unfoldHttpHeaders: "unfold_http_headers",
};

const IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_EnvelopeSettingsFields: FieldMap = {
  autogenerateFileName: "autogenerate_file_name",
  fileNameTemplate: "file_name_template",
  messageContentType: "message_content_type",
  suspendMessageOnFileNameGenerationError: "suspend_message_on_file_name_generation_error",
  transmitFileNameInMimeHeader: "transmit_file_name_in_mime_header",
};

const IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_ErrorSettingsFields: FieldMap = {
  resendIfMdnnotReceived: "resend_if_mdnnot_received",
  suspendDuplicateMessage: "suspend_duplicate_message",
};

const IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_MdnSettingsFields: FieldMap = {
  dispositionNotificationTo: "disposition_notification_to",
  mdnText: "mdn_text",
  micHashingAlgorithm: "mic_hashing_algorithm",
  needMdn: "need_mdn",
  receiptDeliveryUrl: "receipt_delivery_url",
  sendInboundMdntoMessageBox: "send_inbound_mdnto_message_box",
  sendMdnasynchronously: "send_mdnasynchronously",
  signMdn: "sign_mdn",
  signOutboundMdnifOptional: "sign_outbound_mdnif_optional",
};

const IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_SecuritySettingsFields: FieldMap = {
  enableNrrforInboundDecodedMessages: "enable_nrrfor_inbound_decoded_messages",
  enableNrrforInboundEncodedMessages: "enable_nrrfor_inbound_encoded_messages",
  enableNrrforInboundMdn: "enable_nrrfor_inbound_mdn",
  enableNrrforOutboundDecodedMessages: "enable_nrrfor_outbound_decoded_messages",
  enableNrrforOutboundEncodedMessages: "enable_nrrfor_outbound_encoded_messages",
  enableNrrforOutboundMdn: "enable_nrrfor_outbound_mdn",
  encryptionCertificateName: "encryption_certificate_name",
  overrideGroupSigningCertificate: "override_group_signing_certificate",
  sha2AlgorithmFormat: "sha2_algorithm_format",
  signingCertificateName: "signing_certificate_name",
};

const IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_ValidationSettingsFields: FieldMap = {
  checkCertificateRevocationListOnReceive: "check_certificate_revocation_list_on_receive",
  checkCertificateRevocationListOnSend: "check_certificate_revocation_list_on_send",
  checkDuplicateMessage: "check_duplicate_message",
  compressMessage: "compress_message",
  encryptMessage: "encrypt_message",
  encryptionAlgorithm: "encryption_algorithm",
  interchangeDuplicatesValidityDays: "interchange_duplicates_validity_days",
  overrideMessageProperties: "override_message_properties",
  signMessage: "sign_message",
  signingAlgorithm: "signing_algorithm",
};

const IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettingsFields: FieldMap = {
  acknowledgementConnectionSettings: {
    wireName: "acknowledgement_connection_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_AcknowledgementConnectionSettingsFields,
  },
  envelopeSettings: {
    wireName: "envelope_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_EnvelopeSettingsFields,
  },
  errorSettings: {
    wireName: "error_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_ErrorSettingsFields,
  },
  mdnSettings: {
    wireName: "mdn_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_MdnSettingsFields,
  },
  messageConnectionSettings: {
    wireName: "message_connection_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_AcknowledgementConnectionSettingsFields,
  },
  securitySettings: {
    wireName: "security_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_SecuritySettingsFields,
  },
  validationSettings: {
    wireName: "validation_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettings_ValidationSettingsFields,
  },
};

const IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentityFields: FieldMap = {
  qualifier: "qualifier",
  value: "value",
};

const IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreementFields: FieldMap = {
  protocolSettings: {
    wireName: "protocol_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ProtocolSettingsFields,
  },
  receiverBusinessIdentity: {
    wireName: "receiver_business_identity",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentityFields,
  },
  senderBusinessIdentity: {
    wireName: "sender_business_identity",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentityFields,
  },
};

const IntegrationAccountAgreement_Properties_Content_AS2Fields: FieldMap = {
  receiveAgreement: {
    wireName: "receive_agreement",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreementFields,
  },
  sendAgreement: {
    wireName: "send_agreement",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreementFields,
  },
};

const IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_AcknowledgementSettingsFields: FieldMap = {
  acknowledgementControlNumberLowerBound: "acknowledgement_control_number_lower_bound",
  acknowledgementControlNumberPrefix: "acknowledgement_control_number_prefix",
  acknowledgementControlNumberSuffix: "acknowledgement_control_number_suffix",
  acknowledgementControlNumberUpperBound: "acknowledgement_control_number_upper_bound",
  batchFunctionalAcknowledgements: "batch_functional_acknowledgements",
  batchTechnicalAcknowledgements: "batch_technical_acknowledgements",
  needFunctionalAcknowledgement: "need_functional_acknowledgement",
  needLoopForValidMessages: "need_loop_for_valid_messages",
  needTechnicalAcknowledgement: "need_technical_acknowledgement",
  rolloverAcknowledgementControlNumber: "rollover_acknowledgement_control_number",
  sendSynchronousAcknowledgement: "send_synchronous_acknowledgement",
};

const IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_EdifactDelimiterOverridesFields: FieldMap = {
  componentSeparator: "component_separator",
  dataElementSeparator: "data_element_separator",
  decimalPointIndicator: "decimal_point_indicator",
  messageAssociationAssignedCode: "message_association_assigned_code",
  messageId: "message_id",
  messageRelease: "message_release",
  messageVersion: "message_version",
  releaseIndicator: "release_indicator",
  repetitionSeparator: "repetition_separator",
  segmentTerminator: "segment_terminator",
  segmentTerminatorSuffix: "segment_terminator_suffix",
  targetNamespace: "target_namespace",
};

const IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_EnvelopeOverridesFields: FieldMap = {
  applicationPassword: "application_password",
  associationAssignedCode: "association_assigned_code",
  controllingAgencyCode: "controlling_agency_code",
  functionalGroupId: "functional_group_id",
  groupHeaderMessageRelease: "group_header_message_release",
  groupHeaderMessageVersion: "group_header_message_version",
  messageAssociationAssignedCode: "message_association_assigned_code",
  messageId: "message_id",
  messageRelease: "message_release",
  messageVersion: "message_version",
  receiverApplicationId: "receiver_application_id",
  receiverApplicationQualifier: "receiver_application_qualifier",
  senderApplicationId: "sender_application_id",
  senderApplicationQualifier: "sender_application_qualifier",
  targetNamespace: "target_namespace",
};

const IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_EnvelopeSettingsFields: FieldMap = {
  applicationReferenceId: "application_reference_id",
  applyDelimiterStringAdvice: "apply_delimiter_string_advice",
  communicationAgreementId: "communication_agreement_id",
  createGroupingSegments: "create_grouping_segments",
  enableDefaultGroupHeaders: "enable_default_group_headers",
  functionalGroupId: "functional_group_id",
  groupApplicationPassword: "group_application_password",
  groupApplicationReceiverId: "group_application_receiver_id",
  groupApplicationReceiverQualifier: "group_application_receiver_qualifier",
  groupApplicationSenderId: "group_application_sender_id",
  groupApplicationSenderQualifier: "group_application_sender_qualifier",
  groupAssociationAssignedCode: "group_association_assigned_code",
  groupControlNumberLowerBound: "group_control_number_lower_bound",
  groupControlNumberPrefix: "group_control_number_prefix",
  groupControlNumberSuffix: "group_control_number_suffix",
  groupControlNumberUpperBound: "group_control_number_upper_bound",
  groupControllingAgencyCode: "group_controlling_agency_code",
  groupMessageRelease: "group_message_release",
  groupMessageVersion: "group_message_version",
  interchangeControlNumberLowerBound: "interchange_control_number_lower_bound",
  interchangeControlNumberPrefix: "interchange_control_number_prefix",
  interchangeControlNumberSuffix: "interchange_control_number_suffix",
  interchangeControlNumberUpperBound: "interchange_control_number_upper_bound",
  isTestInterchange: "is_test_interchange",
  overwriteExistingTransactionSetControlNumber: "overwrite_existing_transaction_set_control_number",
  processingPriorityCode: "processing_priority_code",
  receiverInternalIdentification: "receiver_internal_identification",
  receiverInternalSubIdentification: "receiver_internal_sub_identification",
  receiverReverseRoutingAddress: "receiver_reverse_routing_address",
  recipientReferencePasswordQualifier: "recipient_reference_password_qualifier",
  recipientReferencePasswordValue: "recipient_reference_password_value",
  rolloverGroupControlNumber: "rollover_group_control_number",
  rolloverInterchangeControlNumber: "rollover_interchange_control_number",
  rolloverTransactionSetControlNumber: "rollover_transaction_set_control_number",
  senderInternalIdentification: "sender_internal_identification",
  senderInternalSubIdentification: "sender_internal_sub_identification",
  senderReverseRoutingAddress: "sender_reverse_routing_address",
  transactionSetControlNumberLowerBound: "transaction_set_control_number_lower_bound",
  transactionSetControlNumberPrefix: "transaction_set_control_number_prefix",
  transactionSetControlNumberSuffix: "transaction_set_control_number_suffix",
  transactionSetControlNumberUpperBound: "transaction_set_control_number_upper_bound",
};

const IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_FramingSettingsFields: FieldMap = {
  characterEncoding: "character_encoding",
  characterSet: "character_set",
  componentSeparator: "component_separator",
  dataElementSeparator: "data_element_separator",
  decimalPointIndicator: "decimal_point_indicator",
  protocolVersion: "protocol_version",
  releaseIndicator: "release_indicator",
  repetitionSeparator: "repetition_separator",
  segmentTerminator: "segment_terminator",
  segmentTerminatorSuffix: "segment_terminator_suffix",
  serviceCodeListDirectoryVersion: "service_code_list_directory_version",
};

const IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilterFields: FieldMap = {
  messageFilterType: "message_filter_type",
};

const IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilterListFields: FieldMap = {
  messageId: "message_id",
};

const IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ProcessingSettingsFields: FieldMap = {
  createEmptyXmlTagsForTrailingSeparators: "create_empty_xml_tags_for_trailing_separators",
  maskSecurityInfo: "mask_security_info",
  preserveInterchange: "preserve_interchange",
  suspendInterchangeOnError: "suspend_interchange_on_error",
  useDotAsDecimalSeparator: "use_dot_as_decimal_separator",
};

const IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_SchemaReferencesFields: FieldMap = {
  associationAssignedCode: "association_assigned_code",
  messageId: "message_id",
  messageRelease: "message_release",
  messageVersion: "message_version",
  schemaName: "schema_name",
  senderApplicationId: "sender_application_id",
  senderApplicationQualifier: "sender_application_qualifier",
};

const IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ValidationOverridesFields: FieldMap = {
  allowLeadingAndTrailingSpacesAndZeroes: "allow_leading_and_trailing_spaces_and_zeroes",
  enforceCharacterSet: "enforce_character_set",
  messageId: "message_id",
  trailingSeparatorPolicy: "trailing_separator_policy",
  trimLeadingAndTrailingSpacesAndZeroes: "trim_leading_and_trailing_spaces_and_zeroes",
  validateEditypes: "validate_editypes",
  validateXsdtypes: "validate_xsdtypes",
};

const IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ValidationSettingsFields: FieldMap = {
  allowLeadingAndTrailingSpacesAndZeroes: "allow_leading_and_trailing_spaces_and_zeroes",
  checkDuplicateGroupControlNumber: "check_duplicate_group_control_number",
  checkDuplicateInterchangeControlNumber: "check_duplicate_interchange_control_number",
  checkDuplicateTransactionSetControlNumber: "check_duplicate_transaction_set_control_number",
  interchangeControlNumberValidityDays: "interchange_control_number_validity_days",
  trailingSeparatorPolicy: "trailing_separator_policy",
  trimLeadingAndTrailingSpacesAndZeroes: "trim_leading_and_trailing_spaces_and_zeroes",
  validateCharacterSet: "validate_character_set",
  validateEditypes: "validate_editypes",
  validateXsdtypes: "validate_xsdtypes",
};

const IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettingsFields: FieldMap = {
  acknowledgementSettings: {
    wireName: "acknowledgement_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_AcknowledgementSettingsFields,
  },
  edifactDelimiterOverrides: {
    wireName: "edifact_delimiter_overrides",
    kind: "list",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_EdifactDelimiterOverridesFields,
  },
  envelopeOverrides: {
    wireName: "envelope_overrides",
    kind: "list",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_EnvelopeOverridesFields,
  },
  envelopeSettings: {
    wireName: "envelope_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_EnvelopeSettingsFields,
  },
  framingSettings: {
    wireName: "framing_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_FramingSettingsFields,
  },
  messageFilter: {
    wireName: "message_filter",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilterFields,
  },
  messageFilterList: {
    wireName: "message_filter_list",
    kind: "list",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilterListFields,
  },
  processingSettings: {
    wireName: "processing_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ProcessingSettingsFields,
  },
  schemaReferences: {
    wireName: "schema_references",
    kind: "list",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_SchemaReferencesFields,
  },
  validationOverrides: {
    wireName: "validation_overrides",
    kind: "list",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ValidationOverridesFields,
  },
  validationSettings: {
    wireName: "validation_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ValidationSettingsFields,
  },
};

const IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreementFields: FieldMap = {
  protocolSettings: {
    wireName: "protocol_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettingsFields,
  },
  receiverBusinessIdentity: {
    wireName: "receiver_business_identity",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentityFields,
  },
  senderBusinessIdentity: {
    wireName: "sender_business_identity",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentityFields,
  },
};

const IntegrationAccountAgreement_Properties_Content_EdifactFields: FieldMap = {
  receiveAgreement: {
    wireName: "receive_agreement",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreementFields,
  },
  sendAgreement: {
    wireName: "send_agreement",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreementFields,
  },
};

const IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_AcknowledgementSettingsFields: FieldMap = {
  acknowledgementControlNumberLowerBound: "acknowledgement_control_number_lower_bound",
  acknowledgementControlNumberPrefix: "acknowledgement_control_number_prefix",
  acknowledgementControlNumberSuffix: "acknowledgement_control_number_suffix",
  acknowledgementControlNumberUpperBound: "acknowledgement_control_number_upper_bound",
  batchFunctionalAcknowledgements: "batch_functional_acknowledgements",
  batchImplementationAcknowledgements: "batch_implementation_acknowledgements",
  batchTechnicalAcknowledgements: "batch_technical_acknowledgements",
  functionalAcknowledgementVersion: "functional_acknowledgement_version",
  implementationAcknowledgementVersion: "implementation_acknowledgement_version",
  needFunctionalAcknowledgement: "need_functional_acknowledgement",
  needImplementationAcknowledgement: "need_implementation_acknowledgement",
  needLoopForValidMessages: "need_loop_for_valid_messages",
  needTechnicalAcknowledgement: "need_technical_acknowledgement",
  rolloverAcknowledgementControlNumber: "rollover_acknowledgement_control_number",
  sendSynchronousAcknowledgement: "send_synchronous_acknowledgement",
};

const IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_EnvelopeOverridesFields: FieldMap = {
  dateFormat: "date_format",
  functionalIdentifierCode: "functional_identifier_code",
  headerVersion: "header_version",
  messageId: "message_id",
  protocolVersion: "protocol_version",
  receiverApplicationId: "receiver_application_id",
  responsibleAgencyCode: "responsible_agency_code",
  senderApplicationId: "sender_application_id",
  targetNamespace: "target_namespace",
  timeFormat: "time_format",
};

const IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_EnvelopeSettingsFields: FieldMap = {
  controlStandardsId: "control_standards_id",
  controlVersionNumber: "control_version_number",
  enableDefaultGroupHeaders: "enable_default_group_headers",
  functionalGroupId: "functional_group_id",
  groupControlNumberLowerBound: "group_control_number_lower_bound",
  groupControlNumberUpperBound: "group_control_number_upper_bound",
  groupHeaderAgencyCode: "group_header_agency_code",
  groupHeaderDateFormat: "group_header_date_format",
  groupHeaderTimeFormat: "group_header_time_format",
  groupHeaderVersion: "group_header_version",
  interchangeControlNumberLowerBound: "interchange_control_number_lower_bound",
  interchangeControlNumberUpperBound: "interchange_control_number_upper_bound",
  overwriteExistingTransactionSetControlNumber: "overwrite_existing_transaction_set_control_number",
  receiverApplicationId: "receiver_application_id",
  rolloverGroupControlNumber: "rollover_group_control_number",
  rolloverInterchangeControlNumber: "rollover_interchange_control_number",
  rolloverTransactionSetControlNumber: "rollover_transaction_set_control_number",
  senderApplicationId: "sender_application_id",
  transactionSetControlNumberLowerBound: "transaction_set_control_number_lower_bound",
  transactionSetControlNumberPrefix: "transaction_set_control_number_prefix",
  transactionSetControlNumberSuffix: "transaction_set_control_number_suffix",
  transactionSetControlNumberUpperBound: "transaction_set_control_number_upper_bound",
  usageIndicator: "usage_indicator",
  useControlStandardsIdAsRepetitionCharacter: "use_control_standards_id_as_repetition_character",
};

const IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_FramingSettingsFields: FieldMap = {
  characterSet: "character_set",
  componentSeparator: "component_separator",
  dataElementSeparator: "data_element_separator",
  replaceCharacter: "replace_character",
  replaceSeparatorsInPayload: "replace_separators_in_payload",
  segmentTerminator: "segment_terminator",
  segmentTerminatorSuffix: "segment_terminator_suffix",
};

const IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_ProcessingSettingsFields: FieldMap = {
  convertImpliedDecimal: "convert_implied_decimal",
  createEmptyXmlTagsForTrailingSeparators: "create_empty_xml_tags_for_trailing_separators",
  maskSecurityInfo: "mask_security_info",
  preserveInterchange: "preserve_interchange",
  suspendInterchangeOnError: "suspend_interchange_on_error",
  useDotAsDecimalSeparator: "use_dot_as_decimal_separator",
};

const IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_SchemaReferencesFields: FieldMap = {
  messageId: "message_id",
  schemaName: "schema_name",
  schemaVersion: "schema_version",
  senderApplicationId: "sender_application_id",
};

const IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_SecuritySettingsFields: FieldMap = {
  authorizationQualifier: "authorization_qualifier",
  authorizationValue: "authorization_value",
  passwordValue: "password_value",
  securityQualifier: "security_qualifier",
};

const IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_ValidationOverridesFields: FieldMap = {
  allowLeadingAndTrailingSpacesAndZeroes: "allow_leading_and_trailing_spaces_and_zeroes",
  messageId: "message_id",
  trailingSeparatorPolicy: "trailing_separator_policy",
  trimLeadingAndTrailingSpacesAndZeroes: "trim_leading_and_trailing_spaces_and_zeroes",
  validateCharacterSet: "validate_character_set",
  validateEditypes: "validate_editypes",
  validateXsdtypes: "validate_xsdtypes",
};

const IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_X12DelimiterOverridesFields: FieldMap = {
  componentSeparator: "component_separator",
  dataElementSeparator: "data_element_separator",
  messageId: "message_id",
  protocolVersion: "protocol_version",
  replaceCharacter: "replace_character",
  replaceSeparatorsInPayload: "replace_separators_in_payload",
  segmentTerminator: "segment_terminator",
  segmentTerminatorSuffix: "segment_terminator_suffix",
  targetNamespace: "target_namespace",
};

const IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettingsFields: FieldMap = {
  acknowledgementSettings: {
    wireName: "acknowledgement_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_AcknowledgementSettingsFields,
  },
  envelopeOverrides: {
    wireName: "envelope_overrides",
    kind: "list",
    fields: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_EnvelopeOverridesFields,
  },
  envelopeSettings: {
    wireName: "envelope_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_EnvelopeSettingsFields,
  },
  framingSettings: {
    wireName: "framing_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_FramingSettingsFields,
  },
  messageFilter: {
    wireName: "message_filter",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilterFields,
  },
  messageFilterList: {
    wireName: "message_filter_list",
    kind: "list",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_MessageFilterListFields,
  },
  processingSettings: {
    wireName: "processing_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_ProcessingSettingsFields,
  },
  schemaReferences: {
    wireName: "schema_references",
    kind: "list",
    fields: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_SchemaReferencesFields,
  },
  securitySettings: {
    wireName: "security_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_SecuritySettingsFields,
  },
  validationOverrides: {
    wireName: "validation_overrides",
    kind: "list",
    fields: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_ValidationOverridesFields,
  },
  validationSettings: {
    wireName: "validation_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_Edifact_ReceiveAgreement_ProtocolSettings_ValidationSettingsFields,
  },
  x12DelimiterOverrides: {
    wireName: "x12_delimiter_overrides",
    kind: "list",
    fields: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettings_X12DelimiterOverridesFields,
  },
};

const IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreementFields: FieldMap = {
  protocolSettings: {
    wireName: "protocol_settings",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreement_ProtocolSettingsFields,
  },
  receiverBusinessIdentity: {
    wireName: "receiver_business_identity",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentityFields,
  },
  senderBusinessIdentity: {
    wireName: "sender_business_identity",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentityFields,
  },
};

const IntegrationAccountAgreement_Properties_Content_X12Fields: FieldMap = {
  receiveAgreement: {
    wireName: "receive_agreement",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreementFields,
  },
  sendAgreement: {
    wireName: "send_agreement",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_X12_ReceiveAgreementFields,
  },
};

const IntegrationAccountAgreement_Properties_ContentFields: FieldMap = {
  aS2: {
    wireName: "a_s2",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2Fields,
  },
  edifact: {
    wireName: "edifact",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_EdifactFields,
  },
  x12: {
    wireName: "x12",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_X12Fields,
  },
};

const IntegrationAccountAgreement_PropertiesFields: FieldMap = {
  agreementType: "agreement_type",
  changedTime: "changed_time",
  content: {
    wireName: "content",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_ContentFields,
  },
  createdTime: "created_time",
  guestIdentity: {
    wireName: "guest_identity",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentityFields,
  },
  guestPartner: "guest_partner",
  hostIdentity: {
    wireName: "host_identity",
    kind: "object",
    fields: IntegrationAccountAgreement_Properties_Content_AS2_ReceiveAgreement_ReceiverBusinessIdentityFields,
  },
  hostPartner: "host_partner",
  metadata: "metadata",
};

export interface IntegrationAccountAgreementConfig {
  /** The resource location. */
  location?: string | Computed<string>;
  /** The integration account agreement properties. */
  properties: IntegrationAccountAgreement_Properties | Computed<IntegrationAccountAgreement_Properties>;
  /** The resource tags. */
  tags?: Record<string, string> | Computed<Record<string, string>>;
}

export interface IntegrationAccountAgreementAttrs {
  /** The resource id. */
  id: string;
  /** The resource location. */
  location: string;
  /** Gets the resource name. */
  name: string;
  /** The integration account agreement properties. */
  properties: IntegrationAccountAgreement_Properties;
  /** The resource tags. */
  tags: Record<string, string>;
  /** Gets the resource type. */
  type: string;
}

export const IntegrationAccountAgreement: ResourceBinding<IntegrationAccountAgreementConfig, IntegrationAccountAgreementAttrs> = {
  wireType: "azure_logic_integration_account_agreement",
  fields: {
    location: "location",
    properties: {
      wireName: "properties",
      kind: "object",
      fields: IntegrationAccountAgreement_PropertiesFields,
    },
    tags: "tags",
  },
};
