// Code generated by `ubx sdk gen` from azure_apimanagement_apimworkspaces_api_contract_2. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ApimworkspacesApiContract2_Properties_WsdlSelector {
  /** Name of endpoint(port) to import from WSDL */
  wsdlEndpointName?: string | Computed<string>;
  /** Name of service to import from WSDL */
  wsdlServiceName?: string | Computed<string>;
}

export interface ApimworkspacesApiContract2_Properties {
  /** Type of API to create. * `http` creates a REST API * `soap` creates a SOAP pass-through API * `websocket` creates websocket API * `graphql` creates GraphQL API. New types can be added in the future. */
  apiType?: string | Computed<string>;
  /** Format of the Content in which the API is getting imported. New formats can be added in the future */
  format?: string | Computed<string>;
  /** Strategy of translating required query parameters to template ones. By default has value 'template'. Possible values: 'template', 'query' */
  translateRequiredQueryParameters?: string | Computed<string>;
  /** Content value when Importing an API. */
  value?: string | Computed<string>;
  /** Criteria to limit import of WSDL to a subset of the document. */
  wsdlSelector?: ApimworkspacesApiContract2_Properties_WsdlSelector | Computed<ApimworkspacesApiContract2_Properties_WsdlSelector>;
}

const ApimworkspacesApiContract2_Properties_WsdlSelectorFields: FieldMap = {
  wsdlEndpointName: "wsdl_endpoint_name",
  wsdlServiceName: "wsdl_service_name",
};

const ApimworkspacesApiContract2_PropertiesFields: FieldMap = {
  apiType: "api_type",
  format: "format",
  translateRequiredQueryParameters: "translate_required_query_parameters",
  value: "value",
  wsdlSelector: {
    wireName: "wsdl_selector",
    kind: "object",
    fields: ApimworkspacesApiContract2_Properties_WsdlSelectorFields,
  },
};

export interface ApimworkspacesApiContract2Config {
  /** API Create or Update Properties. */
  properties?: ApimworkspacesApiContract2_Properties | Computed<ApimworkspacesApiContract2_Properties>;
}

export interface ApimworkspacesApiContract2Attrs {
  /** API Create or Update Properties. */
  properties: ApimworkspacesApiContract2_Properties;
}

export const ApimworkspacesApiContract2: ResourceBinding<ApimworkspacesApiContract2Config, ApimworkspacesApiContract2Attrs> = {
  wireType: "azure_apimanagement_apimworkspaces_api_contract_2",
  fields: {
    properties: {
      wireName: "properties",
      kind: "object",
      fields: ApimworkspacesApiContract2_PropertiesFields,
    },
  },
};
