# Code generated by `ubx sdk gen` from azure_communication_openapi_communication_service_resource. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OpenapiCommunicationServiceResource_Identity_UserAssignedIdentities:
    client_id: Any = None
    principal_id: Any = None

@dataclasses.dataclass
class OpenapiCommunicationServiceResource_Identity:
    # The service principal ID of the system assigned identity. This property will only be provided for a system assigned identity.
    principal_id: Any = None
    # The tenant ID of the system assigned identity. This property will only be provided for a system assigned identity.
    tenant_id: Any = None
    # Type of managed service identity (where both SystemAssigned and UserAssigned types are allowed).
    type: Any = None
    # The set of user assigned identities associated with the resource. The userAssignedIdentities dictionary keys will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}. The dictionary values can be empty objects ({}) in requests.
    user_assigned_identities: Any = None

@dataclasses.dataclass
class OpenapiCommunicationServiceResource_Properties:
    # The location where the communication service stores its data at rest.
    data_location: Any = None
    # Disable local authentication for the CommunicationService.
    disable_local_auth: Any = None
    # FQDN of the CommunicationService instance.
    host_name: Any = None
    # The immutable resource Id of the communication service.
    immutable_resource_id: Any = None
    # List of email Domain resource Ids.
    linked_domains: Any = None
    # Resource ID of an Azure Notification Hub linked to this resource.
    notification_hub_id: Any = None
    # Provisioning state of the resource.
    provisioning_state: Any = None
    # Allow, disallow, or let network security perimeter configuration control public network access to the protected resource. Value is optional but if passed in, it must be 'Enabled', 'Disabled' or 'SecuredByPerimeter'.
    public_network_access: Any = None
    # Version of the CommunicationService resource. Probably you need the same or higher version of client SDKs.
    version: Any = None

_OpenapiCommunicationServiceResource_Identity_UserAssignedIdentitiesFields = {
    "client_id": ubx.FieldSpec(wire_name="client_id"),
    "principal_id": ubx.FieldSpec(wire_name="principal_id"),
}

_OpenapiCommunicationServiceResource_IdentityFields = {
    "principal_id": ubx.FieldSpec(wire_name="principal_id"),
    "tenant_id": ubx.FieldSpec(wire_name="tenant_id"),
    "type": ubx.FieldSpec(wire_name="type"),
    "user_assigned_identities": ubx.FieldSpec(
        wire_name="user_assigned_identities",
        kind="map",
        fields=_OpenapiCommunicationServiceResource_Identity_UserAssignedIdentitiesFields,
    ),
}

_OpenapiCommunicationServiceResource_PropertiesFields = {
    "data_location": ubx.FieldSpec(wire_name="data_location"),
    "disable_local_auth": ubx.FieldSpec(wire_name="disable_local_auth"),
    "host_name": ubx.FieldSpec(wire_name="host_name"),
    "immutable_resource_id": ubx.FieldSpec(wire_name="immutable_resource_id"),
    "linked_domains": ubx.FieldSpec(wire_name="linked_domains"),
    "notification_hub_id": ubx.FieldSpec(wire_name="notification_hub_id"),
    "provisioning_state": ubx.FieldSpec(wire_name="provisioning_state"),
    "public_network_access": ubx.FieldSpec(wire_name="public_network_access"),
    "version": ubx.FieldSpec(wire_name="version"),
}

@dataclasses.dataclass
class OpenapiCommunicationServiceResourceConfig:
    # Managed service identity (system assigned and/or user assigned identities)
    identity: Any = None
    # The geo-location where the resource lives
    location: Any = None
    # A class that describes the properties of the CommunicationService.
    properties: Any = None
    # Resource tags.
    tags: Any = None

@dataclasses.dataclass
class OpenapiCommunicationServiceResourceAttrs:
    # Managed service identity (system assigned and/or user assigned identities)
    identity: Any = None
    # The geo-location where the resource lives
    location: Any = None
    # A class that describes the properties of the CommunicationService.
    properties: Any = None
    # Resource tags.
    tags: Any = None

OpenapiCommunicationServiceResource = ubx.ResourceBinding(
    wire_type="azure_communication_openapi_communication_service_resource",
    fields={
        "identity": ubx.FieldSpec(
            wire_name="identity",
            kind="object",
            fields=_OpenapiCommunicationServiceResource_IdentityFields,
        ),
        "location": ubx.FieldSpec(wire_name="location"),
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_OpenapiCommunicationServiceResource_PropertiesFields,
        ),
        "tags": ubx.FieldSpec(wire_name="tags"),
    },
)
