# Code generated by `ubx sdk gen` from azure_appplatform_gateway_custom_domain_resource. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class GatewayCustomDomainResource_Properties:
    # The thumbprint of bound certificate.
    thumbprint: Any = None

_GatewayCustomDomainResource_PropertiesFields = {
    "thumbprint": ubx.FieldSpec(wire_name="thumbprint"),
}

@dataclasses.dataclass
class GatewayCustomDomainResourceConfig:
    # The properties of custom domain for Spring Cloud Gateway
    properties: Any = None

@dataclasses.dataclass
class GatewayCustomDomainResourceAttrs:
    # The properties of custom domain for Spring Cloud Gateway
    properties: Any = None

GatewayCustomDomainResource = ubx.ResourceBinding(
    wire_type="azure_appplatform_gateway_custom_domain_resource",
    fields={
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_GatewayCustomDomainResource_PropertiesFields,
        ),
    },
)
