// Code generated by `ubx sdk gen` from azure_operationalinsights_openapi_storage_insight_list. DO NOT EDIT.
package operationalinsights

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpenapiStorageInsightList_Value_Properties_Status struct {
	Description any
	State any
}

type OpenapiStorageInsightList_Value_Properties_StorageAccount struct {
	Id any
	Key any
}

type OpenapiStorageInsightList_Value_Properties struct {
	Containers any
	Status any
	StorageAccount any
	Tables any
}

type OpenapiStorageInsightList_Value struct {
	ETag any
	Properties any
	Tags any
}

type OpenapiStorageInsightListConfig struct {
	WorkspaceName any
}

type OpenapiStorageInsightListAttrs struct {
	// A list of storage insight items.
	Value any
	WorkspaceName any
}

var OpenapiStorageInsightList = ubx.DataSourceBinding{
	WireType: "azure_operationalinsights_openapi_storage_insight_list",
	Fields: ubx.FieldMap{
		"WorkspaceName": ubx.FieldSpec{WireName: "workspace_name"},
	},
}
