// Code generated by `ubx sdk gen` from azurerm_managed_lustre_file_system. DO NOT EDIT.
package managed

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type LustreFileSystem_EncryptionKey struct {
	KeyUrl any
	SourceVaultId any
}

type LustreFileSystem_HsmSetting struct {
	ContainerId any
	ImportPrefix any
	LoggingContainerId any
}

type LustreFileSystem_Identity struct {
	IdentityIds any
	Type any
}

type LustreFileSystem_MaintenanceWindow struct {
	DayOfWeek any
	TimeOfDayInUtc any
}

type LustreFileSystem_RootSquash struct {
	Mode any
	NoSquashNids any
	SquashGid any
	SquashUid any
}

type LustreFileSystem_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var LustreFileSystem_EncryptionKeyFields = ubx.FieldMap{
		"KeyUrl": ubx.FieldSpec{WireName: "key_url"},
		"SourceVaultId": ubx.FieldSpec{WireName: "source_vault_id"},
	}

var LustreFileSystem_HsmSettingFields = ubx.FieldMap{
		"ContainerId": ubx.FieldSpec{WireName: "container_id"},
		"ImportPrefix": ubx.FieldSpec{WireName: "import_prefix"},
		"LoggingContainerId": ubx.FieldSpec{WireName: "logging_container_id"},
	}

var LustreFileSystem_IdentityFields = ubx.FieldMap{
		"IdentityIds": ubx.FieldSpec{WireName: "identity_ids"},
		"Type": ubx.FieldSpec{WireName: "type"},
	}

var LustreFileSystem_MaintenanceWindowFields = ubx.FieldMap{
		"DayOfWeek": ubx.FieldSpec{WireName: "day_of_week"},
		"TimeOfDayInUtc": ubx.FieldSpec{WireName: "time_of_day_in_utc"},
	}

var LustreFileSystem_RootSquashFields = ubx.FieldMap{
		"Mode": ubx.FieldSpec{WireName: "mode"},
		"NoSquashNids": ubx.FieldSpec{WireName: "no_squash_nids"},
		"SquashGid": ubx.FieldSpec{WireName: "squash_gid"},
		"SquashUid": ubx.FieldSpec{WireName: "squash_uid"},
	}

var LustreFileSystem_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Read": ubx.FieldSpec{WireName: "read"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

type LustreFileSystemConfig struct {
	Id any
	Location any
	Name any
	ResourceGroupName any
	SkuName any
	StorageCapacityInTb any
	SubnetId any
	Tags any
	Zones any
	EncryptionKey any
	HsmSetting any
	Identity any
	MaintenanceWindow any
	RootSquash any
	Timeouts any
}

var LustreFileSystem = ubx.ResourceBinding{
	WireType: "azurerm_managed_lustre_file_system",
	Fields: ubx.FieldMap{
		"Id": ubx.FieldSpec{WireName: "id"},
		"Location": ubx.FieldSpec{WireName: "location"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"ResourceGroupName": ubx.FieldSpec{WireName: "resource_group_name"},
		"SkuName": ubx.FieldSpec{WireName: "sku_name"},
		"StorageCapacityInTb": ubx.FieldSpec{WireName: "storage_capacity_in_tb"},
		"SubnetId": ubx.FieldSpec{WireName: "subnet_id"},
		"Tags": ubx.FieldSpec{WireName: "tags"},
		"Zones": ubx.FieldSpec{WireName: "zones"},
		"EncryptionKey": ubx.FieldSpec{
			WireName: "encryption_key",
			Kind: "list",
			Fields: LustreFileSystem_EncryptionKeyFields,
		},
		"HsmSetting": ubx.FieldSpec{
			WireName: "hsm_setting",
			Kind: "list",
			Fields: LustreFileSystem_HsmSettingFields,
		},
		"Identity": ubx.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: LustreFileSystem_IdentityFields,
		},
		"MaintenanceWindow": ubx.FieldSpec{
			WireName: "maintenance_window",
			Kind: "list",
			Fields: LustreFileSystem_MaintenanceWindowFields,
		},
		"RootSquash": ubx.FieldSpec{
			WireName: "root_squash",
			Kind: "list",
			Fields: LustreFileSystem_RootSquashFields,
		},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: LustreFileSystem_TimeoutsFields,
		},
	},
}
