// Code generated by `ubx sdk gen` from azurerm_log_analytics_workspace. DO NOT EDIT.
package log

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AnalyticsWorkspace_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type AnalyticsWorkspace_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AnalyticsWorkspace_IdentityFields = ubx.FieldMap{
		"IdentityIds": ubx.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": ubx.FieldSpec{WireName: "principal_id"},
		"TenantId": ubx.FieldSpec{WireName: "tenant_id"},
		"Type": ubx.FieldSpec{WireName: "type"},
	}

var AnalyticsWorkspace_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Read": ubx.FieldSpec{WireName: "read"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

type AnalyticsWorkspaceConfig struct {
	AllowResourceOnlyPermissions any
	CmkForQueryForced any
	DailyQuotaGb any
	DataCollectionRuleId any
	Id any
	ImmediateDataPurgeOn30DaysEnabled any
	InternetIngestionAccessType any
	InternetQueryAccessType any
	LocalAuthenticationEnabled any
	Location any
	Name any
	ReservationCapacityInGbPerDay any
	ResourceGroupName any
	RetentionInDays any
	Sku any
	Tags any
	Identity any
	Timeouts any
}

var AnalyticsWorkspace = ubx.ResourceBinding{
	WireType: "azurerm_log_analytics_workspace",
	Fields: ubx.FieldMap{
		"AllowResourceOnlyPermissions": ubx.FieldSpec{WireName: "allow_resource_only_permissions"},
		"CmkForQueryForced": ubx.FieldSpec{WireName: "cmk_for_query_forced"},
		"DailyQuotaGb": ubx.FieldSpec{WireName: "daily_quota_gb"},
		"DataCollectionRuleId": ubx.FieldSpec{WireName: "data_collection_rule_id"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"ImmediateDataPurgeOn30DaysEnabled": ubx.FieldSpec{WireName: "immediate_data_purge_on_30_days_enabled"},
		"InternetIngestionAccessType": ubx.FieldSpec{WireName: "internet_ingestion_access_type"},
		"InternetQueryAccessType": ubx.FieldSpec{WireName: "internet_query_access_type"},
		"LocalAuthenticationEnabled": ubx.FieldSpec{WireName: "local_authentication_enabled"},
		"Location": ubx.FieldSpec{WireName: "location"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"ReservationCapacityInGbPerDay": ubx.FieldSpec{WireName: "reservation_capacity_in_gb_per_day"},
		"ResourceGroupName": ubx.FieldSpec{WireName: "resource_group_name"},
		"RetentionInDays": ubx.FieldSpec{WireName: "retention_in_days"},
		"Sku": ubx.FieldSpec{WireName: "sku"},
		"Tags": ubx.FieldSpec{WireName: "tags"},
		"Identity": ubx.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: AnalyticsWorkspace_IdentityFields,
		},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AnalyticsWorkspace_TimeoutsFields,
		},
	},
}
