// Code generated by `ubx sdk gen` from azure_security_datascanners_data_scanner. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface DatascannersDataScanner_Value_Identity {
  principalId?: string | Computed<string>;
  tenantId?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface DatascannersDataScanner_Value {
  identity?: DatascannersDataScanner_Value_Identity | Computed<DatascannersDataScanner_Value_Identity>;
  properties?: unknown | Computed<unknown>;
}

export interface DatascannersDataScannerConfig {
  scopeId: string | Computed<string>;
}

export interface DatascannersDataScannerAttrs {
  /** The URI to fetch the next page. */
  nextLink: string;
  scopeId: string;
  /** The list of data scanner resources. */
  value: DatascannersDataScanner_Value[];
}

export const DatascannersDataScanner: DataSourceBinding<DatascannersDataScannerConfig, DatascannersDataScannerAttrs> = {
  wireType: "azure_security_datascanners_data_scanner",
  fields: {
    scopeId: "scope_id",
  },
};
