// Code generated by `ubx sdk gen` from azure_devtestlabs_dtl_artifact_source. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DtlArtifactSource_Properties {
  /** The folder containing Azure Resource Manager templates. */
  armTemplateFolderPath?: string | Computed<string>;
  /** The artifact source's branch reference. */
  branchRef?: string | Computed<string>;
  /** The artifact source's creation date. */
  createdDate?: string | Computed<string>;
  /** The artifact source's display name. */
  displayName?: string | Computed<string>;
  /** The folder containing artifacts. */
  folderPath?: string | Computed<string>;
  /** The provisioning status of the resource. */
  provisioningState?: string | Computed<string>;
  /** The security token to authenticate to the artifact source. */
  securityToken?: string | Computed<string>;
  /** The artifact source's type. */
  sourceType?: string | Computed<string>;
  /** Indicates if the artifact source is enabled (values: Enabled, Disabled). */
  status?: string | Computed<string>;
  /** The unique immutable identifier of a resource (Guid). */
  uniqueIdentifier?: string | Computed<string>;
  /** The artifact source's URI. */
  uri?: string | Computed<string>;
}

const DtlArtifactSource_PropertiesFields: FieldMap = {
  armTemplateFolderPath: "arm_template_folder_path",
  branchRef: "branch_ref",
  createdDate: "created_date",
  displayName: "display_name",
  folderPath: "folder_path",
  provisioningState: "provisioning_state",
  securityToken: "security_token",
  sourceType: "source_type",
  status: "status",
  uniqueIdentifier: "unique_identifier",
  uri: "uri",
};

export interface DtlArtifactSourceConfig {
  /** The geo-location where the resource lives */
  location?: string | Computed<string>;
  /** Properties of an artifact source. */
  properties: DtlArtifactSource_Properties | Computed<DtlArtifactSource_Properties>;
  /** Resource tags. */
  tags?: Record<string, string> | Computed<Record<string, string>>;
  /** path parameter, not part of the API's own resource representation */
  name: string | Computed<string>;
}

export interface DtlArtifactSourceAttrs {
  /** The geo-location where the resource lives */
  location: string;
  /** Properties of an artifact source. */
  properties: DtlArtifactSource_Properties;
  /** Resource tags. */
  tags: Record<string, string>;
  /** path parameter, not part of the API's own resource representation */
  name: string;
}

export const DtlArtifactSource: ResourceBinding<DtlArtifactSourceConfig, DtlArtifactSourceAttrs> = {
  wireType: "azure_devtestlabs_dtl_artifact_source",
  fields: {
    location: "location",
    properties: {
      wireName: "properties",
      kind: "object",
      fields: DtlArtifactSource_PropertiesFields,
    },
    tags: "tags",
    name: "name",
  },
};
