// Code generated by `ubx sdk gen` from azure_recoveryservicessiterecovery_service_alert. DO NOT EDIT.
package recoveryservicessiterecovery

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ServiceAlert_Value_Properties struct {
	CustomEmailAddresses any
	Locale any
	SendToOwners any
}

type ServiceAlert_Value struct {
	Location any
	Properties any
}

type ServiceAlertConfig struct {
	ResourceName any
}

type ServiceAlertAttrs struct {
	// The link to the next page of items
	NextLink any
	ResourceName any
	// The Alert items on this page
	Value any
}

var ServiceAlert = ubx.DataSourceBinding{
	WireType: "azure_recoveryservicessiterecovery_service_alert",
	Fields: ubx.FieldMap{
		"ResourceName": ubx.FieldSpec{WireName: "resource_name"},
	},
}
