# Code generated by `ubx sdk gen` from azure_recoveryservicesbackup_bms_protected_item_resource. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class BmsProtectedItemResource_Properties_SourceSideScanInfo:
    # Threat status of the container
    source_side_scan_status: Any = None
    # Threat summary for the container
    source_side_scan_summary: Any = None

@dataclasses.dataclass
class BmsProtectedItemResource_Properties:
    # Backup management type to execute the current job.
    backup_management_type: Any = None
    # Name of the backup set the backup item belongs to
    backup_set_name: Any = None
    # Unique name of container
    container_name: Any = None
    # Create mode to indicate recovery of existing soft deleted data source or creation of new data source.
    create_mode: Any = None
    # Time for deferred deletion in UTC
    deferred_delete_time_in_utc: Any = None
    # Time remaining before the DS marked for deferred delete is permanently deleted
    deferred_delete_time_remaining: Any = None
    # Flag to identify whether datasource is protected in archive
    is_archive_enabled: Any = None
    # Flag to identify whether the deferred deleted DS is to be purged soon
    is_deferred_delete_schedule_upcoming: Any = None
    # Flag to identify that deferred deleted DS is to be moved into Pause state
    is_rehydrate: Any = None
    # Flag to identify whether the DS is scheduled for deferred delete
    is_scheduled_for_deferred_delete: Any = None
    # Timestamp when the last (latest) backup copy was created for this backup item.
    last_recovery_point: Any = None
    # ID of the backup policy with which this item is backed up.
    policy_id: Any = None
    # Name of the policy used for protection
    policy_name: Any = None
    # backup item type.
    protected_item_type: Any = None
    # ResourceGuardOperationRequests on which LAC check will be performed
    resource_guard_operation_requests: Any = None
    # Soft delete retention period in days
    soft_delete_retention_period_in_days: Any = None
    # Source location of the protected item datasource.
    source_location: Any = None
    # ARM ID of the resource to be backed up.
    source_resource_id: Any = None
    # Source side threat information
    source_side_scan_info: Any = None
    # ID of the vault which protects this item
    vault_id: Any = None
    # Type of workload this item represents.
    workload_type: Any = None

_BmsProtectedItemResource_Properties_SourceSideScanInfoFields = {
    "source_side_scan_status": ubx.FieldSpec(wire_name="source_side_scan_status"),
    "source_side_scan_summary": ubx.FieldSpec(wire_name="source_side_scan_summary"),
}

_BmsProtectedItemResource_PropertiesFields = {
    "backup_management_type": ubx.FieldSpec(wire_name="backup_management_type"),
    "backup_set_name": ubx.FieldSpec(wire_name="backup_set_name"),
    "container_name": ubx.FieldSpec(wire_name="container_name"),
    "create_mode": ubx.FieldSpec(wire_name="create_mode"),
    "deferred_delete_time_in_utc": ubx.FieldSpec(wire_name="deferred_delete_time_in_utc"),
    "deferred_delete_time_remaining": ubx.FieldSpec(wire_name="deferred_delete_time_remaining"),
    "is_archive_enabled": ubx.FieldSpec(wire_name="is_archive_enabled"),
    "is_deferred_delete_schedule_upcoming": ubx.FieldSpec(wire_name="is_deferred_delete_schedule_upcoming"),
    "is_rehydrate": ubx.FieldSpec(wire_name="is_rehydrate"),
    "is_scheduled_for_deferred_delete": ubx.FieldSpec(wire_name="is_scheduled_for_deferred_delete"),
    "last_recovery_point": ubx.FieldSpec(wire_name="last_recovery_point"),
    "policy_id": ubx.FieldSpec(wire_name="policy_id"),
    "policy_name": ubx.FieldSpec(wire_name="policy_name"),
    "protected_item_type": ubx.FieldSpec(wire_name="protected_item_type"),
    "resource_guard_operation_requests": ubx.FieldSpec(wire_name="resource_guard_operation_requests"),
    "soft_delete_retention_period_in_days": ubx.FieldSpec(wire_name="soft_delete_retention_period_in_days"),
    "source_location": ubx.FieldSpec(wire_name="source_location"),
    "source_resource_id": ubx.FieldSpec(wire_name="source_resource_id"),
    "source_side_scan_info": ubx.FieldSpec(
        wire_name="source_side_scan_info",
        kind="object",
        fields=_BmsProtectedItemResource_Properties_SourceSideScanInfoFields,
    ),
    "vault_id": ubx.FieldSpec(wire_name="vault_id"),
    "workload_type": ubx.FieldSpec(wire_name="workload_type"),
}

@dataclasses.dataclass
class BmsProtectedItemResourceConfig:
    # Optional ETag.
    e_tag: Any = None
    # Represents an Azure geography region where supported resource providers live.
    location: Any = None
    # Base class for backup items.
    properties: Any = None
    # Resource tags.
    tags: Any = None

@dataclasses.dataclass
class BmsProtectedItemResourceAttrs:
    # Optional ETag.
    e_tag: Any = None
    # Represents an Azure geography region where supported resource providers live.
    location: Any = None
    # Base class for backup items.
    properties: Any = None
    # Resource tags.
    tags: Any = None

BmsProtectedItemResource = ubx.ResourceBinding(
    wire_type="azure_recoveryservicesbackup_bms_protected_item_resource",
    fields={
        "e_tag": ubx.FieldSpec(wire_name="e_tag"),
        "location": ubx.FieldSpec(wire_name="location"),
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_BmsProtectedItemResource_PropertiesFields,
        ),
        "tags": ubx.FieldSpec(wire_name="tags"),
    },
)
