// Code generated by `ubx sdk gen` from azure_network_expressroute_route_filter_rule_list. DO NOT EDIT.
package network

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ExpressrouteRouteFilterRuleList_Value_Properties struct {
	Access any
	Communities any
	ProvisioningState any
	RouteFilterRuleType any
}

type ExpressrouteRouteFilterRuleList_Value struct {
	Etag any
	Location any
	Name any
	Properties any
}

type ExpressrouteRouteFilterRuleListConfig struct {
	RouteFilterName any
}

type ExpressrouteRouteFilterRuleListAttrs struct {
	// The link to the next page of items
	NextLink any
	RouteFilterName any
	// The RouteFilterRule items on this page
	Value any
}

var ExpressrouteRouteFilterRuleList = ubx.DataSourceBinding{
	WireType: "azure_network_expressroute_route_filter_rule_list",
	Fields: ubx.FieldMap{
		"RouteFilterName": ubx.FieldSpec{WireName: "route_filter_name"},
	},
}
