// Code generated by `ubx sdk gen` from azure_network_firewallpolicy_firewall_policy_rule_collection_group. DO NOT EDIT.
package network

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type FirewallpolicyFirewallPolicyRuleCollectionGroup_Value_Properties_RuleCollections struct {
	Name any
	Priority any
	RuleCollectionType any
}

type FirewallpolicyFirewallPolicyRuleCollectionGroup_Value_Properties struct {
	Priority any
	ProvisioningState any
	RuleCollections any
	Size any
}

type FirewallpolicyFirewallPolicyRuleCollectionGroup_Value struct {
	Etag any
	Properties any
}

type FirewallpolicyFirewallPolicyRuleCollectionGroupConfig struct {
	FirewallPolicyName any
}

type FirewallpolicyFirewallPolicyRuleCollectionGroupAttrs struct {
	FirewallPolicyName any
	// The link to the next page of items
	NextLink any
	// The FirewallPolicyRuleCollectionGroup items on this page
	Value any
}

var FirewallpolicyFirewallPolicyRuleCollectionGroup = ubx.DataSourceBinding{
	WireType: "azure_network_firewallpolicy_firewall_policy_rule_collection_group",
	Fields: ubx.FieldMap{
		"FirewallPolicyName": ubx.FieldSpec{WireName: "firewall_policy_name"},
	},
}
