// Code generated by `ubx sdk gen` from azure_network_virtualnetwork_available_service_alias. DO NOT EDIT.
package network

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type VirtualnetworkAvailableServiceAlias_Value struct {
	Id           any
	Name         any
	ResourceName any
	Type         any
}

type VirtualnetworkAvailableServiceAliasConfig struct {
}

type VirtualnetworkAvailableServiceAliasAttrs struct {
	// The link to the next page of items
	NextLink any
	// The AvailableServiceAlias items on this page
	Value any
}

var VirtualnetworkAvailableServiceAlias = ubx.DataSourceBinding{
	WireType: "azure_network_virtualnetwork_available_service_alias",
	Fields:   ubx.FieldMap{},
}
