# Code generated by `ubx sdk gen` from azure_databox_operation_list. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OperationList_Value_Display:
    description: Any = None
    operation: Any = None
    provider: Any = None
    resource: Any = None

@dataclasses.dataclass
class OperationList_Value:
    display: Any = None
    is_data_action: Any = None
    name: Any = None
    origin: Any = None
    properties: Any = None

@dataclasses.dataclass
class OperationListConfig:
    pass

@dataclasses.dataclass
class OperationListAttrs:
    # The link to fetch the next page of connected cluster API operations.
    next_link: Any = None
    # The list of connected cluster API operations.
    value: Any = None

OperationList = ubx.DataSourceBinding(
    wire_type="azure_databox_operation_list",
    fields={
    },
)
