// Code generated by `ubx sdk gen` from azure_recoveryservicessiterecovery_service_vault_setting_collection. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ServiceVaultSettingCollection_Value_Properties {
  migrationSolutionId?: string | Computed<string>;
  vmwareToAzureProviderType?: string | Computed<string>;
}

export interface ServiceVaultSettingCollection_Value {
  location?: string | Computed<string>;
  properties?: ServiceVaultSettingCollection_Value_Properties | Computed<ServiceVaultSettingCollection_Value_Properties>;
}

export interface ServiceVaultSettingCollectionConfig {
  resourceName: string | Computed<string>;
}

export interface ServiceVaultSettingCollectionAttrs {
  /** The link to the next page of items */
  nextLink: string;
  resourceName: string;
  /** The VaultSetting items on this page */
  value: ServiceVaultSettingCollection_Value[];
}

export const ServiceVaultSettingCollection: DataSourceBinding<ServiceVaultSettingCollectionConfig, ServiceVaultSettingCollectionAttrs> = {
  wireType: "azure_recoveryservicessiterecovery_service_vault_setting_collection",
  fields: {
    resourceName: "resource_name",
  },
};
