# Code generated by `ubx sdk gen` from azure_vi_private_link_resource. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class PrivateLinkResource_Properties_PrivateEndpoint:
    # The ARM identifier for private endpoint.
    id: Any = None

@dataclasses.dataclass
class PrivateLinkResource_Properties_PrivateLinkServiceConnectionState:
    # A message indicating if changes on the service provider require any updates on the consumer.
    actions_required: Any = None
    # The reason for approval/rejection of the connection.
    description: Any = None
    # The private endpoint connection status.
    status: Any = None

@dataclasses.dataclass
class PrivateLinkResource_Properties:
    # The group ids for the private endpoint resource.
    group_ids: Any = None
    # The private endpoint resource.
    private_endpoint: Any = None
    # A collection of information about the state of the connection between service consumer and provider.
    private_link_service_connection_state: Any = None
    # The current provisioning state.
    provisioning_state: Any = None

_PrivateLinkResource_Properties_PrivateEndpointFields = {
    "id": ubx.FieldSpec(wire_name="id"),
}

_PrivateLinkResource_Properties_PrivateLinkServiceConnectionStateFields = {
    "actions_required": ubx.FieldSpec(wire_name="actions_required"),
    "description": ubx.FieldSpec(wire_name="description"),
    "status": ubx.FieldSpec(wire_name="status"),
}

_PrivateLinkResource_PropertiesFields = {
    "group_ids": ubx.FieldSpec(wire_name="group_ids"),
    "private_endpoint": ubx.FieldSpec(
        wire_name="private_endpoint",
        kind="object",
        fields=_PrivateLinkResource_Properties_PrivateEndpointFields,
    ),
    "private_link_service_connection_state": ubx.FieldSpec(
        wire_name="private_link_service_connection_state",
        kind="object",
        fields=_PrivateLinkResource_Properties_PrivateLinkServiceConnectionStateFields,
    ),
    "provisioning_state": ubx.FieldSpec(wire_name="provisioning_state"),
}

@dataclasses.dataclass
class PrivateLinkResourceConfig:
    # Properties of the private endpoint connection.
    properties: Any = None

@dataclasses.dataclass
class PrivateLinkResourceAttrs:
    # Properties of the private endpoint connection.
    properties: Any = None

PrivateLinkResource = ubx.ResourceBinding(
    wire_type="azure_vi_private_link_resource",
    fields={
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_PrivateLinkResource_PropertiesFields,
        ),
    },
)
