# Code generated by `ubx sdk gen` from azure_cdn_openapi_route. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OpenapiRoute_Properties_CacheConfiguration_CompressionSettings:
    # List of content types on which compression applies. The value should be a valid MIME type.
    content_types_to_compress: Any = None
    # Indicates whether content compression is enabled on AzureFrontDoor. Default value is false. If compression is enabled, content will be served as compressed if user requests for a compressed version. Content won't be compressed on AzureFrontDoor when requested content is smaller than 1 byte or larger than 1 MB.
    is_compression_enabled: Any = None

@dataclasses.dataclass
class OpenapiRoute_Properties_CacheConfiguration:
    # settings for compression.
    compression_settings: Any = None
    # query parameters to include or exclude (comma separated).
    query_parameters: Any = None
    # Defines how Frontdoor caches requests that include query strings. You can ignore any query strings when caching, ignore specific query strings, cache every request with a unique URL, or cache specific query strings.
    query_string_caching_behavior: Any = None

@dataclasses.dataclass
class OpenapiRoute_Properties_CustomDomains:
    id: Any = None
    is_active: Any = None

@dataclasses.dataclass
class OpenapiRoute_Properties_OriginGroup:
    # Resource ID.
    id: Any = None

@dataclasses.dataclass
class OpenapiRoute_Properties:
    # Caching settings for a caching-type route. To disable caching, do not provide a cacheConfiguration object.
    cache_configuration: Any = None
    # Domains referenced by this endpoint.
    custom_domains: Any = None
    deployment_status: Any = None
    # Whether to enable use of this rule. Permitted values are 'Enabled' or 'Disabled'
    enabled_state: Any = None
    # The name of the endpoint which holds the route.
    endpoint_name: Any = None
    # Protocol this rule will use when forwarding traffic to backends.
    forwarding_protocol: Any = None
    # Whether to automatically redirect HTTP traffic to HTTPS traffic. Note that this is a easy way to set up this rule and it will be the first rule that gets executed.
    https_redirect: Any = None
    # whether this route will be linked to the default endpoint domain.
    link_to_default_domain: Any = None
    # Reference to another resource.
    origin_group: Any = None
    # A directory path on the origin that AzureFrontDoor can use to retrieve content from, e.g. contoso.cloudapp.net/originpath.
    origin_path: Any = None
    # The route patterns of the rule.
    patterns_to_match: Any = None
    # Provisioning status
    provisioning_state: Any = None
    # rule sets referenced by this endpoint.
    rule_sets: Any = None
    # List of supported protocols for this route.
    supported_protocols: Any = None

_OpenapiRoute_Properties_CacheConfiguration_CompressionSettingsFields = {
    "content_types_to_compress": ubx.FieldSpec(wire_name="content_types_to_compress"),
    "is_compression_enabled": ubx.FieldSpec(wire_name="is_compression_enabled"),
}

_OpenapiRoute_Properties_CacheConfigurationFields = {
    "compression_settings": ubx.FieldSpec(
        wire_name="compression_settings",
        kind="object",
        fields=_OpenapiRoute_Properties_CacheConfiguration_CompressionSettingsFields,
    ),
    "query_parameters": ubx.FieldSpec(wire_name="query_parameters"),
    "query_string_caching_behavior": ubx.FieldSpec(wire_name="query_string_caching_behavior"),
}

_OpenapiRoute_Properties_CustomDomainsFields = {
    "id": ubx.FieldSpec(wire_name="id"),
    "is_active": ubx.FieldSpec(wire_name="is_active"),
}

_OpenapiRoute_Properties_OriginGroupFields = {
    "id": ubx.FieldSpec(wire_name="id"),
}

_OpenapiRoute_PropertiesFields = {
    "cache_configuration": ubx.FieldSpec(
        wire_name="cache_configuration",
        kind="object",
        fields=_OpenapiRoute_Properties_CacheConfigurationFields,
    ),
    "custom_domains": ubx.FieldSpec(
        wire_name="custom_domains",
        kind="list",
        fields=_OpenapiRoute_Properties_CustomDomainsFields,
    ),
    "deployment_status": ubx.FieldSpec(wire_name="deployment_status"),
    "enabled_state": ubx.FieldSpec(wire_name="enabled_state"),
    "endpoint_name": ubx.FieldSpec(wire_name="endpoint_name"),
    "forwarding_protocol": ubx.FieldSpec(wire_name="forwarding_protocol"),
    "https_redirect": ubx.FieldSpec(wire_name="https_redirect"),
    "link_to_default_domain": ubx.FieldSpec(wire_name="link_to_default_domain"),
    "origin_group": ubx.FieldSpec(
        wire_name="origin_group",
        kind="object",
        fields=_OpenapiRoute_Properties_OriginGroupFields,
    ),
    "origin_path": ubx.FieldSpec(wire_name="origin_path"),
    "patterns_to_match": ubx.FieldSpec(wire_name="patterns_to_match"),
    "provisioning_state": ubx.FieldSpec(wire_name="provisioning_state"),
    "rule_sets": ubx.FieldSpec(
        wire_name="rule_sets",
        kind="list",
        fields=_OpenapiRoute_Properties_OriginGroupFields,
    ),
    "supported_protocols": ubx.FieldSpec(wire_name="supported_protocols"),
}

@dataclasses.dataclass
class OpenapiRouteConfig:
    # The JSON object that contains the properties of the Routes to create.
    properties: Any = None

@dataclasses.dataclass
class OpenapiRouteAttrs:
    # The JSON object that contains the properties of the Routes to create.
    properties: Any = None

OpenapiRoute = ubx.ResourceBinding(
    wire_type="azure_cdn_openapi_route",
    fields={
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_OpenapiRoute_PropertiesFields,
        ),
    },
)
