# Code generated by `ubx sdk gen` from azure_hdinsight_privateendpointconnections_private_endpoint_connection. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class PrivateendpointconnectionsPrivateEndpointConnection_Value_Properties_PrivateEndpoint:
    id: Any = None

@dataclasses.dataclass
class PrivateendpointconnectionsPrivateEndpointConnection_Value_Properties_PrivateLinkServiceConnectionState:
    actions_required: Any = None
    description: Any = None
    status: Any = None

@dataclasses.dataclass
class PrivateendpointconnectionsPrivateEndpointConnection_Value_Properties:
    link_identifier: Any = None
    private_endpoint: Any = None
    private_link_service_connection_state: Any = None
    provisioning_state: Any = None

@dataclasses.dataclass
class PrivateendpointconnectionsPrivateEndpointConnection_Value_SystemData:
    created_at: Any = None
    created_by: Any = None
    created_by_type: Any = None
    last_modified_at: Any = None
    last_modified_by: Any = None
    last_modified_by_type: Any = None

@dataclasses.dataclass
class PrivateendpointconnectionsPrivateEndpointConnection_Value:
    properties: Any = None
    system_data: Any = None

@dataclasses.dataclass
class PrivateendpointconnectionsPrivateEndpointConnectionConfig:
    api_version: Any = None
    cluster_name: Any = None
    resource_group_name: Any = None
    subscription_id: Any = None

@dataclasses.dataclass
class PrivateendpointconnectionsPrivateEndpointConnectionAttrs:
    api_version: Any = None
    cluster_name: Any = None
    # The link (url) to the next page of results.
    next_link: Any = None
    resource_group_name: Any = None
    subscription_id: Any = None
    # The list of private endpoint connections.
    value: Any = None

PrivateendpointconnectionsPrivateEndpointConnection = ubx.DataSourceBinding(
    wire_type="azure_hdinsight_privateendpointconnections_private_endpoint_connection",
    fields={
        "api_version": ubx.FieldSpec(wire_name="api_version"),
        "cluster_name": ubx.FieldSpec(wire_name="cluster_name"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "subscription_id": ubx.FieldSpec(wire_name="subscription_id"),
    },
)
