// Code generated by `ubx sdk gen` from azure_batch_openapi_private_endpoint_connection_list. DO NOT EDIT.
package batch

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpenapiPrivateEndpointConnectionList_Value_Properties_PrivateEndpoint struct {
	Id any
}

type OpenapiPrivateEndpointConnectionList_Value_Properties_PrivateLinkServiceConnectionState struct {
	ActionsRequired any
	Description any
	Status any
}

type OpenapiPrivateEndpointConnectionList_Value_Properties struct {
	GroupIds any
	PrivateEndpoint any
	PrivateLinkServiceConnectionState any
	ProvisioningState any
}

type OpenapiPrivateEndpointConnectionList_Value struct {
	Etag any
	Properties any
	Tags any
}

type OpenapiPrivateEndpointConnectionListConfig struct {
	AccountName any
	Maxresults any
}

type OpenapiPrivateEndpointConnectionListAttrs struct {
	AccountName any
	Maxresults any
	// The link to the next page of items
	NextLink any
	// The PrivateEndpointConnection items on this page
	Value any
}

var OpenapiPrivateEndpointConnectionList = ubx.DataSourceBinding{
	WireType: "azure_batch_openapi_private_endpoint_connection_list",
	Fields: ubx.FieldMap{
		"AccountName": ubx.FieldSpec{WireName: "account_name"},
		"Maxresults": ubx.FieldSpec{WireName: "maxresults"},
	},
}
