// Code generated by `ubx sdk gen` from azurerm_backup_policy_vm. DO NOT EDIT.
package backup

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type PolicyVm_Backup struct {
	Frequency any
	HourDuration any
	HourInterval any
	Time any
	Weekdays any
}

type PolicyVm_InstantRestoreResourceGroup struct {
	Prefix any
	Suffix any
}

type PolicyVm_RetentionDaily struct {
	Count any
}

type PolicyVm_RetentionMonthly struct {
	Count any
	Days any
	IncludeLastDays any
	Weekdays any
	Weeks any
}

type PolicyVm_RetentionWeekly struct {
	Count any
	Weekdays any
}

type PolicyVm_RetentionYearly struct {
	Count any
	Days any
	IncludeLastDays any
	Months any
	Weekdays any
	Weeks any
}

type PolicyVm_TieringPolicy_ArchivedRestorePoint struct {
	Duration any
	DurationType any
	Mode any
}

type PolicyVm_TieringPolicy struct {
	ArchivedRestorePoint any
}

type PolicyVm_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var PolicyVm_BackupFields = ubx.FieldMap{
		"Frequency": ubx.FieldSpec{WireName: "frequency"},
		"HourDuration": ubx.FieldSpec{WireName: "hour_duration"},
		"HourInterval": ubx.FieldSpec{WireName: "hour_interval"},
		"Time": ubx.FieldSpec{WireName: "time"},
		"Weekdays": ubx.FieldSpec{WireName: "weekdays"},
	}

var PolicyVm_InstantRestoreResourceGroupFields = ubx.FieldMap{
		"Prefix": ubx.FieldSpec{WireName: "prefix"},
		"Suffix": ubx.FieldSpec{WireName: "suffix"},
	}

var PolicyVm_RetentionDailyFields = ubx.FieldMap{
		"Count": ubx.FieldSpec{WireName: "count"},
	}

var PolicyVm_RetentionMonthlyFields = ubx.FieldMap{
		"Count": ubx.FieldSpec{WireName: "count"},
		"Days": ubx.FieldSpec{WireName: "days"},
		"IncludeLastDays": ubx.FieldSpec{WireName: "include_last_days"},
		"Weekdays": ubx.FieldSpec{WireName: "weekdays"},
		"Weeks": ubx.FieldSpec{WireName: "weeks"},
	}

var PolicyVm_RetentionWeeklyFields = ubx.FieldMap{
		"Count": ubx.FieldSpec{WireName: "count"},
		"Weekdays": ubx.FieldSpec{WireName: "weekdays"},
	}

var PolicyVm_RetentionYearlyFields = ubx.FieldMap{
		"Count": ubx.FieldSpec{WireName: "count"},
		"Days": ubx.FieldSpec{WireName: "days"},
		"IncludeLastDays": ubx.FieldSpec{WireName: "include_last_days"},
		"Months": ubx.FieldSpec{WireName: "months"},
		"Weekdays": ubx.FieldSpec{WireName: "weekdays"},
		"Weeks": ubx.FieldSpec{WireName: "weeks"},
	}

var PolicyVm_TieringPolicy_ArchivedRestorePointFields = ubx.FieldMap{
		"Duration": ubx.FieldSpec{WireName: "duration"},
		"DurationType": ubx.FieldSpec{WireName: "duration_type"},
		"Mode": ubx.FieldSpec{WireName: "mode"},
	}

var PolicyVm_TieringPolicyFields = ubx.FieldMap{
		"ArchivedRestorePoint": ubx.FieldSpec{
			WireName: "archived_restore_point",
			Kind: "list",
			Fields: PolicyVm_TieringPolicy_ArchivedRestorePointFields,
		},
	}

var PolicyVm_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Read": ubx.FieldSpec{WireName: "read"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

type PolicyVmConfig struct {
	ConsistencyType any
	Id any
	InstantRestoreRetentionDays any
	Name any
	PolicyType any
	RecoveryVaultName any
	ResourceGroupName any
	Timezone any
	Backup any
	InstantRestoreResourceGroup any
	RetentionDaily any
	RetentionMonthly any
	RetentionWeekly any
	RetentionYearly any
	TieringPolicy any
	Timeouts any
}

var PolicyVm = ubx.ResourceBinding{
	WireType: "azurerm_backup_policy_vm",
	Fields: ubx.FieldMap{
		"ConsistencyType": ubx.FieldSpec{WireName: "consistency_type"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"InstantRestoreRetentionDays": ubx.FieldSpec{WireName: "instant_restore_retention_days"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"PolicyType": ubx.FieldSpec{WireName: "policy_type"},
		"RecoveryVaultName": ubx.FieldSpec{WireName: "recovery_vault_name"},
		"ResourceGroupName": ubx.FieldSpec{WireName: "resource_group_name"},
		"Timezone": ubx.FieldSpec{WireName: "timezone"},
		"Backup": ubx.FieldSpec{
			WireName: "backup",
			Kind: "list",
			Fields: PolicyVm_BackupFields,
		},
		"InstantRestoreResourceGroup": ubx.FieldSpec{
			WireName: "instant_restore_resource_group",
			Kind: "list",
			Fields: PolicyVm_InstantRestoreResourceGroupFields,
		},
		"RetentionDaily": ubx.FieldSpec{
			WireName: "retention_daily",
			Kind: "list",
			Fields: PolicyVm_RetentionDailyFields,
		},
		"RetentionMonthly": ubx.FieldSpec{
			WireName: "retention_monthly",
			Kind: "list",
			Fields: PolicyVm_RetentionMonthlyFields,
		},
		"RetentionWeekly": ubx.FieldSpec{
			WireName: "retention_weekly",
			Kind: "list",
			Fields: PolicyVm_RetentionWeeklyFields,
		},
		"RetentionYearly": ubx.FieldSpec{
			WireName: "retention_yearly",
			Kind: "list",
			Fields: PolicyVm_RetentionYearlyFields,
		},
		"TieringPolicy": ubx.FieldSpec{
			WireName: "tiering_policy",
			Kind: "list",
			Fields: PolicyVm_TieringPolicyFields,
		},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: PolicyVm_TimeoutsFields,
		},
	},
}
