// Code generated by `ubx sdk gen` from azure_hybridcompute_openapi_machine. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface OpenapiMachine_Identity_UserAssignedIdentities {
  /** The client (application) ID of the user-assigned managed identity to use. (AI-inferred) */
  clientId?: string | Computed<string>;
  /** Output only. The Microsoft Entra ID object ID of this resource's own managed identity or service principal. (AI-inferred) */
  principalId?: string | Computed<string>;
}

export interface OpenapiMachine_Identity {
  /** The service principal ID of the system assigned identity. This property will only be provided for a system assigned identity. */
  principalId?: string | Computed<string>;
  /** The tenant ID of the system assigned identity. This property will only be provided for a system assigned identity. */
  tenantId?: string | Computed<string>;
  /** Type of managed service identity (where both SystemAssigned and UserAssigned types are allowed). */
  type: string | Computed<string>;
  /** The set of user assigned identities associated with the resource. The userAssignedIdentities dictionary keys will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}. The dictionary values can be empty objects ({}) in requests. */
  userAssignedIdentities?: Record<string, OpenapiMachine_Identity_UserAssignedIdentities> | Computed<Record<string, OpenapiMachine_Identity_UserAssignedIdentities>>;
}

export interface OpenapiMachine_Properties_AgentConfiguration_ExtensionsAllowList {
  /** The publisher of this VM extension. (AI-inferred) */
  publisher?: string | Computed<string>;
  /** The Azure resource type, in the form `{resource-provider}/{resource-type}`, e.g. `Microsoft.Network/loadBalancers`. (AI-inferred) */
  type?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_AgentConfiguration {
  /** Name of configuration mode to use. Modes are pre-defined configurations of security controls, extension allowlists and guest configuration, maintained by Microsoft. */
  configMode?: string | Computed<string>;
  /** Array of extensions that are allowed to be installed or updated. */
  extensionsAllowList?: OpenapiMachine_Properties_AgentConfiguration_ExtensionsAllowList[] | Computed<OpenapiMachine_Properties_AgentConfiguration_ExtensionsAllowList[]>;
  /** Array of extensions that are blocked (cannot be installed or updated) */
  extensionsBlockList?: OpenapiMachine_Properties_AgentConfiguration_ExtensionsAllowList[] | Computed<OpenapiMachine_Properties_AgentConfiguration_ExtensionsAllowList[]>;
  /** Specifies whether the extension service is enabled or disabled. */
  extensionsEnabled?: string | Computed<string>;
  /** Specified whether the guest configuration service is enabled or disabled. */
  guestConfigurationEnabled?: string | Computed<string>;
  /** Specifies the list of ports that the agent will be able to listen on. */
  incomingConnectionsPorts?: string[] | Computed<string[]>;
  /** List of service names which should not use the specified proxy server. */
  proxyBypass?: string[] | Computed<string[]>;
  /** Specifies the URL of the proxy to be used. */
  proxyUrl?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_AgentUpgrade {
  /** The correlation ID associated with an agent upgrade operation. */
  correlationId?: string | Computed<string>;
  /** Specifies the version info w.r.t AgentUpgrade for the machine. */
  desiredVersion?: string | Computed<string>;
  /** Specifies if the machine's agent should be upgraded */
  enableAutomaticUpgrade?: boolean | Computed<boolean>;
  /** Specifies the version of the last attempt */
  lastAttemptDesiredVersion?: string | Computed<string>;
  /** Failure message of last upgrade attempt if any. */
  lastAttemptMessage?: string | Computed<string>;
  /** Specifies the status of Agent Upgrade. */
  lastAttemptStatus?: string | Computed<string>;
  /** Timestamp of last upgrade attempt */
  lastAttemptTimestamp?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_CloudMetadata {
  /** Specifies the cloud provider (Azure/AWS/GCP...). */
  provider?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_ErrorDetails_AdditionalInfo {
  /** Additional detail about this result. (AI-inferred) */
  info?: unknown | Computed<unknown>;
  /** The Azure resource type, in the form `{resource-provider}/{resource-type}`, e.g. `Microsoft.Network/loadBalancers`. (AI-inferred) */
  type?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_ErrorDetails_Details_Details {
}

export interface OpenapiMachine_Properties_ErrorDetails_Details {
  /** Additional detail about this result. (AI-inferred) */
  additionalInfo?: OpenapiMachine_Properties_ErrorDetails_AdditionalInfo[] | Computed<OpenapiMachine_Properties_ErrorDetails_AdditionalInfo[]>;
  /** A machine-readable status or error code. (AI-inferred) */
  code?: string | Computed<string>;
  /** Additional detail about this result. (AI-inferred) */
  details?: OpenapiMachine_Properties_ErrorDetails_Details_Details[] | Computed<OpenapiMachine_Properties_ErrorDetails_Details_Details[]>;
  /** A human-readable description of this result. (AI-inferred) */
  message?: string | Computed<string>;
  /** A reference to the resource this operation targets. (AI-inferred) */
  target?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_ErrorDetails {
  /** Additional detail about this result. (AI-inferred) */
  additionalInfo?: OpenapiMachine_Properties_ErrorDetails_AdditionalInfo[] | Computed<OpenapiMachine_Properties_ErrorDetails_AdditionalInfo[]>;
  /** A machine-readable status or error code. (AI-inferred) */
  code?: string | Computed<string>;
  /** Additional detail about this result. (AI-inferred) */
  details?: OpenapiMachine_Properties_ErrorDetails_Details[] | Computed<OpenapiMachine_Properties_ErrorDetails_Details[]>;
  /** A human-readable description of this result. (AI-inferred) */
  message?: string | Computed<string>;
  /** A reference to the resource this operation targets. (AI-inferred) */
  target?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_Extensions_Status {
  /** A machine-readable status or error code. (AI-inferred) */
  code?: string | Computed<string>;
  /** A human-readable summary of this status. (AI-inferred) */
  displayStatus?: string | Computed<string>;
  /** The severity level of this status, e.g. `Info`, `Warning`, or `Error`. (AI-inferred) */
  level?: string | Computed<string>;
  /** A human-readable description of this result. (AI-inferred) */
  message?: string | Computed<string>;
  /** When this status was last reported. (AI-inferred) */
  time?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_Extensions {
  /** The resource's own name, unique within its parent scope. (AI-inferred) */
  name?: string | Computed<string>;
  /** The current status of this resource. (AI-inferred) */
  status?: OpenapiMachine_Properties_Extensions_Status | Computed<OpenapiMachine_Properties_Extensions_Status>;
  /** The Azure resource type, in the form `{resource-provider}/{resource-type}`, e.g. `Microsoft.Network/loadBalancers`. (AI-inferred) */
  type?: string | Computed<string>;
  /** The version of the extension handler. (AI-inferred) */
  typeHandlerVersion?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_FirmwareProfile {
  /** The serial number of the firmware */
  serialNumber?: string | Computed<string>;
  /** The type of the firmware */
  type?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_HardwareProfile_Processors {
  /** The resource's own name, unique within its parent scope. (AI-inferred) */
  name?: string | Computed<string>;
  /** The number of processor cores. (AI-inferred) */
  numberOfCores?: number | Computed<number>;
}

export interface OpenapiMachine_Properties_HardwareProfile {
  /** The total number of CPU sockets available on the machine */
  numberOfCpuSockets?: number | Computed<number>;
  /** The physical processors of the machine. */
  processors?: OpenapiMachine_Properties_HardwareProfile_Processors[] | Computed<OpenapiMachine_Properties_HardwareProfile_Processors[]>;
  /** The total physical memory on the machine */
  totalPhysicalMemoryInBytes?: number | Computed<number>;
}

export interface OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense_Properties_LicenseDetails_VolumeLicenseDetails {
  /** The invoice number associated with this volume license. (AI-inferred) */
  invoiceId?: string | Computed<string>;
  /** The program year this Software Assurance/subscription benefit applies to. (AI-inferred) */
  programYear?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense_Properties_LicenseDetails {
  /** Describes the number of assigned licenses. */
  assignedLicenses?: number | Computed<number>;
  /** Describes the edition of the license. The values are either Standard or Datacenter. */
  edition?: string | Computed<string>;
  /** Describes the immutable id. */
  immutableId?: string | Computed<string>;
  /** Describes the number of processors. */
  processors?: number | Computed<number>;
  /** Describes the state of the license. */
  state?: string | Computed<string>;
  /** Describes the license target server. */
  target?: string | Computed<string>;
  /** Describes the license core type (pCore or vCore). */
  type?: string | Computed<string>;
  /** A list of volume license details. */
  volumeLicenseDetails?: OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense_Properties_LicenseDetails_VolumeLicenseDetails[] | Computed<OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense_Properties_LicenseDetails_VolumeLicenseDetails[]>;
}

export interface OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense_Properties {
  /** Describes the properties of a License. */
  licenseDetails?: OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense_Properties_LicenseDetails | Computed<OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense_Properties_LicenseDetails>;
  /** The type of the license resource. */
  licenseType?: string | Computed<string>;
  /** The provisioning state, which only appears in the response. */
  provisioningState?: string | Computed<string>;
  /** Describes the tenant id. */
  tenantId?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense {
  /** Describes the properties of a License Profile. */
  properties?: OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense_Properties | Computed<OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense_Properties>;
}

export interface OpenapiMachine_Properties_LicenseProfile_EsuProfile {
  /** Describes a license in a hybrid machine. */
  assignedLicense?: OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense | Computed<OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense>;
  /** Describes the license assignment state (Assigned or NotAssigned). */
  licenseAssignmentState?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_LicenseProfile_ProductProfile_ProductFeatures {
  /** When billing for this product feature ends. (AI-inferred) */
  billingEndDate?: string | Computed<string>;
  /** When billing for this product feature starts. (AI-inferred) */
  billingStartDate?: string | Computed<string>;
  /** When this machine was disenrolled from this product feature. (AI-inferred) */
  disenrollmentDate?: string | Computed<string>;
  /** When this machine was enrolled in this product feature. (AI-inferred) */
  enrollmentDate?: string | Computed<string>;
  /** Detail about an error that occurred. (AI-inferred) */
  error?: OpenapiMachine_Properties_ErrorDetails | Computed<OpenapiMachine_Properties_ErrorDetails>;
  /** The resource's own name, unique within its parent scope. (AI-inferred) */
  name?: string | Computed<string>;
  /** This product feature's own current subscription status. (AI-inferred) */
  subscriptionStatus?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_LicenseProfile_ProductProfile {
  /** The timestamp in UTC when the billing ends. */
  billingEndDate?: string | Computed<string>;
  /** The timestamp in UTC when the billing starts. */
  billingStartDate?: string | Computed<string>;
  /** The timestamp in UTC when the user disenrolled the feature. */
  disenrollmentDate?: string | Computed<string>;
  /** The timestamp in UTC when the user enrolls the feature. */
  enrollmentDate?: string | Computed<string>;
  /** The error detail. */
  error?: OpenapiMachine_Properties_ErrorDetails | Computed<OpenapiMachine_Properties_ErrorDetails>;
  /** The list of product features. */
  productFeatures?: OpenapiMachine_Properties_LicenseProfile_ProductProfile_ProductFeatures[] | Computed<OpenapiMachine_Properties_LicenseProfile_ProductProfile_ProductFeatures[]>;
  /** The product type of the license. */
  productType?: string | Computed<string>;
  /** Subscription status of the OS or Product feature. */
  subscriptionStatus?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_LicenseProfile_SoftwareAssurance {
  /** Specifies if this machine is licensed as part of a Software Assurance agreement. */
  softwareAssuranceCustomer?: boolean | Computed<boolean>;
}

export interface OpenapiMachine_Properties_LicenseProfile {
  /** Properties for the Machine ESU profile. */
  esuProfile?: OpenapiMachine_Properties_LicenseProfile_EsuProfile | Computed<OpenapiMachine_Properties_LicenseProfile_EsuProfile>;
  /** Indicates the license channel. */
  licenseChannel?: string | Computed<string>;
  /** The license status. */
  licenseStatus?: string | Computed<string>;
  /** Describes the properties of a Product License Profile ARM model. */
  productProfile?: OpenapiMachine_Properties_LicenseProfile_ProductProfile | Computed<OpenapiMachine_Properties_LicenseProfile_ProductProfile>;
  /** This machine's Software Assurance/subscription benefit status, used to determine Extended Security Update eligibility. (AI-inferred) */
  softwareAssurance?: OpenapiMachine_Properties_LicenseProfile_SoftwareAssurance | Computed<OpenapiMachine_Properties_LicenseProfile_SoftwareAssurance>;
}

export interface OpenapiMachine_Properties_LocationData {
  /** The city or locality where the resource is located. */
  city?: string | Computed<string>;
  /** The country or region where the resource is located */
  countryOrRegion?: string | Computed<string>;
  /** The district, state, or province where the resource is located. */
  district?: string | Computed<string>;
  /** A canonical name for the geographic or physical location. */
  name: string | Computed<string>;
}

export interface OpenapiMachine_Properties_NetworkProfile_NetworkInterfaces_IpAddresses_Subnet {
  /** The subnet's own address range, in CIDR notation. (AI-inferred) */
  addressPrefix?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_NetworkProfile_NetworkInterfaces_IpAddresses {
  /** The literal IP address. (AI-inferred) */
  address?: string | Computed<string>;
  /** Whether this is an IPv4 or IPv6 address. (AI-inferred) */
  ipAddressVersion?: string | Computed<string>;
  /** The subnet this IP address belongs to. (AI-inferred) */
  subnet?: OpenapiMachine_Properties_NetworkProfile_NetworkInterfaces_IpAddresses_Subnet | Computed<OpenapiMachine_Properties_NetworkProfile_NetworkInterfaces_IpAddresses_Subnet>;
}

export interface OpenapiMachine_Properties_NetworkProfile_NetworkInterfaces {
  /** The fully qualified Azure Resource Manager resource ID, in the form `/subscriptions/{id}/resourceGroups/{group}/providers/{provider}/.../{name}`. (AI-inferred) */
  id?: string | Computed<string>;
  /** The IP address(es) assigned to this network interface. (AI-inferred) */
  ipAddresses?: OpenapiMachine_Properties_NetworkProfile_NetworkInterfaces_IpAddresses[] | Computed<OpenapiMachine_Properties_NetworkProfile_NetworkInterfaces_IpAddresses[]>;
  /** This network interface's own MAC address. (AI-inferred) */
  macAddress?: string | Computed<string>;
  /** The resource's own name, unique within its parent scope. (AI-inferred) */
  name?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_NetworkProfile {
  /** The list of network interfaces. */
  networkInterfaces?: OpenapiMachine_Properties_NetworkProfile_NetworkInterfaces[] | Computed<OpenapiMachine_Properties_NetworkProfile_NetworkInterfaces[]>;
}

export interface OpenapiMachine_Properties_OsProfile_LinuxConfiguration_PatchSettings_Status {
  /** The error detail. */
  error?: OpenapiMachine_Properties_ErrorDetails | Computed<OpenapiMachine_Properties_ErrorDetails>;
  /** Status of hotpatch enablement or disablement. */
  hotpatchEnablementStatus?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_OsProfile_LinuxConfiguration_PatchSettings {
  /** Specifies the assessment mode. */
  assessmentMode?: string | Computed<string>;
  /** Captures the hotpatch capability enrollment intent of the customers, which enables customers to patch their Windows machines without requiring a reboot. */
  enableHotpatching?: boolean | Computed<boolean>;
  /** Specifies the patch mode. */
  patchMode?: string | Computed<string>;
  /** Status of the hotpatch capability enrollment or disenrollment. */
  status?: OpenapiMachine_Properties_OsProfile_LinuxConfiguration_PatchSettings_Status | Computed<OpenapiMachine_Properties_OsProfile_LinuxConfiguration_PatchSettings_Status>;
}

export interface OpenapiMachine_Properties_OsProfile_LinuxConfiguration {
  /** Specifies the patch settings. */
  patchSettings?: OpenapiMachine_Properties_OsProfile_LinuxConfiguration_PatchSettings | Computed<OpenapiMachine_Properties_OsProfile_LinuxConfiguration_PatchSettings>;
}

export interface OpenapiMachine_Properties_OsProfile {
  /** Specifies the host OS name of the hybrid machine. */
  computerName?: string | Computed<string>;
  /** Specifies the linux configuration for update management. */
  linuxConfiguration?: OpenapiMachine_Properties_OsProfile_LinuxConfiguration | Computed<OpenapiMachine_Properties_OsProfile_LinuxConfiguration>;
  /** Specifies the windows configuration for update management. */
  windowsConfiguration?: OpenapiMachine_Properties_OsProfile_LinuxConfiguration | Computed<OpenapiMachine_Properties_OsProfile_LinuxConfiguration>;
}

export interface OpenapiMachine_Properties_ServiceStatuses_ExtensionService {
  /** The behavior of the service when the Arc-enabled machine starts up. */
  startupType?: string | Computed<string>;
  /** The current status of the service. */
  status?: string | Computed<string>;
}

export interface OpenapiMachine_Properties_ServiceStatuses {
  /** Describes the status and behavior of a service. */
  extensionService?: OpenapiMachine_Properties_ServiceStatuses_ExtensionService | Computed<OpenapiMachine_Properties_ServiceStatuses_ExtensionService>;
  /** Describes the status and behavior of a service. */
  guestConfigurationService?: OpenapiMachine_Properties_ServiceStatuses_ExtensionService | Computed<OpenapiMachine_Properties_ServiceStatuses_ExtensionService>;
}

export interface OpenapiMachine_Properties_StorageProfile_Disks {
  /** The type of this disk, e.g. `Managed` or `Unmanaged`. (AI-inferred) */
  diskType?: string | Computed<string>;
  /** A machine-generated unique identifier for this disk. (AI-inferred) */
  generatedId?: string | Computed<string>;
  /** The fully qualified Azure Resource Manager resource ID, in the form `/subscriptions/{id}/resourceGroups/{group}/providers/{provider}/.../{name}`. (AI-inferred) */
  id?: string | Computed<string>;
  /** This disk's own maximum size, in bytes. (AI-inferred) */
  maxSizeInBytes?: number | Computed<number>;
  /** The resource's own name, unique within its parent scope. (AI-inferred) */
  name?: string | Computed<string>;
  /** This disk's own file system path. (AI-inferred) */
  path?: string | Computed<string>;
  /** This disk's own currently-used space, in bytes. (AI-inferred) */
  usedSpaceInBytes?: number | Computed<number>;
}

export interface OpenapiMachine_Properties_StorageProfile {
  /** The disks on the machine. */
  disks?: OpenapiMachine_Properties_StorageProfile_Disks[] | Computed<OpenapiMachine_Properties_StorageProfile_Disks[]>;
}

export interface OpenapiMachine_Properties {
  /** Specifies the AD fully qualified display name. */
  adFqdn?: string | Computed<string>;
  /** Configurable properties that the user can set locally via the azcmagent config command, or remotely via ARM. */
  agentConfiguration?: OpenapiMachine_Properties_AgentConfiguration | Computed<OpenapiMachine_Properties_AgentConfiguration>;
  /** The info w.r.t Agent Upgrade. */
  agentUpgrade?: OpenapiMachine_Properties_AgentUpgrade | Computed<OpenapiMachine_Properties_AgentUpgrade>;
  /** The hybrid machine agent full version. */
  agentVersion?: string | Computed<string>;
  /** Public Key that the client provides to be used during initial resource onboarding */
  clientPublicKey?: string | Computed<string>;
  /** The metadata of the cloud environment (Azure/GCP/AWS/OCI...). */
  cloudMetadata?: OpenapiMachine_Properties_CloudMetadata | Computed<OpenapiMachine_Properties_CloudMetadata>;
  /** Detected properties from the machine. */
  detectedProperties?: Record<string, string> | Computed<Record<string, string>>;
  /** Specifies the hybrid machine display name. */
  displayName?: string | Computed<string>;
  /** Specifies the DNS fully qualified display name. */
  dnsFqdn?: string | Computed<string>;
  /** Specifies the Windows domain name. */
  domainName?: string | Computed<string>;
  /** Details about the error state. */
  errorDetails?: OpenapiMachine_Properties_ErrorDetails[] | Computed<OpenapiMachine_Properties_ErrorDetails[]>;
  /** Machine Extensions information (deprecated field) */
  extensions?: OpenapiMachine_Properties_Extensions[] | Computed<OpenapiMachine_Properties_Extensions[]>;
  /** Describes the firmware of the machine */
  firmwareProfile?: OpenapiMachine_Properties_FirmwareProfile | Computed<OpenapiMachine_Properties_FirmwareProfile>;
  /** Describes the hardware of the machine */
  hardwareProfile?: OpenapiMachine_Properties_HardwareProfile | Computed<OpenapiMachine_Properties_HardwareProfile>;
  /** Specifies the resource ID of the associated hardware device. Only settable by HCI RP. */
  hardwareResourceId?: string | Computed<string>;
  /** Specifies the identity key store a machine is using. */
  identityKeyStore?: string | Computed<string>;
  /** The time of the last status change. */
  lastStatusChange?: string | Computed<string>;
  /** License Profile Instance View in Machine Properties. */
  licenseProfile?: OpenapiMachine_Properties_LicenseProfile | Computed<OpenapiMachine_Properties_LicenseProfile>;
  /** Metadata pertaining to the geographic location of the resource. */
  locationData?: OpenapiMachine_Properties_LocationData | Computed<OpenapiMachine_Properties_LocationData>;
  /** Specifies the hybrid machine FQDN. */
  machineFqdn?: string | Computed<string>;
  /** Specifies whether any MS SQL instance is discovered on the machine. */
  mssqlDiscovered?: string | Computed<string>;
  /** Describes the network information on this machine. */
  networkProfile?: OpenapiMachine_Properties_NetworkProfile | Computed<OpenapiMachine_Properties_NetworkProfile>;
  /** The edition of the Operating System. */
  osEdition?: string | Computed<string>;
  /** The Operating System running on the hybrid machine. */
  osName?: string | Computed<string>;
  /** Specifies the operating system settings for the hybrid machine. */
  osProfile?: OpenapiMachine_Properties_OsProfile | Computed<OpenapiMachine_Properties_OsProfile>;
  /** Specifies the Operating System product SKU. */
  osSku?: string | Computed<string>;
  /** The type of Operating System (windows/linux). */
  osType?: string | Computed<string>;
  /** The version of Operating System running on the hybrid machine. */
  osVersion?: string | Computed<string>;
  /** The resource id of the parent cluster (Azure HCI) this machine is assigned to, if any. */
  parentClusterResourceId?: string | Computed<string>;
  /** The resource id of the private link scope this machine is assigned to, if any. */
  privateLinkScopeResourceId?: string | Computed<string>;
  /** The provisioning state, which only appears in the response. */
  provisioningState?: string | Computed<string>;
  /** Reports the state and behavior of dependent services. */
  serviceStatuses?: OpenapiMachine_Properties_ServiceStatuses | Computed<OpenapiMachine_Properties_ServiceStatuses>;
  /** The status of the hybrid machine agent. */
  status?: string | Computed<string>;
  /** The reason describing why the service set the machine status to a particular value. */
  statusReason?: string | Computed<string>;
  /** Describes the storage configuration of the machine */
  storageProfile?: OpenapiMachine_Properties_StorageProfile | Computed<OpenapiMachine_Properties_StorageProfile>;
  /** Endorsement Key Certificate of the Trusted Platform Module (TPM) that the client provides to be used during initial resource onboarding. */
  tpmEkCertificate?: string | Computed<string>;
  /** Specifies the hybrid machine unique ID. */
  vmId?: string | Computed<string>;
  /** Specifies the Arc Machine's unique SMBIOS ID */
  vmUuid?: string | Computed<string>;
}

export interface OpenapiMachine_Resources_Properties {
  /** Whether this extension automatically upgrades to the latest minor version as new versions become available. (AI-inferred) */
  autoUpgradeMinorVersion?: boolean | Computed<boolean>;
  /** Whether Azure automatically upgrades this extension to newer versions as they're released. (AI-inferred) */
  enableAutomaticUpgrade?: boolean | Computed<boolean>;
  /** An opaque value that, when changed, forces this extension to re-run even though its own configuration is otherwise unchanged. (AI-inferred) */
  forceUpdateTag?: string | Computed<string>;
  /** Real-time status information about this extension's own current runtime state. (AI-inferred) */
  instanceView?: OpenapiMachine_Properties_Extensions | Computed<OpenapiMachine_Properties_Extensions>;
  /** Extension-specific configuration that's encrypted before being sent to the machine, never returned on a read. (AI-inferred) */
  protectedSettings?: Record<string, unknown> | Computed<Record<string, unknown>>;
  /** The last, current provisioning status ARM reported for this resource, e.g. `Succeeded`, `Failed`, or `Updating`. (AI-inferred) */
  provisioningState?: string | Computed<string>;
  /** The publisher of this VM extension. (AI-inferred) */
  publisher?: string | Computed<string>;
  /** Extension-specific configuration, in JSON. (AI-inferred) */
  settings?: Record<string, unknown> | Computed<Record<string, unknown>>;
  /** The Azure resource type, in the form `{resource-provider}/{resource-type}`, e.g. `Microsoft.Network/loadBalancers`. (AI-inferred) */
  type?: string | Computed<string>;
  /** The version of the extension handler. (AI-inferred) */
  typeHandlerVersion?: string | Computed<string>;
}

export interface OpenapiMachine_Resources {
  /** The resource type-specific configuration for this resource, wrapping every field that isn't part of ARM's own standard envelope (id/name/type/location/tags). (AI-inferred) */
  properties?: OpenapiMachine_Resources_Properties | Computed<OpenapiMachine_Resources_Properties>;
}

const OpenapiMachine_Identity_UserAssignedIdentitiesFields: FieldMap = {
  clientId: "client_id",
  principalId: "principal_id",
};

const OpenapiMachine_IdentityFields: FieldMap = {
  principalId: "principal_id",
  tenantId: "tenant_id",
  type: "type",
  userAssignedIdentities: {
    wireName: "user_assigned_identities",
    kind: "map",
    fields: OpenapiMachine_Identity_UserAssignedIdentitiesFields,
  },
};

const OpenapiMachine_Properties_AgentConfiguration_ExtensionsAllowListFields: FieldMap = {
  publisher: "publisher",
  type: "type",
};

const OpenapiMachine_Properties_AgentConfigurationFields: FieldMap = {
  configMode: "config_mode",
  extensionsAllowList: {
    wireName: "extensions_allow_list",
    kind: "list",
    fields: OpenapiMachine_Properties_AgentConfiguration_ExtensionsAllowListFields,
  },
  extensionsBlockList: {
    wireName: "extensions_block_list",
    kind: "list",
    fields: OpenapiMachine_Properties_AgentConfiguration_ExtensionsAllowListFields,
  },
  extensionsEnabled: "extensions_enabled",
  guestConfigurationEnabled: "guest_configuration_enabled",
  incomingConnectionsPorts: "incoming_connections_ports",
  proxyBypass: "proxy_bypass",
  proxyUrl: "proxy_url",
};

const OpenapiMachine_Properties_AgentUpgradeFields: FieldMap = {
  correlationId: "correlation_id",
  desiredVersion: "desired_version",
  enableAutomaticUpgrade: "enable_automatic_upgrade",
  lastAttemptDesiredVersion: "last_attempt_desired_version",
  lastAttemptMessage: "last_attempt_message",
  lastAttemptStatus: "last_attempt_status",
  lastAttemptTimestamp: "last_attempt_timestamp",
};

const OpenapiMachine_Properties_CloudMetadataFields: FieldMap = {
  provider: "provider",
};

const OpenapiMachine_Properties_ErrorDetails_AdditionalInfoFields: FieldMap = {
  info: "info",
  type: "type",
};

const OpenapiMachine_Properties_ErrorDetails_Details_DetailsFields: FieldMap = {
};

const OpenapiMachine_Properties_ErrorDetails_DetailsFields: FieldMap = {
  additionalInfo: {
    wireName: "additional_info",
    kind: "list",
    fields: OpenapiMachine_Properties_ErrorDetails_AdditionalInfoFields,
  },
  code: "code",
  details: {
    wireName: "details",
    kind: "list",
    fields: OpenapiMachine_Properties_ErrorDetails_Details_DetailsFields,
  },
  message: "message",
  target: "target",
};

const OpenapiMachine_Properties_ErrorDetailsFields: FieldMap = {
  additionalInfo: {
    wireName: "additional_info",
    kind: "list",
    fields: OpenapiMachine_Properties_ErrorDetails_AdditionalInfoFields,
  },
  code: "code",
  details: {
    wireName: "details",
    kind: "list",
    fields: OpenapiMachine_Properties_ErrorDetails_DetailsFields,
  },
  message: "message",
  target: "target",
};

const OpenapiMachine_Properties_Extensions_StatusFields: FieldMap = {
  code: "code",
  displayStatus: "display_status",
  level: "level",
  message: "message",
  time: "time",
};

const OpenapiMachine_Properties_ExtensionsFields: FieldMap = {
  name: "name",
  status: {
    wireName: "status",
    kind: "object",
    fields: OpenapiMachine_Properties_Extensions_StatusFields,
  },
  type: "type",
  typeHandlerVersion: "type_handler_version",
};

const OpenapiMachine_Properties_FirmwareProfileFields: FieldMap = {
  serialNumber: "serial_number",
  type: "type",
};

const OpenapiMachine_Properties_HardwareProfile_ProcessorsFields: FieldMap = {
  name: "name",
  numberOfCores: "number_of_cores",
};

const OpenapiMachine_Properties_HardwareProfileFields: FieldMap = {
  numberOfCpuSockets: "number_of_cpu_sockets",
  processors: {
    wireName: "processors",
    kind: "list",
    fields: OpenapiMachine_Properties_HardwareProfile_ProcessorsFields,
  },
  totalPhysicalMemoryInBytes: "total_physical_memory_in_bytes",
};

const OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense_Properties_LicenseDetails_VolumeLicenseDetailsFields: FieldMap = {
  invoiceId: "invoice_id",
  programYear: "program_year",
};

const OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense_Properties_LicenseDetailsFields: FieldMap = {
  assignedLicenses: "assigned_licenses",
  edition: "edition",
  immutableId: "immutable_id",
  processors: "processors",
  state: "state",
  target: "target",
  type: "type",
  volumeLicenseDetails: {
    wireName: "volume_license_details",
    kind: "list",
    fields: OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense_Properties_LicenseDetails_VolumeLicenseDetailsFields,
  },
};

const OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense_PropertiesFields: FieldMap = {
  licenseDetails: {
    wireName: "license_details",
    kind: "object",
    fields: OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense_Properties_LicenseDetailsFields,
  },
  licenseType: "license_type",
  provisioningState: "provisioning_state",
  tenantId: "tenant_id",
};

const OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicenseFields: FieldMap = {
  properties: {
    wireName: "properties",
    kind: "object",
    fields: OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicense_PropertiesFields,
  },
};

const OpenapiMachine_Properties_LicenseProfile_EsuProfileFields: FieldMap = {
  assignedLicense: {
    wireName: "assigned_license",
    kind: "object",
    fields: OpenapiMachine_Properties_LicenseProfile_EsuProfile_AssignedLicenseFields,
  },
  licenseAssignmentState: "license_assignment_state",
};

const OpenapiMachine_Properties_LicenseProfile_ProductProfile_ProductFeaturesFields: FieldMap = {
  billingEndDate: "billing_end_date",
  billingStartDate: "billing_start_date",
  disenrollmentDate: "disenrollment_date",
  enrollmentDate: "enrollment_date",
  error: {
    wireName: "error",
    kind: "object",
    fields: OpenapiMachine_Properties_ErrorDetailsFields,
  },
  name: "name",
  subscriptionStatus: "subscription_status",
};

const OpenapiMachine_Properties_LicenseProfile_ProductProfileFields: FieldMap = {
  billingEndDate: "billing_end_date",
  billingStartDate: "billing_start_date",
  disenrollmentDate: "disenrollment_date",
  enrollmentDate: "enrollment_date",
  error: {
    wireName: "error",
    kind: "object",
    fields: OpenapiMachine_Properties_ErrorDetailsFields,
  },
  productFeatures: {
    wireName: "product_features",
    kind: "list",
    fields: OpenapiMachine_Properties_LicenseProfile_ProductProfile_ProductFeaturesFields,
  },
  productType: "product_type",
  subscriptionStatus: "subscription_status",
};

const OpenapiMachine_Properties_LicenseProfile_SoftwareAssuranceFields: FieldMap = {
  softwareAssuranceCustomer: "software_assurance_customer",
};

const OpenapiMachine_Properties_LicenseProfileFields: FieldMap = {
  esuProfile: {
    wireName: "esu_profile",
    kind: "object",
    fields: OpenapiMachine_Properties_LicenseProfile_EsuProfileFields,
  },
  licenseChannel: "license_channel",
  licenseStatus: "license_status",
  productProfile: {
    wireName: "product_profile",
    kind: "object",
    fields: OpenapiMachine_Properties_LicenseProfile_ProductProfileFields,
  },
  softwareAssurance: {
    wireName: "software_assurance",
    kind: "object",
    fields: OpenapiMachine_Properties_LicenseProfile_SoftwareAssuranceFields,
  },
};

const OpenapiMachine_Properties_LocationDataFields: FieldMap = {
  city: "city",
  countryOrRegion: "country_or_region",
  district: "district",
  name: "name",
};

const OpenapiMachine_Properties_NetworkProfile_NetworkInterfaces_IpAddresses_SubnetFields: FieldMap = {
  addressPrefix: "address_prefix",
};

const OpenapiMachine_Properties_NetworkProfile_NetworkInterfaces_IpAddressesFields: FieldMap = {
  address: "address",
  ipAddressVersion: "ip_address_version",
  subnet: {
    wireName: "subnet",
    kind: "object",
    fields: OpenapiMachine_Properties_NetworkProfile_NetworkInterfaces_IpAddresses_SubnetFields,
  },
};

const OpenapiMachine_Properties_NetworkProfile_NetworkInterfacesFields: FieldMap = {
  id: "id",
  ipAddresses: {
    wireName: "ip_addresses",
    kind: "list",
    fields: OpenapiMachine_Properties_NetworkProfile_NetworkInterfaces_IpAddressesFields,
  },
  macAddress: "mac_address",
  name: "name",
};

const OpenapiMachine_Properties_NetworkProfileFields: FieldMap = {
  networkInterfaces: {
    wireName: "network_interfaces",
    kind: "list",
    fields: OpenapiMachine_Properties_NetworkProfile_NetworkInterfacesFields,
  },
};

const OpenapiMachine_Properties_OsProfile_LinuxConfiguration_PatchSettings_StatusFields: FieldMap = {
  error: {
    wireName: "error",
    kind: "object",
    fields: OpenapiMachine_Properties_ErrorDetailsFields,
  },
  hotpatchEnablementStatus: "hotpatch_enablement_status",
};

const OpenapiMachine_Properties_OsProfile_LinuxConfiguration_PatchSettingsFields: FieldMap = {
  assessmentMode: "assessment_mode",
  enableHotpatching: "enable_hotpatching",
  patchMode: "patch_mode",
  status: {
    wireName: "status",
    kind: "object",
    fields: OpenapiMachine_Properties_OsProfile_LinuxConfiguration_PatchSettings_StatusFields,
  },
};

const OpenapiMachine_Properties_OsProfile_LinuxConfigurationFields: FieldMap = {
  patchSettings: {
    wireName: "patch_settings",
    kind: "object",
    fields: OpenapiMachine_Properties_OsProfile_LinuxConfiguration_PatchSettingsFields,
  },
};

const OpenapiMachine_Properties_OsProfileFields: FieldMap = {
  computerName: "computer_name",
  linuxConfiguration: {
    wireName: "linux_configuration",
    kind: "object",
    fields: OpenapiMachine_Properties_OsProfile_LinuxConfigurationFields,
  },
  windowsConfiguration: {
    wireName: "windows_configuration",
    kind: "object",
    fields: OpenapiMachine_Properties_OsProfile_LinuxConfigurationFields,
  },
};

const OpenapiMachine_Properties_ServiceStatuses_ExtensionServiceFields: FieldMap = {
  startupType: "startup_type",
  status: "status",
};

const OpenapiMachine_Properties_ServiceStatusesFields: FieldMap = {
  extensionService: {
    wireName: "extension_service",
    kind: "object",
    fields: OpenapiMachine_Properties_ServiceStatuses_ExtensionServiceFields,
  },
  guestConfigurationService: {
    wireName: "guest_configuration_service",
    kind: "object",
    fields: OpenapiMachine_Properties_ServiceStatuses_ExtensionServiceFields,
  },
};

const OpenapiMachine_Properties_StorageProfile_DisksFields: FieldMap = {
  diskType: "disk_type",
  generatedId: "generated_id",
  id: "id",
  maxSizeInBytes: "max_size_in_bytes",
  name: "name",
  path: "path",
  usedSpaceInBytes: "used_space_in_bytes",
};

const OpenapiMachine_Properties_StorageProfileFields: FieldMap = {
  disks: {
    wireName: "disks",
    kind: "list",
    fields: OpenapiMachine_Properties_StorageProfile_DisksFields,
  },
};

const OpenapiMachine_PropertiesFields: FieldMap = {
  adFqdn: "ad_fqdn",
  agentConfiguration: {
    wireName: "agent_configuration",
    kind: "object",
    fields: OpenapiMachine_Properties_AgentConfigurationFields,
  },
  agentUpgrade: {
    wireName: "agent_upgrade",
    kind: "object",
    fields: OpenapiMachine_Properties_AgentUpgradeFields,
  },
  agentVersion: "agent_version",
  clientPublicKey: "client_public_key",
  cloudMetadata: {
    wireName: "cloud_metadata",
    kind: "object",
    fields: OpenapiMachine_Properties_CloudMetadataFields,
  },
  detectedProperties: "detected_properties",
  displayName: "display_name",
  dnsFqdn: "dns_fqdn",
  domainName: "domain_name",
  errorDetails: {
    wireName: "error_details",
    kind: "list",
    fields: OpenapiMachine_Properties_ErrorDetailsFields,
  },
  extensions: {
    wireName: "extensions",
    kind: "list",
    fields: OpenapiMachine_Properties_ExtensionsFields,
  },
  firmwareProfile: {
    wireName: "firmware_profile",
    kind: "object",
    fields: OpenapiMachine_Properties_FirmwareProfileFields,
  },
  hardwareProfile: {
    wireName: "hardware_profile",
    kind: "object",
    fields: OpenapiMachine_Properties_HardwareProfileFields,
  },
  hardwareResourceId: "hardware_resource_id",
  identityKeyStore: "identity_key_store",
  lastStatusChange: "last_status_change",
  licenseProfile: {
    wireName: "license_profile",
    kind: "object",
    fields: OpenapiMachine_Properties_LicenseProfileFields,
  },
  locationData: {
    wireName: "location_data",
    kind: "object",
    fields: OpenapiMachine_Properties_LocationDataFields,
  },
  machineFqdn: "machine_fqdn",
  mssqlDiscovered: "mssql_discovered",
  networkProfile: {
    wireName: "network_profile",
    kind: "object",
    fields: OpenapiMachine_Properties_NetworkProfileFields,
  },
  osEdition: "os_edition",
  osName: "os_name",
  osProfile: {
    wireName: "os_profile",
    kind: "object",
    fields: OpenapiMachine_Properties_OsProfileFields,
  },
  osSku: "os_sku",
  osType: "os_type",
  osVersion: "os_version",
  parentClusterResourceId: "parent_cluster_resource_id",
  privateLinkScopeResourceId: "private_link_scope_resource_id",
  provisioningState: "provisioning_state",
  serviceStatuses: {
    wireName: "service_statuses",
    kind: "object",
    fields: OpenapiMachine_Properties_ServiceStatusesFields,
  },
  status: "status",
  statusReason: "status_reason",
  storageProfile: {
    wireName: "storage_profile",
    kind: "object",
    fields: OpenapiMachine_Properties_StorageProfileFields,
  },
  tpmEkCertificate: "tpm_ek_certificate",
  vmId: "vm_id",
  vmUuid: "vm_uuid",
};

export interface OpenapiMachineConfig {
  /** Managed service identity (system assigned and/or user assigned identities) */
  identity?: OpenapiMachine_Identity | Computed<OpenapiMachine_Identity>;
  /** Indicates which kind of Arc machine placement on-premises, such as HCI, SCVMM or VMware etc. */
  kind?: string | Computed<string>;
  /** The geo-location where the resource lives */
  location: string | Computed<string>;
  /** Describes the properties of a hybrid machine. */
  properties?: OpenapiMachine_Properties | Computed<OpenapiMachine_Properties>;
  /** Resource tags. */
  tags?: Record<string, string> | Computed<Record<string, string>>;
}

export interface OpenapiMachineAttrs {
  /** Managed service identity (system assigned and/or user assigned identities) */
  identity: OpenapiMachine_Identity;
  /** Indicates which kind of Arc machine placement on-premises, such as HCI, SCVMM or VMware etc. */
  kind: string;
  /** The geo-location where the resource lives */
  location: string;
  /** Describes the properties of a hybrid machine. */
  properties: OpenapiMachine_Properties;
  /** The list of extensions affiliated to the machine */
  resources: OpenapiMachine_Resources[];
  /** Resource tags. */
  tags: Record<string, string>;
}

export const OpenapiMachine: ResourceBinding<OpenapiMachineConfig, OpenapiMachineAttrs> = {
  wireType: "azure_hybridcompute_openapi_machine",
  fields: {
    identity: {
      wireName: "identity",
      kind: "object",
      fields: OpenapiMachine_IdentityFields,
    },
    kind: "kind",
    location: "location",
    properties: {
      wireName: "properties",
      kind: "object",
      fields: OpenapiMachine_PropertiesFields,
    },
    tags: "tags",
  },
};
