// Code generated by `ubx sdk gen` from azure_loadtestservice_load_test_resource. DO NOT EDIT.
package loadtestservice

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type LoadTestResource_Value_Identity_UserAssignedIdentities struct {
	ClientId any
	PrincipalId any
}

type LoadTestResource_Value_Identity struct {
	PrincipalId any
	TenantId any
	Type any
	UserAssignedIdentities any
}

type LoadTestResource_Value_Properties_Encryption_Identity struct {
	ResourceId any
	Type any
}

type LoadTestResource_Value_Properties_Encryption struct {
	Identity any
	KeyUrl any
}

type LoadTestResource_Value_Properties struct {
	DataPlaneUri any
	Description any
	Encryption any
	ProvisioningState any
}

type LoadTestResource_Value struct {
	Identity any
	Properties any
}

type LoadTestResourceConfig struct {
}

type LoadTestResourceAttrs struct {
	// The link to the next page of items
	NextLink any
	// The LoadTestResource items on this page
	Value any
}

var LoadTestResource = ubx.DataSourceBinding{
	WireType: "azure_loadtestservice_load_test_resource",
	Fields: ubx.FieldMap{
	},
}
