// Code generated by `ubx sdk gen` from azure_paloaltonetworks_cloudngfw_certificate_object_local_rulestack_resource. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CloudngfwCertificateObjectLocalRulestackResource_Properties {
  /** comment for this object */
  auditComment?: string | Computed<string>;
  /** Boolean Enum */
  certificateSelfSigned: string | Computed<string>;
  /** Resource Id of certificate signer, to be populated only when certificateSelfSigned is false */
  certificateSignerResourceId?: string | Computed<string>;
  /** user description for this object */
  description?: string | Computed<string>;
  /** read only string representing last create or update */
  etag?: string | Computed<string>;
  /** Provisioning state of the firewall resource. */
  provisioningState?: string | Computed<string>;
}

const CloudngfwCertificateObjectLocalRulestackResource_PropertiesFields: FieldMap = {
  auditComment: "audit_comment",
  certificateSelfSigned: "certificate_self_signed",
  certificateSignerResourceId: "certificate_signer_resource_id",
  description: "description",
  etag: "etag",
  provisioningState: "provisioning_state",
};

export interface CloudngfwCertificateObjectLocalRulestackResourceConfig {
  /** certificate used for inbound and outbound decryption */
  properties: CloudngfwCertificateObjectLocalRulestackResource_Properties | Computed<CloudngfwCertificateObjectLocalRulestackResource_Properties>;
  /** path parameter, not part of the API's own resource representation */
  name: string | Computed<string>;
}

export interface CloudngfwCertificateObjectLocalRulestackResourceAttrs {
  /** certificate used for inbound and outbound decryption */
  properties: CloudngfwCertificateObjectLocalRulestackResource_Properties;
  /** path parameter, not part of the API's own resource representation */
  name: string;
}

export const CloudngfwCertificateObjectLocalRulestackResource: ResourceBinding<CloudngfwCertificateObjectLocalRulestackResourceConfig, CloudngfwCertificateObjectLocalRulestackResourceAttrs> = {
  wireType: "azure_paloaltonetworks_cloudngfw_certificate_object_local_rulestack_resource",
  fields: {
    properties: {
      wireName: "properties",
      kind: "object",
      fields: CloudngfwCertificateObjectLocalRulestackResource_PropertiesFields,
    },
    name: "name",
  },
};
