// Code generated by `ubx sdk gen` from azure_communication_openapi_suppression_list_resource. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface OpenapiSuppressionListResource_Properties {
  /** The date the resource was created. */
  createdTimeStamp?: string | Computed<string>;
  /** The location where the SuppressionListAddress data is stored at rest. This value is inherited from the parent Domains resource. */
  dataLocation?: string | Computed<string>;
  /** The date the resource was last updated. */
  lastUpdatedTimeStamp?: string | Computed<string>;
  /** The name of the suppression list. This value must match one of the valid sender usernames of the sending domain. */
  listName?: string | Computed<string>;
}

const OpenapiSuppressionListResource_PropertiesFields: FieldMap = {
  createdTimeStamp: "created_time_stamp",
  dataLocation: "data_location",
  lastUpdatedTimeStamp: "last_updated_time_stamp",
  listName: "list_name",
};

export interface OpenapiSuppressionListResourceConfig {
  /** A class that describes the properties of a SuppressionList resource. */
  properties?: OpenapiSuppressionListResource_Properties | Computed<OpenapiSuppressionListResource_Properties>;
}

export interface OpenapiSuppressionListResourceAttrs {
  /** A class that describes the properties of a SuppressionList resource. */
  properties: OpenapiSuppressionListResource_Properties;
}

export const OpenapiSuppressionListResource: ResourceBinding<OpenapiSuppressionListResourceConfig, OpenapiSuppressionListResourceAttrs> = {
  wireType: "azure_communication_openapi_suppression_list_resource",
  fields: {
    properties: {
      wireName: "properties",
      kind: "object",
      fields: OpenapiSuppressionListResource_PropertiesFields,
    },
  },
};
