// Code generated by `ubx sdk gen` from azure_logic_integration_service_environment_sku_definition. DO NOT EDIT.
package logic

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type IntegrationServiceEnvironmentSkuDefinition_Value_Capacity struct {
	Default   any
	Maximum   any
	Minimum   any
	ScaleType any
}

type IntegrationServiceEnvironmentSkuDefinition_Value_Sku struct {
	Name any
	Tier any
}

type IntegrationServiceEnvironmentSkuDefinition_Value struct {
	Capacity     any
	ResourceType any
	Sku          any
}

type IntegrationServiceEnvironmentSkuDefinitionConfig struct {
	ApiVersion                        any
	IntegrationServiceEnvironmentName any
	ResourceGroup                     any
	SubscriptionId                    any
}

type IntegrationServiceEnvironmentSkuDefinitionAttrs struct {
	ApiVersion                        any
	IntegrationServiceEnvironmentName any
	// The URL to get the next set of results.
	NextLink       any
	ResourceGroup  any
	SubscriptionId any
	// The list of integration service environment skus.
	Value any
}

var IntegrationServiceEnvironmentSkuDefinition = ubx.DataSourceBinding{
	WireType: "azure_logic_integration_service_environment_sku_definition",
	Fields: ubx.FieldMap{
		"ApiVersion":                        ubx.FieldSpec{WireName: "api_version"},
		"IntegrationServiceEnvironmentName": ubx.FieldSpec{WireName: "integration_service_environment_name"},
		"ResourceGroup":                     ubx.FieldSpec{WireName: "resource_group"},
		"SubscriptionId":                    ubx.FieldSpec{WireName: "subscription_id"},
	},
}
