// Code generated by `ubx sdk gen` from azure_apimanagement_apimgroups_user_contract_list. DO NOT EDIT.
package apimanagement

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ApimgroupsUserContractList_Value_Properties_Groups struct {
	BuiltIn     any
	Description any
	DisplayName any
	ExternalId  any
	Type        any
}

type ApimgroupsUserContractList_Value_Properties struct {
	Email            any
	FirstName        any
	Groups           any
	LastName         any
	RegistrationDate any
}

type ApimgroupsUserContractList_Value struct {
	Properties any
}

type ApimgroupsUserContractListConfig struct {
}

type ApimgroupsUserContractListAttrs struct {
	// Total record count number across all pages.
	Count any
	// Next page link if any.
	NextLink any
	// Page values.
	Value any
}

var ApimgroupsUserContractList = ubx.DataSourceBinding{
	WireType: "azure_apimanagement_apimgroups_user_contract_list",
	Fields:   ubx.FieldMap{},
}
