// Code generated by `ubx sdk gen` from azure_postgresql_openapi_tuning_options_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface OpenapiTuningOptionsList_Value_Properties {
  state?: string | Computed<string>;
}

export interface OpenapiTuningOptionsList_Value {
  properties?: OpenapiTuningOptionsList_Value_Properties | Computed<OpenapiTuningOptionsList_Value_Properties>;
}

export interface OpenapiTuningOptionsListConfig {
  serverName: string | Computed<string>;
}

export interface OpenapiTuningOptionsListAttrs {
  /** The link to the next page of items */
  nextLink: string;
  serverName: string;
  /** The TuningOptions items on this page */
  value: OpenapiTuningOptionsList_Value[];
}

export const OpenapiTuningOptionsList: DataSourceBinding<OpenapiTuningOptionsListConfig, OpenapiTuningOptionsListAttrs> = {
  wireType: "azure_postgresql_openapi_tuning_options_list",
  fields: {
    serverName: "server_name",
  },
};
