// Code generated by `ubx sdk gen` from azurerm_mssql_virtual_machine. DO NOT EDIT.
package mssql

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type VirtualMachine_Assessment_Schedule struct {
	DayOfWeek any
	MonthlyOccurrence any
	StartTime any
	WeeklyInterval any
}

type VirtualMachine_Assessment struct {
	Enabled any
	RunImmediately any
	Schedule any
}

type VirtualMachine_AutoBackup_ManualSchedule struct {
	DaysOfWeek any
	FullBackupFrequency any
	FullBackupStartHour any
	FullBackupWindowInHours any
	LogBackupFrequencyInMinutes any
}

type VirtualMachine_AutoBackup struct {
	EncryptionPassword any
	RetentionPeriodInDays any
	StorageAccountAccessKey any
	StorageBlobEndpoint any
	SystemDatabasesBackupEnabled any
	ManualSchedule any
}

type VirtualMachine_AutoPatching struct {
	DayOfWeek any
	MaintenanceWindowDurationInMinutes any
	MaintenanceWindowStartingHour any
}

type VirtualMachine_KeyVaultCredential struct {
	KeyVaultUrl any
	Name any
	ServicePrincipalName any
	ServicePrincipalSecret any
}

type VirtualMachine_SqlInstance struct {
	AdhocWorkloadsOptimizationEnabled any
	Collation any
	InstantFileInitializationEnabled any
	LockPagesInMemoryEnabled any
	MaxDop any
	MaxServerMemoryMb any
	MinServerMemoryMb any
}

type VirtualMachine_StorageConfiguration_DataSettings struct {
	DefaultFilePath any
	Luns any
}

type VirtualMachine_StorageConfiguration_TempDbSettings struct {
	DataFileCount any
	DataFileGrowthInMb any
	DataFileSizeMb any
	DefaultFilePath any
	LogFileGrowthMb any
	LogFileSizeMb any
	Luns any
}

type VirtualMachine_StorageConfiguration struct {
	DiskType any
	StorageWorkloadType any
	SystemDbOnDataDiskEnabled any
	DataSettings any
	LogSettings any
	TempDbSettings any
}

type VirtualMachine_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

type VirtualMachine_WsfcDomainCredential struct {
	ClusterBootstrapAccountPassword any
	ClusterOperatorAccountPassword any
	SqlServiceAccountPassword any
}

var VirtualMachine_Assessment_ScheduleFields = ubx.FieldMap{
		"DayOfWeek": ubx.FieldSpec{WireName: "day_of_week"},
		"MonthlyOccurrence": ubx.FieldSpec{WireName: "monthly_occurrence"},
		"StartTime": ubx.FieldSpec{WireName: "start_time"},
		"WeeklyInterval": ubx.FieldSpec{WireName: "weekly_interval"},
	}

var VirtualMachine_AssessmentFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"RunImmediately": ubx.FieldSpec{WireName: "run_immediately"},
		"Schedule": ubx.FieldSpec{
			WireName: "schedule",
			Kind: "list",
			Fields: VirtualMachine_Assessment_ScheduleFields,
		},
	}

var VirtualMachine_AutoBackup_ManualScheduleFields = ubx.FieldMap{
		"DaysOfWeek": ubx.FieldSpec{WireName: "days_of_week"},
		"FullBackupFrequency": ubx.FieldSpec{WireName: "full_backup_frequency"},
		"FullBackupStartHour": ubx.FieldSpec{WireName: "full_backup_start_hour"},
		"FullBackupWindowInHours": ubx.FieldSpec{WireName: "full_backup_window_in_hours"},
		"LogBackupFrequencyInMinutes": ubx.FieldSpec{WireName: "log_backup_frequency_in_minutes"},
	}

var VirtualMachine_AutoBackupFields = ubx.FieldMap{
		"EncryptionPassword": ubx.FieldSpec{WireName: "encryption_password"},
		"RetentionPeriodInDays": ubx.FieldSpec{WireName: "retention_period_in_days"},
		"StorageAccountAccessKey": ubx.FieldSpec{WireName: "storage_account_access_key"},
		"StorageBlobEndpoint": ubx.FieldSpec{WireName: "storage_blob_endpoint"},
		"SystemDatabasesBackupEnabled": ubx.FieldSpec{WireName: "system_databases_backup_enabled"},
		"ManualSchedule": ubx.FieldSpec{
			WireName: "manual_schedule",
			Kind: "list",
			Fields: VirtualMachine_AutoBackup_ManualScheduleFields,
		},
	}

var VirtualMachine_AutoPatchingFields = ubx.FieldMap{
		"DayOfWeek": ubx.FieldSpec{WireName: "day_of_week"},
		"MaintenanceWindowDurationInMinutes": ubx.FieldSpec{WireName: "maintenance_window_duration_in_minutes"},
		"MaintenanceWindowStartingHour": ubx.FieldSpec{WireName: "maintenance_window_starting_hour"},
	}

var VirtualMachine_KeyVaultCredentialFields = ubx.FieldMap{
		"KeyVaultUrl": ubx.FieldSpec{WireName: "key_vault_url"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"ServicePrincipalName": ubx.FieldSpec{WireName: "service_principal_name"},
		"ServicePrincipalSecret": ubx.FieldSpec{WireName: "service_principal_secret"},
	}

var VirtualMachine_SqlInstanceFields = ubx.FieldMap{
		"AdhocWorkloadsOptimizationEnabled": ubx.FieldSpec{WireName: "adhoc_workloads_optimization_enabled"},
		"Collation": ubx.FieldSpec{WireName: "collation"},
		"InstantFileInitializationEnabled": ubx.FieldSpec{WireName: "instant_file_initialization_enabled"},
		"LockPagesInMemoryEnabled": ubx.FieldSpec{WireName: "lock_pages_in_memory_enabled"},
		"MaxDop": ubx.FieldSpec{WireName: "max_dop"},
		"MaxServerMemoryMb": ubx.FieldSpec{WireName: "max_server_memory_mb"},
		"MinServerMemoryMb": ubx.FieldSpec{WireName: "min_server_memory_mb"},
	}

var VirtualMachine_StorageConfiguration_DataSettingsFields = ubx.FieldMap{
		"DefaultFilePath": ubx.FieldSpec{WireName: "default_file_path"},
		"Luns": ubx.FieldSpec{WireName: "luns"},
	}

var VirtualMachine_StorageConfiguration_TempDbSettingsFields = ubx.FieldMap{
		"DataFileCount": ubx.FieldSpec{WireName: "data_file_count"},
		"DataFileGrowthInMb": ubx.FieldSpec{WireName: "data_file_growth_in_mb"},
		"DataFileSizeMb": ubx.FieldSpec{WireName: "data_file_size_mb"},
		"DefaultFilePath": ubx.FieldSpec{WireName: "default_file_path"},
		"LogFileGrowthMb": ubx.FieldSpec{WireName: "log_file_growth_mb"},
		"LogFileSizeMb": ubx.FieldSpec{WireName: "log_file_size_mb"},
		"Luns": ubx.FieldSpec{WireName: "luns"},
	}

var VirtualMachine_StorageConfigurationFields = ubx.FieldMap{
		"DiskType": ubx.FieldSpec{WireName: "disk_type"},
		"StorageWorkloadType": ubx.FieldSpec{WireName: "storage_workload_type"},
		"SystemDbOnDataDiskEnabled": ubx.FieldSpec{WireName: "system_db_on_data_disk_enabled"},
		"DataSettings": ubx.FieldSpec{
			WireName: "data_settings",
			Kind: "list",
			Fields: VirtualMachine_StorageConfiguration_DataSettingsFields,
		},
		"LogSettings": ubx.FieldSpec{
			WireName: "log_settings",
			Kind: "list",
			Fields: VirtualMachine_StorageConfiguration_DataSettingsFields,
		},
		"TempDbSettings": ubx.FieldSpec{
			WireName: "temp_db_settings",
			Kind: "list",
			Fields: VirtualMachine_StorageConfiguration_TempDbSettingsFields,
		},
	}

var VirtualMachine_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
		"Delete": ubx.FieldSpec{WireName: "delete"},
		"Read": ubx.FieldSpec{WireName: "read"},
		"Update": ubx.FieldSpec{WireName: "update"},
	}

var VirtualMachine_WsfcDomainCredentialFields = ubx.FieldMap{
		"ClusterBootstrapAccountPassword": ubx.FieldSpec{WireName: "cluster_bootstrap_account_password"},
		"ClusterOperatorAccountPassword": ubx.FieldSpec{WireName: "cluster_operator_account_password"},
		"SqlServiceAccountPassword": ubx.FieldSpec{WireName: "sql_service_account_password"},
	}

type VirtualMachineConfig struct {
	Id any
	RServicesEnabled any
	SqlConnectivityPort any
	SqlConnectivityType any
	SqlConnectivityUpdatePassword any
	SqlConnectivityUpdateUsername any
	SqlLicenseType any
	SqlVirtualMachineGroupId any
	Tags any
	VirtualMachineId any
	Assessment any
	AutoBackup any
	AutoPatching any
	KeyVaultCredential any
	SqlInstance any
	StorageConfiguration any
	Timeouts any
	WsfcDomainCredential any
}

var VirtualMachine = ubx.ResourceBinding{
	WireType: "azurerm_mssql_virtual_machine",
	Fields: ubx.FieldMap{
		"Id": ubx.FieldSpec{WireName: "id"},
		"RServicesEnabled": ubx.FieldSpec{WireName: "r_services_enabled"},
		"SqlConnectivityPort": ubx.FieldSpec{WireName: "sql_connectivity_port"},
		"SqlConnectivityType": ubx.FieldSpec{WireName: "sql_connectivity_type"},
		"SqlConnectivityUpdatePassword": ubx.FieldSpec{WireName: "sql_connectivity_update_password"},
		"SqlConnectivityUpdateUsername": ubx.FieldSpec{WireName: "sql_connectivity_update_username"},
		"SqlLicenseType": ubx.FieldSpec{WireName: "sql_license_type"},
		"SqlVirtualMachineGroupId": ubx.FieldSpec{WireName: "sql_virtual_machine_group_id"},
		"Tags": ubx.FieldSpec{WireName: "tags"},
		"VirtualMachineId": ubx.FieldSpec{WireName: "virtual_machine_id"},
		"Assessment": ubx.FieldSpec{
			WireName: "assessment",
			Kind: "list",
			Fields: VirtualMachine_AssessmentFields,
		},
		"AutoBackup": ubx.FieldSpec{
			WireName: "auto_backup",
			Kind: "list",
			Fields: VirtualMachine_AutoBackupFields,
		},
		"AutoPatching": ubx.FieldSpec{
			WireName: "auto_patching",
			Kind: "list",
			Fields: VirtualMachine_AutoPatchingFields,
		},
		"KeyVaultCredential": ubx.FieldSpec{
			WireName: "key_vault_credential",
			Kind: "list",
			Fields: VirtualMachine_KeyVaultCredentialFields,
		},
		"SqlInstance": ubx.FieldSpec{
			WireName: "sql_instance",
			Kind: "list",
			Fields: VirtualMachine_SqlInstanceFields,
		},
		"StorageConfiguration": ubx.FieldSpec{
			WireName: "storage_configuration",
			Kind: "list",
			Fields: VirtualMachine_StorageConfigurationFields,
		},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: VirtualMachine_TimeoutsFields,
		},
		"WsfcDomainCredential": ubx.FieldSpec{
			WireName: "wsfc_domain_credential",
			Kind: "list",
			Fields: VirtualMachine_WsfcDomainCredentialFields,
		},
	},
}
