# Code generated by `ubx sdk gen` from azure_network_virtualwan_vpn_gateway. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_BgpSettings_BgpPeeringAddresses:
    custom_bgp_ip_addresses: Any = None
    default_bgp_ip_addresses: Any = None
    ipconfiguration_id: Any = None
    tunnel_ip_addresses: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_BgpSettings:
    asn: Any = None
    bgp_peering_address: Any = None
    bgp_peering_addresses: Any = None
    peer_weight: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_Connections_Properties_IpsecPolicies:
    dh_group: Any = None
    ike_encryption: Any = None
    ike_integrity: Any = None
    ipsec_encryption: Any = None
    ipsec_integrity: Any = None
    pfs_group: Any = None
    sa_data_size_kilobytes: Any = None
    sa_life_time_seconds: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_Connections_Properties_RemoteVpnSite:
    id: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_Connections_Properties_RoutingConfiguration_PropagatedRouteTables:
    ids: Any = None
    labels: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_Connections_Properties_RoutingConfiguration_VnetRoutes_StaticRoutes:
    address_prefixes: Any = None
    name: Any = None
    next_hop_ip_address: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_Connections_Properties_RoutingConfiguration_VnetRoutes_StaticRoutesConfig:
    propagate_static_routes: Any = None
    vnet_local_route_override_criteria: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_Connections_Properties_RoutingConfiguration_VnetRoutes:
    bgp_connections: Any = None
    static_routes: Any = None
    static_routes_config: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_Connections_Properties_RoutingConfiguration:
    associated_route_table: Any = None
    inbound_route_map: Any = None
    outbound_route_map: Any = None
    propagated_route_tables: Any = None
    vnet_routes: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_Connections_Properties_TrafficSelectorPolicies:
    local_address_ranges: Any = None
    remote_address_ranges: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_Connections_Properties_VpnLinkConnections_Properties_VpnGatewayCustomBgpAddresses:
    custom_bgp_ip_address: Any = None
    ip_configuration_id: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_Connections_Properties_VpnLinkConnections_Properties:
    connection_bandwidth: Any = None
    connection_status: Any = None
    dpd_timeout_seconds: Any = None
    egress_bytes_transferred: Any = None
    egress_nat_rules: Any = None
    enable_bgp: Any = None
    enable_rate_limiting: Any = None
    ingress_bytes_transferred: Any = None
    ingress_nat_rules: Any = None
    ipsec_policies: Any = None
    provisioning_state: Any = None
    routing_weight: Any = None
    shared_key: Any = None
    use_local_azure_ip_address: Any = None
    use_policy_based_traffic_selectors: Any = None
    vpn_connection_protocol_type: Any = None
    vpn_gateway_custom_bgp_addresses: Any = None
    vpn_link_connection_mode: Any = None
    vpn_site_link: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_Connections_Properties_VpnLinkConnections:
    etag: Any = None
    properties: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_Connections_Properties:
    connection_bandwidth: Any = None
    connection_status: Any = None
    dpd_timeout_seconds: Any = None
    egress_bytes_transferred: Any = None
    enable_bgp: Any = None
    enable_internet_security: Any = None
    enable_rate_limiting: Any = None
    ingress_bytes_transferred: Any = None
    ipsec_policies: Any = None
    provisioning_state: Any = None
    remote_vpn_site: Any = None
    routing_configuration: Any = None
    routing_weight: Any = None
    shared_key: Any = None
    traffic_selector_policies: Any = None
    use_local_azure_ip_address: Any = None
    use_policy_based_traffic_selectors: Any = None
    vpn_connection_protocol_type: Any = None
    vpn_link_connections: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_Connections:
    etag: Any = None
    name: Any = None
    properties: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_IpConfigurations:
    id: Any = None
    private_ip_address: Any = None
    public_ip_address: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_NatRules_Properties_ExternalMappings:
    address_space: Any = None
    port_range: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_NatRules_Properties:
    egress_vpn_site_link_connections: Any = None
    external_mappings: Any = None
    ingress_vpn_site_link_connections: Any = None
    internal_mappings: Any = None
    ip_configuration_id: Any = None
    mode: Any = None
    provisioning_state: Any = None
    type: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties_NatRules:
    etag: Any = None
    properties: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value_Properties:
    bgp_settings: Any = None
    connections: Any = None
    enable_bgp_route_translation_for_nat: Any = None
    ip_configurations: Any = None
    is_routing_preference_internet: Any = None
    nat_rules: Any = None
    provisioning_state: Any = None
    virtual_hub: Any = None
    vpn_gateway_scale_unit: Any = None

@dataclasses.dataclass
class VirtualwanVpnGateway_Value:
    etag: Any = None
    properties: Any = None

@dataclasses.dataclass
class VirtualwanVpnGatewayConfig:
    pass

@dataclasses.dataclass
class VirtualwanVpnGatewayAttrs:
    # The link to the next page of items
    next_link: Any = None
    # The VpnGateway items on this page
    value: Any = None

VirtualwanVpnGateway = ubx.DataSourceBinding(
    wire_type="azure_network_virtualwan_vpn_gateway",
    fields={
    },
)
