# Code generated by `ubx sdk gen` from azure@dynamic. DO NOT EDIT.
# This file is committed to git like any other reviewable generated code
# (docs/sdk.md — "ubx sdk gen: local, pinned, offline-after-generation") --
# re-run `ubx sdk gen` to regenerate after a provider version bump.
SOURCE_PROVENANCE = {"source": "azure", "version": "dynamic"}

from .digitaltwins_digital_twins_description import DigitaltwinsDigitalTwinsDescription, DigitaltwinsDigitalTwinsDescriptionConfig
from .digitaltwins_digital_twins_endpoint_resource import DigitaltwinsDigitalTwinsEndpointResource, DigitaltwinsDigitalTwinsEndpointResourceConfig
from .digitaltwins_private_endpoint_connection import DigitaltwinsPrivateEndpointConnection, DigitaltwinsPrivateEndpointConnectionConfig
from .digitaltwins_time_series_database_connection import DigitaltwinsTimeSeriesDatabaseConnection, DigitaltwinsTimeSeriesDatabaseConnectionConfig
