// Code generated by `ubx sdk gen` from azure_subscription_subscriptions_subscription_alias_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SubscriptionsSubscriptionAliasResponse_Properties_AdditionalProperties {
  /** Management group Id for the subscription. */
  managementGroupId?: string | Computed<string>;
  /** Owner Id of the subscription */
  subscriptionOwnerId?: string | Computed<string>;
  /** Tenant Id of the subscription */
  subscriptionTenantId?: string | Computed<string>;
  /** Tags for the subscription */
  tags?: Record<string, string> | Computed<Record<string, string>>;
}

export interface SubscriptionsSubscriptionAliasResponse_Properties {
  /** The accept ownership state of the resource. */
  acceptOwnershipState?: string | Computed<string>;
  /** Url to accept ownership of the subscription. */
  acceptOwnershipUrl?: string | Computed<string>;
  /** Put subscription additional properties. */
  additionalProperties?: SubscriptionsSubscriptionAliasResponse_Properties_AdditionalProperties | Computed<SubscriptionsSubscriptionAliasResponse_Properties_AdditionalProperties>;
  /** Billing scope of the subscription. For CustomerLed and FieldLed - /billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/invoiceSections/{invoiceSectionName} For PartnerLed - /billingAccounts/{billingAccountName}/customers/{customerName} For Legacy EA - /billingAccounts/{billingAccountName}/enrollmentAccounts/{enrollmentAccountName} */
  billingScope?: string | Computed<string>;
  /** Created Time */
  createdTime?: string | Computed<string>;
  /** The friendly name of the subscription. */
  displayName?: string | Computed<string>;
  /** The Management Group Id. */
  managementGroupId?: string | Computed<string>;
  /** The provisioning state of the resource. */
  provisioningState?: string | Computed<string>;
  /** Reseller Id */
  resellerId?: string | Computed<string>;
  /** This parameter can be used to create alias for existing subscription Id */
  subscriptionId?: string | Computed<string>;
  /** Owner Id of the subscription */
  subscriptionOwnerId?: string | Computed<string>;
  /** Tags for the subscription */
  tags?: Record<string, string> | Computed<Record<string, string>>;
  /** The workload type of the subscription. It can be either Production or DevTest. */
  workload?: string | Computed<string>;
}

export interface SubscriptionsSubscriptionAliasResponse_SystemData {
  /** The timestamp of resource creation (UTC). */
  createdAt?: string | Computed<string>;
  /** The identity that created the resource. */
  createdBy?: string | Computed<string>;
  /** The type of identity that created the resource. */
  createdByType?: string | Computed<string>;
  /** The timestamp of resource last modification (UTC) */
  lastModifiedAt?: string | Computed<string>;
  /** The identity that last modified the resource. */
  lastModifiedBy?: string | Computed<string>;
  /** The type of identity that last modified the resource. */
  lastModifiedByType?: string | Computed<string>;
}

const SubscriptionsSubscriptionAliasResponse_Properties_AdditionalPropertiesFields: FieldMap = {
  managementGroupId: "management_group_id",
  subscriptionOwnerId: "subscription_owner_id",
  subscriptionTenantId: "subscription_tenant_id",
  tags: "tags",
};

const SubscriptionsSubscriptionAliasResponse_PropertiesFields: FieldMap = {
  acceptOwnershipState: "accept_ownership_state",
  acceptOwnershipUrl: "accept_ownership_url",
  additionalProperties: {
    wireName: "additional_properties",
    kind: "object",
    fields: SubscriptionsSubscriptionAliasResponse_Properties_AdditionalPropertiesFields,
  },
  billingScope: "billing_scope",
  createdTime: "created_time",
  displayName: "display_name",
  managementGroupId: "management_group_id",
  provisioningState: "provisioning_state",
  resellerId: "reseller_id",
  subscriptionId: "subscription_id",
  subscriptionOwnerId: "subscription_owner_id",
  tags: "tags",
  workload: "workload",
};

export interface SubscriptionsSubscriptionAliasResponseConfig {
  /** Put subscription properties. */
  properties?: SubscriptionsSubscriptionAliasResponse_Properties | Computed<SubscriptionsSubscriptionAliasResponse_Properties>;
}

export interface SubscriptionsSubscriptionAliasResponseAttrs {
  /** Fully qualified ID for the alias resource. */
  id: string;
  /** Alias ID. */
  name: string;
  /** Put subscription properties. */
  properties: SubscriptionsSubscriptionAliasResponse_Properties;
  /** Metadata pertaining to creation and last modification of the resource. */
  systemData: SubscriptionsSubscriptionAliasResponse_SystemData;
  /** Resource type, Microsoft.Subscription/aliases. */
  type: string;
}

export const SubscriptionsSubscriptionAliasResponse: ResourceBinding<SubscriptionsSubscriptionAliasResponseConfig, SubscriptionsSubscriptionAliasResponseAttrs> = {
  wireType: "azure_subscription_subscriptions_subscription_alias_response",
  fields: {
    properties: {
      wireName: "properties",
      kind: "object",
      fields: SubscriptionsSubscriptionAliasResponse_PropertiesFields,
    },
  },
};
