// Code generated by `ubx sdk gen` from azure_vmware_workload_network_virtual_machine_list. DO NOT EDIT.
package vmware

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type WorkloadNetworkVirtualMachineList_Value_Properties struct {
	DisplayName       any
	ProvisioningState any
	VmType            any
}

type WorkloadNetworkVirtualMachineList_Value struct {
	Properties any
}

type WorkloadNetworkVirtualMachineListConfig struct {
	PrivateCloudName any
}

type WorkloadNetworkVirtualMachineListAttrs struct {
	// The link to the next page of items
	NextLink         any
	PrivateCloudName any
	// The WorkloadNetworkVirtualMachine items on this page
	Value any
}

var WorkloadNetworkVirtualMachineList = ubx.DataSourceBinding{
	WireType: "azure_vmware_workload_network_virtual_machine_list",
	Fields: ubx.FieldMap{
		"PrivateCloudName": ubx.FieldSpec{WireName: "private_cloud_name"},
	},
}
