// Code generated by `ubx sdk gen` from azure_servicebus_rule_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface RuleList_Value_Properties_Action {
  compatibilityLevel?: number | Computed<number>;
  requiresPreprocessing?: boolean | Computed<boolean>;
  sqlExpression?: string | Computed<string>;
}

export interface RuleList_Value_Properties_CorrelationFilter {
  contentType?: string | Computed<string>;
  correlationId?: string | Computed<string>;
  label?: string | Computed<string>;
  messageId?: string | Computed<string>;
  properties?: Record<string, string> | Computed<Record<string, string>>;
  replyTo?: string | Computed<string>;
  replyToSessionId?: string | Computed<string>;
  requiresPreprocessing?: boolean | Computed<boolean>;
  sessionId?: string | Computed<string>;
  to?: string | Computed<string>;
}

export interface RuleList_Value_Properties {
  action?: RuleList_Value_Properties_Action | Computed<RuleList_Value_Properties_Action>;
  correlationFilter?: RuleList_Value_Properties_CorrelationFilter | Computed<RuleList_Value_Properties_CorrelationFilter>;
  filterType?: string | Computed<string>;
  sqlFilter?: RuleList_Value_Properties_Action | Computed<RuleList_Value_Properties_Action>;
}

export interface RuleList_Value {
  location?: string | Computed<string>;
  properties?: RuleList_Value_Properties | Computed<RuleList_Value_Properties>;
}

export interface RuleListConfig {
  namespaceName: string | Computed<string>;
  subscriptionName: string | Computed<string>;
  topicName: string | Computed<string>;
}

export interface RuleListAttrs {
  namespaceName: string;
  /** The link to the next page of items */
  nextLink: string;
  subscriptionName: string;
  topicName: string;
  /** The Rule items on this page */
  value: RuleList_Value[];
}

export const RuleList: DataSourceBinding<RuleListConfig, RuleListAttrs> = {
  wireType: "azure_servicebus_rule_list",
  fields: {
    namespaceName: "namespace_name",
    subscriptionName: "subscription_name",
    topicName: "topic_name",
  },
};
