// Code generated by `ubx sdk gen` from azure_web_openapi_static_site_basic_auth_properties_armresource. DO NOT EDIT.
package web

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpenapiStaticSiteBasicAuthPropertiesArmresource_Properties struct {
	// State indicating if basic auth is enabled and for what environments it is active.
	ApplicableEnvironmentsMode any
	// The list of enabled environments for Basic Auth if ApplicableEnvironmentsMode is set to SpecifiedEnvironments.
	Environments any
	// The password for basic auth.
	Password any
	// State indicating if basic auth has a secret and what type it is.
	SecretState any
	// Url to the secret in Key Vault.
	SecretUrl any
}

var OpenapiStaticSiteBasicAuthPropertiesArmresource_PropertiesFields = ubx.FieldMap{
		"ApplicableEnvironmentsMode": ubx.FieldSpec{WireName: "applicable_environments_mode"},
		"Environments": ubx.FieldSpec{WireName: "environments"},
		"Password": ubx.FieldSpec{WireName: "password"},
		"SecretState": ubx.FieldSpec{WireName: "secret_state"},
		"SecretUrl": ubx.FieldSpec{WireName: "secret_url"},
	}

type OpenapiStaticSiteBasicAuthPropertiesArmresourceConfig struct {
	// Kind of resource.
	Kind any
	// StaticSiteBasicAuthPropertiesARMResource resource specific properties
	Properties any
	// path parameter, not part of the API's own resource representation
	Name any
}

type OpenapiStaticSiteBasicAuthPropertiesArmresourceAttrs struct {
	// Kind of resource.
	Kind any
	// StaticSiteBasicAuthPropertiesARMResource resource specific properties
	Properties any
	// path parameter, not part of the API's own resource representation
	Name any
}

var OpenapiStaticSiteBasicAuthPropertiesArmresource = ubx.ResourceBinding{
	WireType: "azure_web_openapi_static_site_basic_auth_properties_armresource",
	Fields: ubx.FieldMap{
		"Kind": ubx.FieldSpec{WireName: "kind"},
		"Properties": ubx.FieldSpec{
			WireName: "properties",
			Kind: "object",
			Fields: OpenapiStaticSiteBasicAuthPropertiesArmresource_PropertiesFields,
		},
		"Name": ubx.FieldSpec{WireName: "name"},
	},
}
