# Code generated by `ubx sdk gen` from azure_logic_workflow_run_action. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class WorkflowRunAction_Properties_Correlation:
    # The action tracking identifier.
    action_tracking_id: Any = None

@dataclasses.dataclass
class WorkflowRunAction_Properties_InputsLink_ContentHash:
    # The algorithm of the content hash.
    algorithm: Any = None
    # The value of the content hash.
    value: Any = None

@dataclasses.dataclass
class WorkflowRunAction_Properties_InputsLink:
    # The content hash.
    content_hash: Any = None
    # The content size.
    content_size: Any = None
    # The content version.
    content_version: Any = None
    metadata: Any = None
    # The content link URI.
    uri: Any = None

@dataclasses.dataclass
class WorkflowRunAction_Properties_RetryHistory_Error_Error:
    code: Any = None
    message: Any = None

@dataclasses.dataclass
class WorkflowRunAction_Properties_RetryHistory_Error:
    error: Any = None

@dataclasses.dataclass
class WorkflowRunAction_Properties_RetryHistory:
    client_request_id: Any = None
    code: Any = None
    end_time: Any = None
    error: Any = None
    service_request_id: Any = None
    start_time: Any = None

@dataclasses.dataclass
class WorkflowRunAction_Properties:
    # Gets the code.
    code: Any = None
    # The workflow run action correlation properties.
    correlation: Any = None
    # Gets the end time.
    end_time: Any = None
    error: Any = None
    # The content link.
    inputs_link: Any = None
    # The content link.
    outputs_link: Any = None
    # Gets the retry histories.
    retry_history: Any = None
    # Gets the start time.
    start_time: Any = None
    # The workflow status.
    status: Any = None
    tracked_properties: Any = None
    # Gets the tracking id.
    tracking_id: Any = None

@dataclasses.dataclass
class WorkflowRunActionConfig:
    action_name: Any = None
    api_version: Any = None
    resource_group_name: Any = None
    run_name: Any = None
    subscription_id: Any = None
    workflow_name: Any = None

@dataclasses.dataclass
class WorkflowRunActionAttrs:
    action_name: Any = None
    api_version: Any = None
    # Gets the workflow run action name.
    name: Any = None
    # The workflow run action properties.
    properties: Any = None
    resource_group_name: Any = None
    run_name: Any = None
    subscription_id: Any = None
    # Gets the workflow run action type.
    type: Any = None
    workflow_name: Any = None

WorkflowRunAction = ubx.DataSourceBinding(
    wire_type="azure_logic_workflow_run_action",
    fields={
        "action_name": ubx.FieldSpec(wire_name="action_name"),
        "api_version": ubx.FieldSpec(wire_name="api_version"),
        "resource_group_name": ubx.FieldSpec(wire_name="resource_group_name"),
        "run_name": ubx.FieldSpec(wire_name="run_name"),
        "subscription_id": ubx.FieldSpec(wire_name="subscription_id"),
        "workflow_name": ubx.FieldSpec(wire_name="workflow_name"),
    },
)
