# Code generated by `ubx sdk gen` from azure_machinelearningservices_openapi_external_fqdnresponse. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OpenapiExternalFqdnresponse_Value_Properties_Endpoints_EndpointDetails:
    port: Any = None

@dataclasses.dataclass
class OpenapiExternalFqdnresponse_Value_Properties_Endpoints:
    domain_name: Any = None
    endpoint_details: Any = None

@dataclasses.dataclass
class OpenapiExternalFqdnresponse_Value_Properties:
    category: Any = None
    endpoints: Any = None

@dataclasses.dataclass
class OpenapiExternalFqdnresponse_Value:
    properties: Any = None

@dataclasses.dataclass
class OpenapiExternalFqdnresponseConfig:
    workspace_name: Any = None

@dataclasses.dataclass
class OpenapiExternalFqdnresponseAttrs:
    value: Any = None
    workspace_name: Any = None

OpenapiExternalFqdnresponse = ubx.DataSourceBinding(
    wire_type="azure_machinelearningservices_openapi_external_fqdnresponse",
    fields={
        "workspace_name": ubx.FieldSpec(wire_name="workspace_name"),
    },
)
