// Code generated by `ubx sdk gen` from azure_automation_openapi_dsc_node_report. DO NOT EDIT.
package automation

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpenapiDscNodeReport_Errors struct {
	ErrorCode any
	ErrorDetails any
	ErrorMessage any
	ErrorSource any
	Locale any
	ResourceId any
}

type OpenapiDscNodeReport_MetaConfiguration struct {
	// Gets or sets the ActionAfterReboot value of the meta configuration.
	ActionAfterReboot any
	// Gets or sets the AllowModuleOverwrite value of the meta configuration.
	AllowModuleOverwrite any
	// Gets or sets the CertificateId value of the meta configuration.
	CertificateId any
	// Gets or sets the ConfigurationMode value of the meta configuration.
	ConfigurationMode any
	// Gets or sets the ConfigurationModeFrequencyMins value of the meta configuration.
	ConfigurationModeFrequencyMins any
	// Gets or sets the RebootNodeIfNeeded value of the meta configuration.
	RebootNodeIfNeeded any
	// Gets or sets the RefreshFrequencyMins value of the meta configuration.
	RefreshFrequencyMins any
}

type OpenapiDscNodeReport_Resources_DependsOn struct {
	ResourceId any
}

type OpenapiDscNodeReport_Resources struct {
	DependsOn any
	DurationInSeconds any
	Error any
	ModuleName any
	ModuleVersion any
	ResourceId any
	ResourceName any
	SourceInfo any
	StartDate any
	Status any
}

type OpenapiDscNodeReportConfig struct {
	AutomationAccountName any
	NodeId any
	ReportId any
}

type OpenapiDscNodeReportAttrs struct {
	AutomationAccountName any
	// Gets or sets the configurationVersion of the node report.
	ConfigurationVersion any
	// Gets or sets the end time of the node report.
	EndTime any
	// Gets or sets the errors for the node report.
	Errors any
	// Gets or sets the hostname of the node that sent the report.
	HostName any
	// Gets or sets the IPv4 address of the node that sent the report.
	IPv4Addresses any
	// Gets or sets the IPv6 address of the node that sent the report.
	IPv6Addresses any
	// Gets or sets the id.
	Id any
	// Gets or sets the lastModifiedTime of the node report.
	LastModifiedTime any
	// Definition of the DSC Meta Configuration.
	MetaConfiguration any
	NodeId any
	// Gets or sets the number of resource in the node report.
	NumberOfResources any
	// Gets or sets the unparsed errors for the node report.
	RawErrors any
	// Gets or sets the rebootRequested of the node report.
	RebootRequested any
	// Gets or sets the refreshMode of the node report.
	RefreshMode any
	// Gets or sets the reportFormatVersion of the node report.
	ReportFormatVersion any
	ReportId any
	// Gets or sets the resource for the node report.
	Resources any
	// Gets or sets the start time of the node report.
	StartTime any
	// Gets or sets the status of the node report.
	Status any
	// Gets or sets the type of the node report.
	Type any
}

var OpenapiDscNodeReport = ubx.DataSourceBinding{
	WireType: "azure_automation_openapi_dsc_node_report",
	Fields: ubx.FieldMap{
		"AutomationAccountName": ubx.FieldSpec{WireName: "automation_account_name"},
		"NodeId": ubx.FieldSpec{WireName: "node_id"},
		"ReportId": ubx.FieldSpec{WireName: "report_id"},
	},
}
