// Code generated by `ubx sdk gen` from azure_automation_openapi_webhook. DO NOT EDIT.
package automation

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpenapiWebhook_Value_Properties_Runbook struct {
	Name any
}

type OpenapiWebhook_Value_Properties struct {
	CreationTime     any
	Description      any
	ExpiryTime       any
	IsEnabled        any
	LastInvokedTime  any
	LastModifiedBy   any
	LastModifiedTime any
	Parameters       any
	RunOn            any
	Runbook          any
	Uri              any
}

type OpenapiWebhook_Value struct {
	Properties any
}

type OpenapiWebhookConfig struct {
	AutomationAccountName any
}

type OpenapiWebhookAttrs struct {
	AutomationAccountName any
	// The link to the next page of items
	NextLink any
	// The Webhook items on this page
	Value any
}

var OpenapiWebhook = ubx.DataSourceBinding{
	WireType: "azure_automation_openapi_webhook",
	Fields: ubx.FieldMap{
		"AutomationAccountName": ubx.FieldSpec{WireName: "automation_account_name"},
	},
}
