// Code generated by `ubx sdk gen` from azure_automation_openapi_statistics. DO NOT EDIT.
package automation

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpenapiStatistics_Value struct {
	CounterProperty any
	CounterValue any
	EndTime any
	Id any
	StartTime any
}

type OpenapiStatisticsConfig struct {
	AutomationAccountName any
}

type OpenapiStatisticsAttrs struct {
	AutomationAccountName any
	NextLink any
	// Gets or sets a list of statistics.
	Value any
}

var OpenapiStatistics = ubx.DataSourceBinding{
	WireType: "azure_automation_openapi_statistics",
	Fields: ubx.FieldMap{
		"AutomationAccountName": ubx.FieldSpec{WireName: "automation_account_name"},
	},
}
