# Code generated by `ubx sdk gen` from azure_network_virtualnetwork_virtual_network_peering. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class VirtualnetworkVirtualNetworkPeering_Properties_LocalAddressSpace_IpamPoolPrefixAllocations_Pool:
    id: Any = None

@dataclasses.dataclass
class VirtualnetworkVirtualNetworkPeering_Properties_LocalAddressSpace_IpamPoolPrefixAllocations:
    allocated_address_prefixes: Any = None
    number_of_ip_addresses: Any = None
    pool: Any = None

@dataclasses.dataclass
class VirtualnetworkVirtualNetworkPeering_Properties_LocalAddressSpace:
    # A list of address blocks reserved for this virtual network in CIDR notation.
    address_prefixes: Any = None
    # A list of IPAM Pools allocating IP address prefixes.
    ipam_pool_prefix_allocations: Any = None

@dataclasses.dataclass
class VirtualnetworkVirtualNetworkPeering_Properties_RemoteBgpCommunities:
    # The BGP community associated with the region of the virtual network.
    regional_community: Any = None
    # The BGP community associated with the virtual network.
    virtual_network_community: Any = None

@dataclasses.dataclass
class VirtualnetworkVirtualNetworkPeering_Properties_RemoteVirtualNetworkEncryption:
    # Indicates if encryption is enabled on the virtual network.
    enabled: Any = None
    # If the encrypted VNet allows VM that does not support encryption. This field is for future support, AllowUnencrypted is the only supported value at general availability.
    enforcement: Any = None

@dataclasses.dataclass
class VirtualnetworkVirtualNetworkPeering_Properties:
    # Whether the forwarded traffic from the VMs in the local virtual network will be allowed/disallowed in remote virtual network.
    allow_forwarded_traffic: Any = None
    # If gateway links can be used in remote virtual networking to link to this virtual network.
    allow_gateway_transit: Any = None
    # Whether the VMs in the local virtual network space would be able to access the VMs in remote virtual network space.
    allow_virtual_network_access: Any = None
    # If we need to verify the provisioning state of the remote gateway.
    do_not_verify_remote_gateways: Any = None
    # Whether only Ipv6 address space is peered for subnet peering.
    enable_only_ipv6_peering: Any = None
    # AddressSpace contains an array of IP address ranges that can be used by subnets of the virtual network.
    local_address_space: Any = None
    # List of local subnet names that are subnet peered with remote virtual network.
    local_subnet_names: Any = None
    # AddressSpace contains an array of IP address ranges that can be used by subnets of the virtual network.
    local_virtual_network_address_space: Any = None
    # Whether complete virtual network address space is peered.
    peer_complete_vnets: Any = None
    # The status of the virtual network peering.
    peering_state: Any = None
    # The peering sync status of the virtual network peering.
    peering_sync_level: Any = None
    # Provisioning states of a resource.
    provisioning_state: Any = None
    # AddressSpace contains an array of IP address ranges that can be used by subnets of the virtual network.
    remote_address_space: Any = None
    # Bgp Communities sent over ExpressRoute with each route corresponding to a prefix in this VNET.
    remote_bgp_communities: Any = None
    # List of remote subnet names from remote virtual network that are subnet peered.
    remote_subnet_names: Any = None
    # Reference to another subresource.
    remote_virtual_network: Any = None
    # AddressSpace contains an array of IP address ranges that can be used by subnets of the virtual network.
    remote_virtual_network_address_space: Any = None
    # Indicates if encryption is enabled on virtual network and if VM without encryption is allowed in encrypted VNet.
    remote_virtual_network_encryption: Any = None
    # The resourceGuid property of the Virtual Network peering resource.
    resource_guid: Any = None
    # If remote gateways can be used on this virtual network. If the flag is set to true, and allowGatewayTransit on remote peering is also true, virtual network will use gateways of remote virtual network for transit. Only one peering can have this flag set to true. This flag cannot be set if virtual network already has a gateway.
    use_remote_gateways: Any = None

_VirtualnetworkVirtualNetworkPeering_Properties_LocalAddressSpace_IpamPoolPrefixAllocations_PoolFields = {
    "id": ubx.FieldSpec(wire_name="id"),
}

_VirtualnetworkVirtualNetworkPeering_Properties_LocalAddressSpace_IpamPoolPrefixAllocationsFields = {
    "allocated_address_prefixes": ubx.FieldSpec(wire_name="allocated_address_prefixes"),
    "number_of_ip_addresses": ubx.FieldSpec(wire_name="number_of_ip_addresses"),
    "pool": ubx.FieldSpec(
        wire_name="pool",
        kind="object",
        fields=_VirtualnetworkVirtualNetworkPeering_Properties_LocalAddressSpace_IpamPoolPrefixAllocations_PoolFields,
    ),
}

_VirtualnetworkVirtualNetworkPeering_Properties_LocalAddressSpaceFields = {
    "address_prefixes": ubx.FieldSpec(wire_name="address_prefixes"),
    "ipam_pool_prefix_allocations": ubx.FieldSpec(
        wire_name="ipam_pool_prefix_allocations",
        kind="list",
        fields=_VirtualnetworkVirtualNetworkPeering_Properties_LocalAddressSpace_IpamPoolPrefixAllocationsFields,
    ),
}

_VirtualnetworkVirtualNetworkPeering_Properties_RemoteBgpCommunitiesFields = {
    "regional_community": ubx.FieldSpec(wire_name="regional_community"),
    "virtual_network_community": ubx.FieldSpec(wire_name="virtual_network_community"),
}

_VirtualnetworkVirtualNetworkPeering_Properties_RemoteVirtualNetworkEncryptionFields = {
    "enabled": ubx.FieldSpec(wire_name="enabled"),
    "enforcement": ubx.FieldSpec(wire_name="enforcement"),
}

_VirtualnetworkVirtualNetworkPeering_PropertiesFields = {
    "allow_forwarded_traffic": ubx.FieldSpec(wire_name="allow_forwarded_traffic"),
    "allow_gateway_transit": ubx.FieldSpec(wire_name="allow_gateway_transit"),
    "allow_virtual_network_access": ubx.FieldSpec(wire_name="allow_virtual_network_access"),
    "do_not_verify_remote_gateways": ubx.FieldSpec(wire_name="do_not_verify_remote_gateways"),
    "enable_only_ipv6_peering": ubx.FieldSpec(wire_name="enable_only_ipv6_peering"),
    "local_address_space": ubx.FieldSpec(
        wire_name="local_address_space",
        kind="object",
        fields=_VirtualnetworkVirtualNetworkPeering_Properties_LocalAddressSpaceFields,
    ),
    "local_subnet_names": ubx.FieldSpec(wire_name="local_subnet_names"),
    "local_virtual_network_address_space": ubx.FieldSpec(
        wire_name="local_virtual_network_address_space",
        kind="object",
        fields=_VirtualnetworkVirtualNetworkPeering_Properties_LocalAddressSpaceFields,
    ),
    "peer_complete_vnets": ubx.FieldSpec(wire_name="peer_complete_vnets"),
    "peering_state": ubx.FieldSpec(wire_name="peering_state"),
    "peering_sync_level": ubx.FieldSpec(wire_name="peering_sync_level"),
    "provisioning_state": ubx.FieldSpec(wire_name="provisioning_state"),
    "remote_address_space": ubx.FieldSpec(
        wire_name="remote_address_space",
        kind="object",
        fields=_VirtualnetworkVirtualNetworkPeering_Properties_LocalAddressSpaceFields,
    ),
    "remote_bgp_communities": ubx.FieldSpec(
        wire_name="remote_bgp_communities",
        kind="object",
        fields=_VirtualnetworkVirtualNetworkPeering_Properties_RemoteBgpCommunitiesFields,
    ),
    "remote_subnet_names": ubx.FieldSpec(wire_name="remote_subnet_names"),
    "remote_virtual_network": ubx.FieldSpec(
        wire_name="remote_virtual_network",
        kind="object",
        fields=_VirtualnetworkVirtualNetworkPeering_Properties_LocalAddressSpace_IpamPoolPrefixAllocations_PoolFields,
    ),
    "remote_virtual_network_address_space": ubx.FieldSpec(
        wire_name="remote_virtual_network_address_space",
        kind="object",
        fields=_VirtualnetworkVirtualNetworkPeering_Properties_LocalAddressSpaceFields,
    ),
    "remote_virtual_network_encryption": ubx.FieldSpec(
        wire_name="remote_virtual_network_encryption",
        kind="object",
        fields=_VirtualnetworkVirtualNetworkPeering_Properties_RemoteVirtualNetworkEncryptionFields,
    ),
    "resource_guid": ubx.FieldSpec(wire_name="resource_guid"),
    "use_remote_gateways": ubx.FieldSpec(wire_name="use_remote_gateways"),
}

@dataclasses.dataclass
class VirtualnetworkVirtualNetworkPeeringConfig:
    # Properties of the virtual network peering.
    properties: Any = None

@dataclasses.dataclass
class VirtualnetworkVirtualNetworkPeeringAttrs:
    # A unique read-only string that changes whenever the resource is updated.
    etag: Any = None
    # Properties of the virtual network peering.
    properties: Any = None

VirtualnetworkVirtualNetworkPeering = ubx.ResourceBinding(
    wire_type="azure_network_virtualnetwork_virtual_network_peering",
    fields={
        "properties": ubx.FieldSpec(
            wire_name="properties",
            kind="object",
            fields=_VirtualnetworkVirtualNetworkPeering_PropertiesFields,
        ),
    },
)
