// Code generated by `ubx sdk gen` from azure_azurestackhci_hci_security_setting_list. DO NOT EDIT.
package azurestackhci

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type HciSecuritySettingList_Value_Properties_SecurityComplianceStatus struct {
	DataAtRestEncrypted any
	DataInTransitProtected any
	LastUpdated any
	SecuredCoreCompliance any
	WdacCompliance any
}

type HciSecuritySettingList_Value_Properties struct {
	ProvisioningState any
	SecuredCoreComplianceAssignment any
	SecurityComplianceStatus any
	SmbEncryptionForIntraClusterTrafficComplianceAssignment any
	WdacComplianceAssignment any
}

type HciSecuritySettingList_Value struct {
	Properties any
}

type HciSecuritySettingListConfig struct {
	ClusterName any
}

type HciSecuritySettingListAttrs struct {
	ClusterName any
	// The link to the next page of items
	NextLink any
	// The SecuritySetting items on this page
	Value any
}

var HciSecuritySettingList = ubx.DataSourceBinding{
	WireType: "azure_azurestackhci_hci_security_setting_list",
	Fields: ubx.FieldMap{
		"ClusterName": ubx.FieldSpec{WireName: "cluster_name"},
	},
}
