// Code generated by `ubx sdk gen` from azure_app_openapi_session_pool_collection. DO NOT EDIT.
package app

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpenapiSessionPoolCollection_Value_Identity_UserAssignedIdentities struct {
	ClientId any
	PrincipalId any
}

type OpenapiSessionPoolCollection_Value_Identity struct {
	PrincipalId any
	TenantId any
	Type any
	UserAssignedIdentities any
}

type OpenapiSessionPoolCollection_Value_Properties_CustomContainerTemplate_Containers_Env struct {
	Name any
	SecretRef any
	Value any
}

type OpenapiSessionPoolCollection_Value_Properties_CustomContainerTemplate_Containers_Resources struct {
	Cpu any
	Memory any
}

type OpenapiSessionPoolCollection_Value_Properties_CustomContainerTemplate_Containers struct {
	Args any
	Command any
	Env any
	Image any
	Name any
	Resources any
}

type OpenapiSessionPoolCollection_Value_Properties_CustomContainerTemplate_Ingress struct {
	TargetPort any
}

type OpenapiSessionPoolCollection_Value_Properties_CustomContainerTemplate_RegistryCredentials struct {
	Identity any
	PasswordSecretRef any
	Server any
	Username any
}

type OpenapiSessionPoolCollection_Value_Properties_CustomContainerTemplate struct {
	Containers any
	Ingress any
	RegistryCredentials any
}

type OpenapiSessionPoolCollection_Value_Properties_DynamicPoolConfiguration_LifecycleConfiguration struct {
	CooldownPeriodInSeconds any
	LifecycleType any
	MaxAlivePeriodInSeconds any
}

type OpenapiSessionPoolCollection_Value_Properties_DynamicPoolConfiguration struct {
	LifecycleConfiguration any
}

type OpenapiSessionPoolCollection_Value_Properties_ManagedIdentitySettings struct {
	Identity any
	Lifecycle any
}

type OpenapiSessionPoolCollection_Value_Properties_ScaleConfiguration struct {
	MaxConcurrentSessions any
	ReadySessionInstances any
}

type OpenapiSessionPoolCollection_Value_Properties_Secrets struct {
	Name any
	Value any
}

type OpenapiSessionPoolCollection_Value_Properties_SessionNetworkConfiguration struct {
	Status any
}

type OpenapiSessionPoolCollection_Value_Properties struct {
	ContainerType any
	CustomContainerTemplate any
	DynamicPoolConfiguration any
	EnvironmentId any
	ManagedIdentitySettings any
	NodeCount any
	PoolManagementEndpoint any
	PoolManagementType any
	ProvisioningState any
	ScaleConfiguration any
	Secrets any
	SessionNetworkConfiguration any
}

type OpenapiSessionPoolCollection_Value struct {
	Identity any
	Properties any
}

type OpenapiSessionPoolCollectionConfig struct {
}

type OpenapiSessionPoolCollectionAttrs struct {
	// The link to the next page of items
	NextLink any
	// The SessionPool items on this page
	Value any
}

var OpenapiSessionPoolCollection = ubx.DataSourceBinding{
	WireType: "azure_app_openapi_session_pool_collection",
	Fields: ubx.FieldMap{
	},
}
