// Code generated by `ubx sdk gen` from azure_app_openapi_auth_config_list. DO NOT EDIT.
package app

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpenapiAuthConfigList_Value_Properties_EncryptionSettings struct {
	ContainerAppAuthEncryptionSecretName any
	ContainerAppAuthSigningSecretName    any
}

type OpenapiAuthConfigList_Value_Properties_GlobalValidation struct {
	ExcludedPaths               any
	RedirectToProvider          any
	UnauthenticatedClientAction any
}

type OpenapiAuthConfigList_Value_Properties_HttpSettings_ForwardProxy struct {
	Convention            any
	CustomHostHeaderName  any
	CustomProtoHeaderName any
}

type OpenapiAuthConfigList_Value_Properties_HttpSettings_Routes struct {
	ApiPrefix any
}

type OpenapiAuthConfigList_Value_Properties_HttpSettings struct {
	ForwardProxy any
	RequireHttps any
	Routes       any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_Apple_Login struct {
	Scopes any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_Apple_Registration struct {
	ClientId                any
	ClientSecretSettingName any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_Apple struct {
	Enabled      any
	Login        any
	Registration any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_AzureActiveDirectory_Login struct {
	DisableWwwauthenticate any
	LoginParameters        any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_AzureActiveDirectory_Registration struct {
	ClientId                                      any
	ClientSecretCertificateIssuer                 any
	ClientSecretCertificateSubjectAlternativeName any
	ClientSecretCertificateThumbprint             any
	ClientSecretSettingName                       any
	OpenIdIssuer                                  any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_AzureActiveDirectory_Validation_DefaultAuthorizationPolicy_AllowedPrincipals struct {
	Groups     any
	Identities any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_AzureActiveDirectory_Validation_DefaultAuthorizationPolicy struct {
	AllowedApplications any
	AllowedPrincipals   any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_AzureActiveDirectory_Validation_JwtClaimChecks struct {
	AllowedClientApplications any
	AllowedGroups             any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_AzureActiveDirectory_Validation struct {
	AllowedAudiences           any
	DefaultAuthorizationPolicy any
	JwtClaimChecks             any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_AzureActiveDirectory struct {
	Enabled           any
	IsAutoProvisioned any
	Login             any
	Registration      any
	Validation        any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_AzureStaticWebApps_Registration struct {
	ClientId any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_AzureStaticWebApps struct {
	Enabled      any
	Registration any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_CustomOpenIdConnectProviders_Login struct {
	NameClaimType any
	Scopes        any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_CustomOpenIdConnectProviders_Registration_ClientCredential struct {
	ClientSecretSettingName any
	Method                  any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_CustomOpenIdConnectProviders_Registration_OpenIdConnectConfiguration struct {
	AuthorizationEndpoint        any
	CertificationUri             any
	Issuer                       any
	TokenEndpoint                any
	WellKnownOpenIdConfiguration any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_CustomOpenIdConnectProviders_Registration struct {
	ClientCredential           any
	ClientId                   any
	OpenIdConnectConfiguration any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_CustomOpenIdConnectProviders struct {
	Enabled      any
	Login        any
	Registration any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_Facebook_Registration struct {
	AppId                any
	AppSecretSettingName any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_Facebook struct {
	Enabled         any
	GraphApiVersion any
	Login           any
	Registration    any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_Google_Validation struct {
	AllowedAudiences any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_Google struct {
	Enabled      any
	Login        any
	Registration any
	Validation   any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_Twitter_Registration struct {
	ConsumerKey               any
	ConsumerSecretSettingName any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders_Twitter struct {
	Enabled      any
	Registration any
}

type OpenapiAuthConfigList_Value_Properties_IdentityProviders struct {
	Apple                        any
	AzureActiveDirectory         any
	AzureStaticWebApps           any
	CustomOpenIdConnectProviders any
	Facebook                     any
	GitHub                       any
	Google                       any
	Twitter                      any
}

type OpenapiAuthConfigList_Value_Properties_Login_CookieExpiration struct {
	Convention       any
	TimeToExpiration any
}

type OpenapiAuthConfigList_Value_Properties_Login_Nonce struct {
	NonceExpirationInterval any
	ValidateNonce           any
}

type OpenapiAuthConfigList_Value_Properties_Login_Routes struct {
	LogoutEndpoint any
}

type OpenapiAuthConfigList_Value_Properties_Login_TokenStore_AzureBlobStorage struct {
	SasUrlSettingName any
}

type OpenapiAuthConfigList_Value_Properties_Login_TokenStore struct {
	AzureBlobStorage           any
	Enabled                    any
	TokenRefreshExtensionHours any
}

type OpenapiAuthConfigList_Value_Properties_Login struct {
	AllowedExternalRedirectUrls   any
	CookieExpiration              any
	Nonce                         any
	PreserveUrlFragmentsForLogins any
	Routes                        any
	TokenStore                    any
}

type OpenapiAuthConfigList_Value_Properties_Platform struct {
	Enabled        any
	RuntimeVersion any
}

type OpenapiAuthConfigList_Value_Properties struct {
	EncryptionSettings any
	GlobalValidation   any
	HttpSettings       any
	IdentityProviders  any
	Login              any
	Platform           any
}

type OpenapiAuthConfigList_Value struct {
	Properties any
}

type OpenapiAuthConfigListConfig struct {
	ContainerAppName any
}

type OpenapiAuthConfigListAttrs struct {
	ContainerAppName any
	// The link to the next page of items
	NextLink any
	// The AuthConfig items on this page
	Value any
}

var OpenapiAuthConfigList = ubx.DataSourceBinding{
	WireType: "azure_app_openapi_auth_config_list",
	Fields: ubx.FieldMap{
		"ContainerAppName": ubx.FieldSpec{WireName: "container_app_name"},
	},
}
