// Code generated by `ubx sdk gen` from azure_oracle_openapi_db_version. DO NOT EDIT.
package oracle

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpenapiDbVersion_Properties struct {
	// True if this version of the Oracle Database software is the latest version for a release.
	IsLatestForMajorVersion any
	// True if this version of the Oracle Database software is the preview version.
	IsPreviewDbVersion any
	// True if this version of the Oracle Database software is supported for Upgrade.
	IsUpgradeSupported any
	// True if this version of the Oracle Database software supports pluggable databases.
	SupportsPdb any
	// A valid Oracle Database version.
	Version any
}

type OpenapiDbVersionConfig struct {
	Dbversionsname any
}

type OpenapiDbVersionAttrs struct {
	Dbversionsname any
	// DbVersion resource model
	Properties any
}

var OpenapiDbVersion = ubx.DataSourceBinding{
	WireType: "azure_oracle_openapi_db_version",
	Fields: ubx.FieldMap{
		"Dbversionsname": ubx.FieldSpec{WireName: "dbversionsname"},
	},
}
