// Code generated by `ubx sdk gen` from azure_oracle_openapi_exascale_db_storage_vault. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface OpenapiExascaleDbStorageVault_Properties_HighCapacityDatabaseStorage {
  /** Available Capacity */
  availableSizeInGbs?: number | Computed<number>;
  /** Total Capacity */
  totalSizeInGbs?: number | Computed<number>;
}

export interface OpenapiExascaleDbStorageVault_Properties_HighCapacityDatabaseStorageInput {
  /** Total Capacity */
  totalSizeInGbs: number | Computed<number>;
}

export interface OpenapiExascaleDbStorageVault_Properties {
  /** The size of additional Flash Cache in percentage of High Capacity database storage. */
  additionalFlashCacheInPercent?: number | Computed<number>;
  /** The shapeAttribute of the Exadata VM cluster(s) associated with the Exadata Database Storage Vault. */
  attachedShapeAttributes?: string[] | Computed<string[]>;
  /** Exadata Database Storage Vault description. */
  description?: string | Computed<string>;
  /** The user-friendly name for the Exadata Database Storage Vault. The name does not need to be unique. */
  displayName: string | Computed<string>;
  /** A type definition that refers the id to an Azure Resource Manager resource. */
  exadataInfrastructureId?: string | Computed<string>;
  /** Exadata Database Storage Details */
  highCapacityDatabaseStorage?: OpenapiExascaleDbStorageVault_Properties_HighCapacityDatabaseStorage | Computed<OpenapiExascaleDbStorageVault_Properties_HighCapacityDatabaseStorage>;
  /** Create exadata Database Storage Details model */
  highCapacityDatabaseStorageInput: OpenapiExascaleDbStorageVault_Properties_HighCapacityDatabaseStorageInput | Computed<OpenapiExascaleDbStorageVault_Properties_HighCapacityDatabaseStorageInput>;
  /** Additional information about the current lifecycle state. */
  lifecycleDetails?: string | Computed<string>;
  /** Exadata Database Storage Vault lifecycle state enum */
  lifecycleState?: string | Computed<string>;
  /** HTTPS link to OCI resources exposed to Azure Customer via Azure Interface. */
  ociUrl?: string | Computed<string>;
  /** The [OCID](/Content/General/Concepts/identifiers.htm) of the resource. */
  ocid?: string | Computed<string>;
  /** Azure Resource Provisioning State enum */
  provisioningState?: string | Computed<string>;
  /** The time zone that you want to use for the Exadata Database Storage Vault */
  timeZone?: string | Computed<string>;
  /** The number of Exadata VM clusters used the Exadata Database Storage Vault. */
  vmClusterCount?: number | Computed<number>;
}

const OpenapiExascaleDbStorageVault_Properties_HighCapacityDatabaseStorageFields: FieldMap = {
  availableSizeInGbs: "available_size_in_gbs",
  totalSizeInGbs: "total_size_in_gbs",
};

const OpenapiExascaleDbStorageVault_Properties_HighCapacityDatabaseStorageInputFields: FieldMap = {
  totalSizeInGbs: "total_size_in_gbs",
};

const OpenapiExascaleDbStorageVault_PropertiesFields: FieldMap = {
  additionalFlashCacheInPercent: "additional_flash_cache_in_percent",
  attachedShapeAttributes: "attached_shape_attributes",
  description: "description",
  displayName: "display_name",
  exadataInfrastructureId: "exadata_infrastructure_id",
  highCapacityDatabaseStorage: {
    wireName: "high_capacity_database_storage",
    kind: "object",
    fields: OpenapiExascaleDbStorageVault_Properties_HighCapacityDatabaseStorageFields,
  },
  highCapacityDatabaseStorageInput: {
    wireName: "high_capacity_database_storage_input",
    kind: "object",
    fields: OpenapiExascaleDbStorageVault_Properties_HighCapacityDatabaseStorageInputFields,
  },
  lifecycleDetails: "lifecycle_details",
  lifecycleState: "lifecycle_state",
  ociUrl: "oci_url",
  ocid: "ocid",
  provisioningState: "provisioning_state",
  timeZone: "time_zone",
  vmClusterCount: "vm_cluster_count",
};

export interface OpenapiExascaleDbStorageVaultConfig {
  /** ExascaleDbStorageVault resource model */
  properties?: OpenapiExascaleDbStorageVault_Properties | Computed<OpenapiExascaleDbStorageVault_Properties>;
  /** The availability zones. */
  zones?: string[] | Computed<string[]>;
}

export interface OpenapiExascaleDbStorageVaultAttrs {
  /** ExascaleDbStorageVault resource model */
  properties: OpenapiExascaleDbStorageVault_Properties;
  /** The availability zones. */
  zones: string[];
}

export const OpenapiExascaleDbStorageVault: ResourceBinding<OpenapiExascaleDbStorageVaultConfig, OpenapiExascaleDbStorageVaultAttrs> = {
  wireType: "azure_oracle_openapi_exascale_db_storage_vault",
  fields: {
    properties: {
      wireName: "properties",
      kind: "object",
      fields: OpenapiExascaleDbStorageVault_PropertiesFields,
    },
    zones: "zones",
  },
};
