# Code generated by `ubx sdk gen` from azure_synapse_workspace_restorable_dropped_sql_pool_list. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class WorkspaceRestorableDroppedSqlPoolList_Value_Properties:
    creation_date: Any = None
    database_name: Any = None
    deletion_date: Any = None
    earliest_restore_date: Any = None
    edition: Any = None
    elastic_pool_name: Any = None
    max_size_bytes: Any = None
    service_level_objective: Any = None

@dataclasses.dataclass
class WorkspaceRestorableDroppedSqlPoolList_Value:
    location: Any = None
    properties: Any = None

@dataclasses.dataclass
class WorkspaceRestorableDroppedSqlPoolListConfig:
    pass

@dataclasses.dataclass
class WorkspaceRestorableDroppedSqlPoolListAttrs:
    # A list of restorable dropped Sql pools
    value: Any = None

WorkspaceRestorableDroppedSqlPoolList = ubx.DataSourceBinding(
    wire_type="azure_synapse_workspace_restorable_dropped_sql_pool_list",
    fields={
    },
)
